# Generated by Django 4.1.3 on 2023-04-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Taxa')),
                ('ativo', models.BooleanField(default=False, verbose_name='Taxa ativa?')),
            ],
            options={
                'verbose_name': '2. Taxa',
                'verbose_name_plural': '2. Taxas',
            },
        ),
    ]
