# Generated by Django 4.1.3 on 2023-04-27 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portabilidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxa',
            options={'verbose_name': 'Taxa', 'verbose_name_plural': 'Taxas'},
        ),
    ]
