# Generated by Django 4.1.3 on 2023-04-21 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envelopecontratos',
            old_name='unique_id',
            new_name='token_envelope',
        ),
        migrations.RemoveField(
            model_name='envelopecontratos',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='envelopecontratos',
            name='criado_por',
        ),
        migrations.AddField(
            model_name='contrato',
            name='token_envelope',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='envelopecontratos',
            name='id_processo_unico',
            field=models.TextField(blank=True, null=True, verbose_name='ID processo - Unico'),
        ),
        migrations.AddField(
            model_name='envelopecontratos',
            name='score_unico',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Score Unico'),
        ),
    ]
