# Generated by Django 4.1.3 on 2023-04-22 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_rename_unique_id_envelopecontratos_token_envelope_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('numero_contrato', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Número Contrato')),
                ('saldo_devedor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='Saldo Devedor')),
                ('prazo', models.IntegerField(blank=True, verbose_name='Prazo')),
                ('taxa', models.DecimalField(blank=True, decimal_places=7, default=None, max_digits=12, null=True, verbose_name='Taxa')),
                ('antiga_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='Parcela Antiga')),
                ('nova_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='Nova Parcela')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Portabilidade',
                'verbose_name_plural': 'Portabilidade',
            },
        ),
    ]
