# Generated by Django 4.1.3 on 2023-04-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_portabilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_produto',
            field=models.SmallIntegerField(choices=[(1, 'FGTS'), (2, 'INSS - Representante Legal'), (3, 'Cartão Benefício - Representante Legal'), (4, 'PAB'), (5, 'INSS CORBAN'), (6, 'INSS'), (7, 'Cartão Benefício'), (8, 'Consignado')], default=1, verbose_name='Tipo de Produto'),
        ),
    ]
