# Generated by Django 4.1.3 on 2023-04-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_alter_contrato_tipo_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='token_envelope',
            field=models.UUIDField(null=True, verbose_name='Token do envelope'),
        ),
    ]
