# Generated by Django 4.1.3 on 2023-04-22 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_alter_contrato_token_envelope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portabilidade',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_portabilidade', to='contract.contrato', verbose_name='Contrato'),
        ),
    ]
