# Generated by Django 4.1.3 on 2023-04-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_alter_portabilidade_contrato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosProduto',
        ),
    ]
