# Generated by Django 4.1.3 on 2023-04-24 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_delete_dadosproduto'),
        ('contract', '0009_alter_envelopecontratos_options_and_more'),
    ]

    operations = [
    ]
