# Generated by Django 4.1.3 on 2023-04-25 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_cartaobeneficio_status_alter_statuscontrato_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuscontrato',
            options={'verbose_name': 'Status dos contratos', 'verbose_name_plural': 'Status dos contratos'},
        ),
        migrations.AddField(
            model_name='statuscontrato',
            name='data_fase_inicial',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da fase inicial'),
            preserve_default=False,
        ),
    ]
