# Generated by Django 4.1.3 on 2023-04-25 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0012_alter_statuscontrato_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='criando_por',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='criadoPor', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='statuscontrato',
            name='descricao_inicial',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Descrição Inicial'),
        ),
        migrations.AlterField(
            model_name='statuscontrato',
            name='descricao_mesa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Descrição da Mesa'),
        ),
        migrations.AlterField(
            model_name='statuscontrato',
            name='descricao_originacao',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Descrição Originação'),
        ),
    ]
