# Generated by Django 4.1.3 on 2023-04-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_alter_contrato_tipo_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaobeneficio',
            name='id_envelope_unico',
            field=models.TextField(blank=True, null=True, verbose_name='UUID do envelope - Unico'),
        ),
        migrations.AddField(
            model_name='cartaobeneficio',
            name='id_processo_unico',
            field=models.TextField(blank=True, null=True, verbose_name='ID processo - Unico'),
        ),
        migrations.AddField(
            model_name='cartaobeneficio',
            name='score_unico',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Score Unico'),
        ),
    ]
