# Generated by Django 4.1.3 on 2023-04-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0015_cartaobeneficio_id_envelope_unico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaobeneficio',
            name='id_envelope_unico',
        ),
        migrations.RemoveField(
            model_name='cartaobeneficio',
            name='id_processo_unico',
        ),
        migrations.RemoveField(
            model_name='cartaobeneficio',
            name='score_unico',
        ),
    ]
