# Generated by Django 4.1.3 on 2023-04-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0017_contrato_corban_contrato_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='criado_por',
        ),
    ]
