# Generated by Django 4.1.3 on 2023-04-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_remove_contrato_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacaocontrato',
            name='retorno_hub',
            field=models.CharField(max_length=200, verbose_name='Código extensão'),
        ),
    ]
