# Generated by Django 4.1.3 on 2023-04-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0019_alter_validacaocontrato_retorno_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='limite_pre_aprovado',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name='Valor do limite pré-aprovado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='taxa',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='Taxa da operação'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='taxa_efetiva_ano',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Taxa considerada no contrato', max_digits=12, null=True, verbose_name='Taxa efetiva ao ano da operação'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='taxa_efetiva_mes',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Taxa considerada no contrato', max_digits=12, null=True, verbose_name='Taxa efetiva ao mês da operação'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='taxa_seguro',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='Taxa do seguro prestamista'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='vr_iof',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='Valor do IOF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='vr_iof_adicional',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='IOF Adicional'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='vr_liberado_cliente',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='Valor liberado Cliente'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='vr_tac',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='Valor TAC'),
        ),
    ]
