# Generated by Django 4.1.3 on 2023-04-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0020_alter_contrato_limite_pre_aprovado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaobeneficio',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_cartao_beneficio', to='contract.contrato', verbose_name='Contrato'),
        ),
    ]
