# Generated by Django 4.1.3 on 2023-04-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0021_alter_cartaobeneficio_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inss',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_inss', to='contract.contrato', verbose_name='Contrato'),
        ),
    ]
