# Generated by Django 4.1.3 on 2023-04-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0022_alter_inss_contrato'),
        ('contract', '0022_remove_cartaobeneficio_enviado_comprovante_residencia_and_more'),
    ]

    operations = [
    ]
