# Generated by Django 4.1.3 on 2023-04-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0024_alter_anexocontrato_tipo_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacaocontrato',
            name='checked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='validacaocontrato',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inserido em'),
        ),
        migrations.AlterField(
            model_name='validacaocontrato',
            name='mensagem_observacao',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Mensagem de Observação'),
        ),
        migrations.AlterField(
            model_name='validacaocontrato',
            name='retorno_hub',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Código extensão'),
        ),
    ]
