# Generated by Django 4.1.3 on 2023-04-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0025_alter_validacaocontrato_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacaocontrato',
            name='checked',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
