# Generated by Django 4.1.3 on 2023-04-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0026_alter_validacaocontrato_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacaocontrato',
            name='retorno_hub',
            field=models.TextField(default='', verbose_name='Código extensão'),
        ),
    ]
