# Generated by Django 4.1.3 on 2023-04-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0027_alter_validacaocontrato_retorno_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacaocontrato',
            name='retorno_hub',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Código extensão'),
        ),
    ]
