# Generated by Django 4.1.3 on 2023-05-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0028_alter_validacaocontrato_retorno_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaobeneficio',
            name='valor_financiado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor lançado em fatura'),
        ),
    ]
