# Generated by Django 4.1.3 on 2023-05-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0029_alter_cartaobeneficio_valor_financiado'),
        ('contract', '0029_retornosaque'),
    ]

    operations = [
    ]
