# Generated by Django 4.1.3 on 2023-05-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0033_alter_cartaobeneficio_status_alter_inss_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portabilidade",
            name="chave_proposta",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Nova chave_proposta",
            ),
        ),
        migrations.AddField(
            model_name="portabilidade",
            name="status_ccb",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (0, "Pendente - Pedido CCB"),
                    (1, "Aguardadndo - Resposta CCB"),
                    (2, "Aprovado - Aprovado CCB"),
                ],
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="cartaobeneficio",
            name="status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Simulação"),
                    (5, "Formalizaçao (cliente)"),
                    (6, "Aprovada – Finalizada"),
                    (7, "Reprovada – Finalizada"),
                    (8, "Checagem – Mesa Formalização"),
                    (9, "Aprovada – Mesa Formalização"),
                    (10, "Reprovada – Finalizada"),
                    (11, "Pendente Documentação"),
                    (12, "Em averbação"),
                    (13, "Aprovada - Averbação"),
                    (14, "Recusada - Averbação"),
                    (15, "Andamento – Emissão cartão"),
                    (16, "Finalizada – Emissão cartão"),
                    (17, "Andamento – Liberação Pagamento Saque"),
                    (18, "Finalizado – Liberação Pagamento Saque"),
                    (19, "Pendente - Correção de dados bancários"),
                ],
                default=1,
                null=True,
                verbose_name="Status do Contrato",
            ),
        ),
        migrations.AlterField(
            model_name="inss",
            name="status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Simulação"),
                    (5, "Formalizaçao (cliente)"),
                    (6, "Aprovada – Finalizada"),
                    (7, "Reprovada – Finalizada"),
                    (8, "Checagem – Mesa Formalização"),
                    (9, "Aprovada – Mesa Formalização"),
                    (10, "Reprovada – Finalizada"),
                    (11, "Pendente Documentação"),
                    (12, "Em averbação"),
                    (13, "Aprovada - Averbação"),
                    (14, "Recusada - Averbação"),
                    (15, "Andamento – Emissão cartão"),
                    (16, "Finalizada – Emissão cartão"),
                    (17, "Andamento – Liberação Pagamento Saque"),
                    (18, "Finalizado – Liberação Pagamento Saque"),
                    (19, "Pendente - Correção de dados bancários"),
                ],
                default=1,
                null=True,
                verbose_name="Status do Contrato",
            ),
        ),
        migrations.AlterField(
            model_name="portabilidade",
            name="status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Simulação"),
                    (5, "Formalizaçao (cliente)"),
                    (6, "Aprovada – Finalizada"),
                    (7, "Reprovada – Finalizada"),
                    (8, "Checagem – Mesa Formalização"),
                    (9, "Aprovada – Mesa Formalização"),
                    (10, "Reprovada – Finalizada"),
                    (11, "Pendente Documentação"),
                    (12, "Em averbação"),
                    (13, "Aprovada - Averbação"),
                    (14, "Recusada - Averbação"),
                    (15, "Andamento – Emissão cartão"),
                    (16, "Finalizada – Emissão cartão"),
                    (17, "Andamento – Liberação Pagamento Saque"),
                    (18, "Finalizado – Liberação Pagamento Saque"),
                    (19, "Pendente - Correção de dados bancários"),
                ],
                default=1,
                null=True,
                verbose_name="Status do Contrato",
            ),
        ),
        migrations.AlterField(
            model_name="statuscontrato",
            name="nome",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Simulação"),
                    (5, "Formalizaçao (cliente)"),
                    (6, "Aprovada – Finalizada"),
                    (7, "Reprovada – Finalizada"),
                    (8, "Checagem – Mesa Formalização"),
                    (9, "Aprovada – Mesa Formalização"),
                    (10, "Reprovada – Finalizada"),
                    (11, "Pendente Documentação"),
                    (12, "Em averbação"),
                    (13, "Aprovada - Averbação"),
                    (14, "Recusada - Averbação"),
                    (15, "Andamento – Emissão cartão"),
                    (16, "Finalizada – Emissão cartão"),
                    (17, "Andamento – Liberação Pagamento Saque"),
                    (18, "Finalizado – Liberação Pagamento Saque"),
                    (19, "Pendente - Correção de dados bancários"),
                ],
                default=1,
                null=True,
                verbose_name="Nome do status",
            ),
        ),
    ]
