# Generated by Django 4.1.3 on 2023-05-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0035_remove_inss_vr_liberado_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='inss',
            name='dt_vencimento_primeira_parcela',
            field=models.DateField(blank=True, null=True, verbose_name='Data de vencimento da primeira parcela'),
        ),
        migrations.AddField(
            model_name='inss',
            name='dt_vencimento_ultima_parcela',
            field=models.DateField(blank=True, null=True, verbose_name='Data de vencimento da ultima parcela'),
        ),
    ]
