# Generated by Django 4.1.3 on 2023-05-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0036_inss_dt_vencimento_primeira_parcela_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inss',
            name='vr_parcela_maxima',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor maximo da Parcela'),
        ),
        migrations.AddField(
            model_name='inss',
            name='vr_parcela_minima',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor minimo da Parcela'),
        ),
    ]
