# Generated by Django 4.1.3 on 2023-05-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0034_portabilidade_chave_proposta_and_more'),
        ('contract', '0037_inss_vr_parcela_maxima_inss_vr_parcela_minima'),
    ]

    operations = [
    ]
