# Generated by Django 4.1.3 on 2023-05-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0038_merge_20230507_1637'),
        ('contract', '0039_alter_portabilidade_chave_proposta'),
    ]

    operations = [
    ]
