# Generated by Django 4.1.3 on 2023-05-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0039_alter_portabilidade_chave_proposta"),
    ]

    operations = [
        migrations.AddField(
            model_name="portabilidade",
            name="numero_portabilidade",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Número portabilidade - Qitech",
            ),
        ),
    ]
