# Generated by Django 4.1.3 on 2023-05-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0040_portabilidade_numero_portabilidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portabilidade",
            name="status_ccb",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (0, "pending_subimission"),
                    (1, "pending_acceptance"),
                    (2, "accepted"),
                    (3, "canceled"),
                    (4, "retained"),
                    (5, "settlement_sent"),
                    (6, "pending_settlement_confirmation"),
                    (7, "paid"),
                    (8, " rejected"),
                ],
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
