# Generated by Django 4.1.3 on 2023-05-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0041_alter_portabilidade_status_ccb'),
        ('contract', '0041_alter_statuscontrato_descricao_inicial_and_more'),
    ]

    operations = [
    ]
