# Generated by Django 4.1.3 on 2023-05-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0042_merge_20230508_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portabilidade',
            name='status_ccb',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'pending_subimission'), (1, 'pending_response'), (2, 'pending_acceptance'), (3, 'accepted'), (4, 'canceled'), (5, 'retained'), (6, 'settlement_sent'), (7, 'pending_settlement_confirmation'), (8, 'paid'), (9, ' rejected')], null=True, verbose_name='Status'),
        ),
    ]
