# Generated by Django 4.1.3 on 2023-05-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0046_alter_portabilidade_document_key_qitech_ccb'),
    ]

    operations = [
        migrations.AddField(
            model_name='portabilidade',
            name='document_key_QiTech_Selfie',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chave da Selfie'),
        ),
        migrations.AlterField(
            model_name='portabilidade',
            name='document_key_QiTech_CCB',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chave do Documento CCB'),
        ),
    ]
