# Generated by Django 4.1.3 on 2023-05-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0049_portabilidade_related_party_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retornosaque',
            options={'verbose_name': 'Retorno Saque', 'verbose_name_plural': 'Retorno Saque'},
        ),
    ]
