# Generated by Django 4.1.3 on 2023-05-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0050_alter_retornosaque_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaobeneficio',
            name='numero_proposta_banksoft',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero da Proposta(Banksoft)'),
        ),
    ]
