# Generated by Django 4.1.3 on 2023-05-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0052_retornosaque_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='portabilidade',
            name='parcela_digitada',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=20, verbose_name='Parcela Digitada'),
            preserve_default=False,
        ),
    ]
