# Generated by Django 4.1.3 on 2023-05-22 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0053_alter_statuscontrato_descricao_mesa'),
        ('contract', '0053_portabilidade_parcela_digitada'),
    ]

    operations = [
    ]
