# Generated by Django 4.1.3 on 2023-05-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0053_portabilidade_parcela_digitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portabilidade',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Aguarda envio link'), (2, 'Formalização (cliente)'), (3, 'Análise de crédito (Bureaus)'), (4, 'Pendente - Dados Divergentes'), (5, 'Reprovada – Política Interna'), (6, 'Checagem - Mesa Corban'), (7, 'Pendente Documentação - Mesa Corban'), (8, 'Reprovada – Mesa Corban'), (9, 'Aprovada - Mesa Corban'), (10, 'Checagem - Mesa de Formalização'), (11, 'Aprovada - Mesa de Formalização'), (12, 'Reprovada – Mesa de Formalização'), (13, 'Aguarda Retorno Saldo'), (14, 'Saldo Retornado'), (15, 'INT - Confirma pagamento'), (16, 'Saldo Reprovado'), (17, 'Reprovada - Pagamento Devolvido'), (18, 'Int - Aguarda Averbação'), (19, 'Int - Finalizado'), (20, 'Int - Averbação Pendente')], default=1, null=True, verbose_name='Status do Contrato'),
        ),
    ]
