# Generated by Django 4.1.3 on 2023-05-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_corban_mesa_corban'),
        ('contract', '0054_alter_portabilidade_numero_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='corban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corban_loja', to='custom_auth.corban', verbose_name='Corban'),
        ),
    ]
