# Generated by Django 4.1.3 on 2023-05-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0053_alter_statuscontrato_descricao_mesa'),
        ('contract', '0055_alter_contrato_corban'),
    ]

    operations = [
    ]
