# Generated by Django 4.1.3 on 2023-05-22 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0054_merge_20230522_1041'),
        ('contract', '0056_merge_20230522_1116'),
    ]

    operations = [
    ]
