# Generated by Django 4.1.3 on 2023-05-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0054_alter_portabilidade_status'),
        ('contract', '0057_merge_20230522_1735'),
    ]

    operations = [
    ]
