# Generated by Django 4.1.3 on 2023-05-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0059_alter_cartaobeneficio_status_alter_inss_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portabilidade',
            name='numero_parcela_atualizada',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero Parcelas Atualizada'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='numero_portabilidade_CTC_CIP',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numero da Portabilidade CTC/CIP'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='saldo_devedor_atualizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Saldo Devedor Atualizado'),
        ),
    ]
