# Generated by Django 4.1.3 on 2023-05-25 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0059_alter_cartaobeneficio_status_alter_inss_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscontrato',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
