# Generated by Django 4.1.3 on 2023-05-25 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0060_statuscontrato_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscontrato',
            name='data_fase_final',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da fase final'),
            preserve_default=False,
        ),
    ]
