# Generated by Django 4.1.3 on 2023-05-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0060_portabilidade_numero_parcela_atualizada_and_more'),
        ('contract', '0061_statuscontrato_data_fase_final'),
    ]

    operations = [
    ]
