# Generated by Django 4.1.3 on 2023-05-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0062_merge_20230526_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='portabilidade',
            name='especie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Especie'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='numero_beneficio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Benefício'),
        ),
    ]
