# Generated by Django 4.1.3 on 2023-05-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0063_portabilidade_especie_portabilidade_numero_beneficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portabilidade',
            name='motivo_recusa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo de Recusa do CTC/CIP'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='taxa_contrato_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor da Parcela Original'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='valor_parcela_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor da Parcela Original'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='valor_parcela_recalculada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor da Parcela Recalculada'),
        ),
    ]
