# Generated by Django 4.1.3 on 2023-05-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0064_portabilidade_motivo_recusa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portabilidade',
            name='taxa_contrato_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Taxa Contrato Original'),
        ),
    ]
