# Generated by Django 4.1.3 on 2023-06-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0065_alter_portabilidade_taxa_contrato_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='portabilidade',
            name='CPF_dados_divergentes',
            field=models.BooleanField(default=False, help_text='Indica se o CPF está Irregular na Receita Federal', verbose_name='CPF irregular na receita?'),
        ),
    ]
