# Generated by Django 4.2.2 on 2023-06-11 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0066_portabilidade_cpf_dados_divergentes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ('-ultima_atualizacao', 'status'), 'verbose_name': 'Contrato', 'verbose_name_plural': '1. Contratos'},
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_pago',
            field=models.BooleanField(default=False, verbose_name='Contrato pago?'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Digitado por'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='última atualização'),
        ),
        migrations.AlterField(
            model_name='validacaocontrato',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_validacoes', to='contract.contrato', verbose_name='Contrato'),
        ),
    ]
