# Generated by Django 4.1.3 on 2023-06-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0067_alter_contrato_options_contrato_contrato_pago_and_more'),
        ('contract', '0067_alter_contrato_tipo_produto'),
    ]

    operations = [
    ]
