# Generated by Django 4.1.3 on 2023-06-12 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0068_merge_20230612_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cd_contrato_tipo',
            field=models.SmallIntegerField(choices=[(1, 'Operação nova (margem livre)'), (2, 'Refinanciamento'), (3, 'Refin Portabilidade'), (4, 'Portabilidade'), (5, 'Novo Aumento Salarial'), (6, 'Saque Complementar')], verbose_name='Tipo do contrato'),
        ),
        migrations.CreateModel(
            name='SaqueComplementar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente')], default=1, null=True, verbose_name='Status do Contrato')),
                ('limite_disponivel_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Limite disponível total')),
                ('saque_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saque mínimo')),
                ('valor_disponivel_saque', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor disponível para saque')),
                ('valor_lancado_fatura', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor lançado em fatura')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_saque_complementar', to='contract.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Saque Complementar',
                'verbose_name_plural': 'Saque Complementar',
            },
        ),
    ]
