# Generated by Django 4.2.2 on 2023-06-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0071_alter_contrato_tipo_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='saquecomplementar',
            name='valor_saque',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor saque'),
        ),
    ]
