# Generated by Django 4.2.2 on 2023-06-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0072_saquecomplementar_valor_saque'),
    ]

    operations = [
        migrations.AddField(
            model_name='portabilidade',
            name='taxa_contrato_recalculada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Taxa Contrato Recalculada'),
        ),
    ]
