# Generated by Django 4.2.2 on 2023-06-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0072_saquecomplementar_valor_saque'),
    ]

    operations = [
        migrations.AddField(
            model_name='saquecomplementar',
            name='numero_proposta_banksoft',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero da Proposta (Banksoft)'),
        ),
    ]
