# Generated by Django 4.2.2 on 2023-06-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0073_portabilidade_taxa_contrato_recalculada'),
        ('contract', '0073_saquecomplementar_numero_proposta_banksoft'),
    ]

    operations = [
    ]
