# Generated by Django 4.2.2 on 2023-06-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0015_convenios_url'),
        ('contract', '0074_merge_20230615_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaobeneficio',
            name='convenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartao_convenio', to='cartao_beneficio.convenios', verbose_name='Convenio'),
        ),
    ]
