# Generated by Django 4.2.2 on 2023-06-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0075_cartaobeneficio_convenio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saquecomplementar',
            name='limite_disponivel_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Limite de saque total'),
        ),
    ]
