# Generated by Django 4.2.2 on 2023-06-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0076_alter_saquecomplementar_limite_disponivel_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaobeneficio',
            name='numero_proposta_banksoft',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero da Proposta (Banksoft)'),
        ),
        migrations.AlterField(
            model_name='saquecomplementar',
            name='numero_proposta_banksoft',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero da Proposta (Banksoft)'),
        ),
    ]
