# Generated by Django 4.2.2 on 2023-07-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0078_alter_cartaobeneficio_status_alter_inss_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='regras_validadas',
            field=models.BooleanField(default=False, verbose_name='Regras validadas?'),
        ),
    ]
