# Generated by Django 4.2.2 on 2023-07-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0079_contrato_regras_validadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='portabilidade',
            name='ccb_gerada',
            field=models.BooleanField(default=False, help_text='Indica se a CCB foi gerada', verbose_name='CCB Gerada pela QITECH?'),
        ),
    ]
