# Generated by Django 4.2.2 on 2023-07-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0080_portabilidade_ccb_gerada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaobeneficio',
            name='qtd_parcela_saque_parcelado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Parcelas Contratadas'),
        ),
        migrations.AddField(
            model_name='cartaobeneficio',
            name='saque_parcelado',
            field=models.BooleanField(default=False, verbose_name='Saque Parcelado?'),
        ),
        migrations.AddField(
            model_name='saquecomplementar',
            name='qtd_parcela_saque_parcelado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Parcelas Contratadas'),
        ),
        migrations.AddField(
            model_name='saquecomplementar',
            name='saque_parcelado',
            field=models.BooleanField(default=False, verbose_name='Saque Parcelado?'),
        ),
    ]
