# Generated by Django 4.2.2 on 2023-07-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0083_alter_cartaobeneficio_possui_saque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaobeneficio',
            name='valor_total_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total a Pagar'),
        ),
    ]
