# Generated by Django 4.2.2 on 2023-07-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0085_saquecomplementar_valor_total_a_pagar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saquecomplementar',
            name='apto_saque',
        ),
        migrations.RemoveField(
            model_name='saquecomplementar',
            name='limite_disponivel_total',
        ),
        migrations.RemoveField(
            model_name='saquecomplementar',
            name='saque_minimo',
        ),
        migrations.AddField(
            model_name='envelopecontratos',
            name='duracao_digitacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duração da digitação'),
        ),
        migrations.AddField(
            model_name='envelopecontratos',
            name='fim_digitacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fim da digitação'),
        ),
        migrations.AddField(
            model_name='envelopecontratos',
            name='inicio_digitacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Início da digitação'),
        ),
        migrations.AddField(
            model_name='saquecomplementar',
            name='possui_saque',
            field=models.BooleanField(default=False, verbose_name='Possui saque rotativo?'),
        ),
        migrations.AlterField(
            model_name='cartaobeneficio',
            name='possui_saque',
            field=models.BooleanField(default=False, verbose_name='Possui Saque Rotativo?'),
        ),
        migrations.AlterField(
            model_name='saquecomplementar',
            name='numero_proposta_banksoft',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero da proposta (Banksoft)'),
        ),
        migrations.AlterField(
            model_name='saquecomplementar',
            name='qtd_parcela_saque_parcelado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de parcelas'),
        ),
        migrations.AlterField(
            model_name='saquecomplementar',
            name='saque_parcelado',
            field=models.BooleanField(default=False, verbose_name='Possui saque parcelado?'),
        ),
        migrations.AlterField(
            model_name='saquecomplementar',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente')], default=1, null=True, verbose_name='Status do contrato'),
        ),
        migrations.AlterField(
            model_name='saquecomplementar',
            name='valor_lancado_fatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor total financiado'),
        ),
        migrations.AlterField(
            model_name='saquecomplementar',
            name='valor_total_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor total a Pagar'),
        ),
    ]
