# Generated by Django 4.2.2 on 2023-07-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0086_remove_saquecomplementar_apto_saque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='latitude',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='longitude',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Longitude'),
        ),
    ]
