# Generated by Django 4.2.2 on 2023-07-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0089_alter_cartaobeneficio_status_alter_inss_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaobeneficio',
            name='folha',
        ),
        migrations.AddField(
            model_name='cartaobeneficio',
            name='folha_especie',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Folha/Espécie de Benefício'),
        ),
    ]
