# Generated by Django 4.2.2 on 2023-07-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0090_remove_cartaobeneficio_folha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaobeneficio',
            name='folha_especie',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Folha/Espécie de Benefício'),
        ),
    ]
