# Generated by Django 4.2.2 on 2023-07-27 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0091_alter_cartaobeneficio_folha_especie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartaobeneficio',
            old_name='folha_especie',
            new_name='folha',
        ),
    ]
