# Generated by Django 4.2.2 on 2023-07-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0092_rename_folha_especie_cartaobeneficio_folha'),
    ]

    operations = [
        migrations.AddField(
            model_name='portabilidade',
            name='insercao_sem_sucesso',
            field=models.CharField(blank=True, help_text='Caso a insercao não foi bem sucedida aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo de erro na insercao QITECH'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='motivo_aceite_proposta',
            field=models.CharField(blank=True, help_text='Caso o ACEITE da proposta nao foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo ACEITE PROPOSTA(QITECH)'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='motivo_documentos_linkados',
            field=models.CharField(blank=True, help_text='Caso a conexão dos documentos com a proposta não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo CONEXÃO DOCUMENTOS(QITECH)'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='motivo_envio_assinatura',
            field=models.CharField(blank=True, help_text='Caso o envio de assinatura não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo Assinatura QITECH'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='motivo_envio_documento_frente_cnh',
            field=models.CharField(blank=True, help_text='Caso o envio de documento (FRENTE/CNH) não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo FRENTE/CNH(QITECH)'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='motivo_envio_documento_selfie',
            field=models.CharField(blank=True, help_text='Caso o envio de documento (SELFIE) não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo SELFIE(QITECH)'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='motivo_envio_documento_verso',
            field=models.CharField(blank=True, help_text='Caso o envio de documento (VERSO) não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo VERSO(QITECH)'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='motivo_recusa_proposta',
            field=models.CharField(blank=True, help_text='Caso a RECUSA da proposta nao foi bem sucedida aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo RECUSA PROPOSTA(QITECH)'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='motivo_submissao_proposta',
            field=models.CharField(blank=True, help_text='Caso a submissão da proposta nao foi bem sucedida aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo SUBMISSÃO PROPOSTA(QITECH)'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='sucesso_aceite_proposta',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se o aceite da proposta foi realizada com sucesso', null=True, verbose_name='Sucesso ACEITE PROPOSTA(QITECH)'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='sucesso_documentos_linkados',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se a conexão dos documentos com a proposta foi realizada com sucesso', null=True, verbose_name='Sucesso CONEXÃO DOCUMENTOS(QITECH)'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='sucesso_envio_assinatura',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se o envio da assinatura foi realizado com sucesso', null=True, verbose_name='Sucesso Assinatura(QITECH)'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='sucesso_envio_documento_frente_cnh',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se o envio do documento(FRENTE/CNH) foi realizado com sucesso', null=True, verbose_name='Sucesso FRENTE/CNH(QITECH)'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='sucesso_envio_documento_selfie',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se o envio do documento (SELFIE) foi realizado com sucesso', null=True, verbose_name='Sucesso SELFIE(QITECH)'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='sucesso_envio_documento_verso',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se o envio do documento(VERSO) foi realizado com sucesso', null=True, verbose_name='Sucesso VERSO(QITECH)'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='sucesso_insercao_proposta',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se a proposta foi inserida com sucesso', null=True, verbose_name='Sucesso na inserção proposta(QITECH)'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='sucesso_recusa_proposta',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se a recusa da proposta foi realizada com sucesso', null=True, verbose_name='Sucesso RECUSA PROPOSTA(QITECH)'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='sucesso_submissao_proposta',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se a submissão da proposta foi realizada com sucesso', null=True, verbose_name='Sucesso SUBMISSÃO PROPOSTA(QITECH)'),
        ),
    ]
