# Generated by Django 4.2.2 on 2023-08-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0093_portabilidade_insercao_sem_sucesso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaobeneficio',
            name='DV_conta_corrente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DVContaCorrente'),
        ),
        migrations.AddField(
            model_name='cartaobeneficio',
            name='UFAPS',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ufPagamento'),
        ),
        migrations.AddField(
            model_name='cartaobeneficio',
            name='agencia_pagadora',
            field=models.IntegerField(blank=True, null=True, verbose_name='agenciaPagadora'),
        ),
        migrations.AddField(
            model_name='cartaobeneficio',
            name='cbc_if_pagadora',
            field=models.IntegerField(blank=True, null=True, verbose_name='cbcIfPagadora'),
        ),
        migrations.AddField(
            model_name='cartaobeneficio',
            name='conta_corrente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='contaCorrente'),
        ),
    ]
