# Generated by Django 4.2.2 on 2023-08-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0094_cartaobeneficio_dv_conta_corrente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaobeneficio',
            name='DV_conta_corrente',
        ),
        migrations.RemoveField(
            model_name='cartaobeneficio',
            name='UFAPS',
        ),
        migrations.RemoveField(
            model_name='cartaobeneficio',
            name='agencia_pagadora',
        ),
        migrations.RemoveField(
            model_name='cartaobeneficio',
            name='cbc_if_pagadora',
        ),
        migrations.RemoveField(
            model_name='cartaobeneficio',
            name='conta_corrente',
        ),
        migrations.AlterField(
            model_name='cartaobeneficio',
            name='reserva',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número da Reserva'),
        ),
    ]
