# Generated by Django 4.2.2 on 2023-08-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0095_remove_cartaobeneficio_dv_conta_corrente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaobeneficio',
            name='valor_financiado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total Financiado'),
        ),
    ]
