# Generated by Django 4.2.2 on 2023-08-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0095_remove_cartaobeneficio_dv_conta_corrente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='hash_assinatura',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hash assinatura'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='ip_publico_assinatura',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IP assinatura'),
        ),
    ]
