# Generated by Django 4.2.2 on 2023-08-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0096_alter_cartaobeneficio_valor_financiado'),
        ('contract', '0096_contrato_hash_assinatura_and_more'),
    ]

    operations = [
    ]
