# Generated by Django 4.2.2 on 2023-08-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0100_alter_cartaobeneficio_status_alter_inss_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='vr_iof',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='Taxa IOF (%)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='vr_iof_adicional',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='Taxa do IOF Adiciona (%)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='vr_iof_total',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Valor total de IOF (R$)'),
        ),
    ]
