# Generated by Django 4.2.2 on 2023-08-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0102_anexoantifraude'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='dt_pagamento_contrato',
            field=models.DateField(blank=True, help_text='Data de pagamento do contrato', null=True, verbose_name='Data Pagamento'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='banco_atacado',
            field=models.CharField(blank=True, help_text='Banco que estamos portando o Contrato', max_length=300, null=True, verbose_name='Banco Atacado'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='dt_envio_proposta_CIP',
            field=models.DateField(blank=True, help_text='Data de envio do aceite da proposta para a CIP', null=True, verbose_name='Data de envio da proposta(CIP)'),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='dt_recebimento_saldo_devedor',
            field=models.DateField(blank=True, help_text='Data de recebimento do saldo devedor(CIP)', null=True, verbose_name='Data de recebimento do saldo devedor(CIP)'),
        ),
    ]
