# Generated by Django 4.2.2 on 2023-08-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0103_contrato_dt_pagamento_contrato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inss',
            name='cedido_fundo',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='chave_webhook_financeira',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='contrato_cedido_fdic',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='custo_operacao',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='data_cedido_fundo',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='documentos_validados',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='dt_retorno_averbacao',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='dt_vencimento_primeira_parcela',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='dt_vencimento_ultima_parcela',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='nu_cessao_retorno_registrador',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='nu_cnpj_correspondente',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='nu_contrato_ccb',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='nu_contrato_facta',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='nu_cpf_agente_validador',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='nu_protocolo_averbacao',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='possui_alerta',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='qt_parcelas_aberto',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='qt_parcelas_averbadas',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='qt_parcelas_pagas',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='qt_parcelas_total',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='qt_parcelas_vencer',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='recusado',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='retorno_access',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='taxa_cessao',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='valor_cessao',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='vr_aberto',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='vr_contrato',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='vr_parcela',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='vr_parcela_maxima',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='vr_parcela_minima',
        ),
        migrations.RemoveField(
            model_name='inss',
            name='vr_vencer',
        ),
        migrations.AddField(
            model_name='cartaobeneficio',
            name='contrato_digitacao_manual',
            field=models.BooleanField(default=False, verbose_name='Digitação manual?'),
        ),
        migrations.AddField(
            model_name='inss',
            name='ccb_gerada',
            field=models.BooleanField(default=False, help_text='Indica se a CCB foi gerada', verbose_name='CCB Gerada pela QITECH?'),
        ),
        migrations.AddField(
            model_name='inss',
            name='insercao_sem_sucesso',
            field=models.CharField(blank=True, help_text='Caso a insercao não foi bem sucedida aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo de erro na insercao QITECH'),
        ),
        migrations.AddField(
            model_name='inss',
            name='motivo_aceite_proposta',
            field=models.CharField(blank=True, help_text='Caso o ACEITE da proposta nao foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo ACEITE PROPOSTA(QITECH)'),
        ),
        migrations.AddField(
            model_name='inss',
            name='motivo_documentos_linkados',
            field=models.CharField(blank=True, help_text='Caso a conexão dos documentos com a proposta não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo CONEXÃO DOCUMENTOS(QITECH)'),
        ),
        migrations.AddField(
            model_name='inss',
            name='motivo_envio_assinatura',
            field=models.CharField(blank=True, help_text='Caso o envio de assinatura não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo Assinatura QITECH'),
        ),
        migrations.AddField(
            model_name='inss',
            name='motivo_envio_documento_frente_cnh',
            field=models.CharField(blank=True, help_text='Caso o envio de documento (FRENTE/CNH) não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo FRENTE/CNH(QITECH)'),
        ),
        migrations.AddField(
            model_name='inss',
            name='motivo_envio_documento_selfie',
            field=models.CharField(blank=True, help_text='Caso o envio de documento (SELFIE) não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo SELFIE(QITECH)'),
        ),
        migrations.AddField(
            model_name='inss',
            name='motivo_envio_documento_verso',
            field=models.CharField(blank=True, help_text='Caso o envio de documento (VERSO) não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo VERSO(QITECH)'),
        ),
        migrations.AddField(
            model_name='inss',
            name='motivo_recusa_proposta',
            field=models.CharField(blank=True, help_text='Caso a RECUSA da proposta nao foi bem sucedida aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo RECUSA PROPOSTA(QITECH)'),
        ),
        migrations.AddField(
            model_name='inss',
            name='motivo_submissao_proposta',
            field=models.CharField(blank=True, help_text='Caso a submissão da proposta nao foi bem sucedida aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo SUBMISSÃO PROPOSTA(QITECH)'),
        ),
        migrations.AddField(
            model_name='inss',
            name='sucesso_aceite_proposta',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se o aceite da proposta foi realizada com sucesso', null=True, verbose_name='Sucesso ACEITE PROPOSTA(QITECH)'),
        ),
        migrations.AddField(
            model_name='inss',
            name='sucesso_documentos_linkados',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se a conexão dos documentos com a proposta foi realizada com sucesso', null=True, verbose_name='Sucesso CONEXÃO DOCUMENTOS(QITECH)'),
        ),
        migrations.AddField(
            model_name='inss',
            name='sucesso_envio_assinatura',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se o envio da assinatura foi realizado com sucesso', null=True, verbose_name='Sucesso Assinatura(QITECH)'),
        ),
        migrations.AddField(
            model_name='inss',
            name='sucesso_envio_documento_frente_cnh',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se o envio do documento(FRENTE/CNH) foi realizado com sucesso', null=True, verbose_name='Sucesso FRENTE/CNH(QITECH)'),
        ),
        migrations.AddField(
            model_name='inss',
            name='sucesso_envio_documento_selfie',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se o envio do documento (SELFIE) foi realizado com sucesso', null=True, verbose_name='Sucesso SELFIE(QITECH)'),
        ),
        migrations.AddField(
            model_name='inss',
            name='sucesso_envio_documento_verso',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se o envio do documento(VERSO) foi realizado com sucesso', null=True, verbose_name='Sucesso VERSO(QITECH)'),
        ),
        migrations.AddField(
            model_name='inss',
            name='sucesso_insercao_proposta',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se a proposta foi inserida com sucesso', null=True, verbose_name='Sucesso na inserção proposta(QITECH)'),
        ),
        migrations.AddField(
            model_name='inss',
            name='sucesso_recusa_proposta',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se a recusa da proposta foi realizada com sucesso', null=True, verbose_name='Sucesso RECUSA PROPOSTA(QITECH)'),
        ),
        migrations.AddField(
            model_name='inss',
            name='sucesso_submissao_proposta',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se a submissão da proposta foi realizada com sucesso', null=True, verbose_name='Sucesso SUBMISSÃO PROPOSTA(QITECH)'),
        ),
        migrations.AddField(
            model_name='inss',
            name='taxa_contrato_recalculada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Taxa Contrato Recalculada'),
        ),
        migrations.AddField(
            model_name='inss',
            name='valor_parcela_recalculada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor da Parcela Recalculada'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_produto',
            field=models.SmallIntegerField(choices=[(1, 'FGTS'), (2, 'INSS - Representante Legal'), (3, 'Cartão Benefício - Representante Legal'), (4, 'PAB'), (5, 'INSS CORBAN'), (6, 'INSS'), (7, 'Cartão Benefício'), (8, 'Siape'), (9, 'Exercito'), (10, 'Marinha'), (11, 'Aeronautica'), (12, 'Portabilidade'), (13, 'Consignado'), (14, 'Saque Complementar'), (15, 'Cartão Consignado')], default=1, verbose_name='Tipo de Produto'),
        ),
    ]
