# Generated by Django 4.2.2 on 2023-08-31 19:36

from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def add_permission_to_group(apps, schema_editor):
    try:
        ContratoModel = apps.get_model('contract', 'Contrato')
        content_type = ContentType.objects.get_for_model(ContratoModel)

        permission = Permission.objects.create(
            codename='happy_generate_contracts_report',
            name='[Happy] Gerar relatório de contratos',
            content_type=content_type,
        )

        group = Group.objects.get(name='Correspondente')
        group.permissions.add(permission)

    except Group.DoesNotExist:
        print("Grupo 'Correspondente' não encontrado.")


class Migration(migrations.Migration):
    dependencies = [
        ('contract', '0104_remove_inss_cedido_fundo_and_more'),
    ]

    operations = [
        migrations.RunPython(add_permission_to_group),
    ]
