# Generated by Django 4.2.3 on 2023-09-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0105_create_happy_generate_contracts_report_permission_'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaobeneficio',
            name='contrato_digitacao_manual',
        ),
        migrations.AddField(
            model_name='contrato',
            name='adicional_enviado',
            field=models.BooleanField(default=False, verbose_name='Documento adicional enviado?'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='adicional_pendente',
            field=models.BooleanField(default=False, verbose_name='Documento adicional pendente?'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contracheque_enviado',
            field=models.BooleanField(default=False, verbose_name='Contracheque enviado?'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contracheque_pendente',
            field=models.BooleanField(default=False, verbose_name='Contracheque pendente?'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_digitacao_manual',
            field=models.BooleanField(default=False, verbose_name='Digitação manual?'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_digitacao_manual_validado',
            field=models.BooleanField(default=False, verbose_name='Digitação manual validado?'),
        ),
        migrations.AddField(
            model_name='inss',
            name='codigo_dataprev',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Código Dataprev'),
        ),
        migrations.AddField(
            model_name='inss',
            name='descricao_dataprev',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição Dataprev'),
        ),
        migrations.AddField(
            model_name='inss',
            name='dt_retorno_dataprev',
            field=models.DateField(blank=True, null=True, verbose_name='Data de retorno do Dataprev'),
        ),
        migrations.AlterField(
            model_name='anexocontrato',
            name='tipo_anexo',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'CCB'), (2, 'Documento do cliente frente'), (3, 'Documento do cliente verso'), (12, 'Documentos Adicionais'), (4, 'Selfie'), (5, 'Foto da Prova de Vida'), (6, 'Comprovante de endereço'), (7, 'Comprovante financeiro'), (11, 'Repasse'), (22, 'Arquivo retorno reserva'), (8, 'Documento - CNH'), (13, 'Documento Frente - CNH'), (14, 'Documento Verso - CNH'), (15, 'Termos e assinaturas'), (16, 'Contracheque')], null=True, verbose_name='Tipo do anexo'),
        ),
        migrations.AlterField(
            model_name='cartaobeneficio',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente'), (41, 'Reprovado'), (42, 'Aguardando Retorno da IN100'), (43, 'Aguardando Consulta IN100 (RECALCULO)'), (44, 'IN100 Consultada no Recalculo'), (45, 'Revisão - Mesa de Formalização'), (46, 'Reprovada Revisão - Mesa de Formalização')], default=1, null=True, verbose_name='Status do Contrato'),
        ),
        migrations.AlterField(
            model_name='inss',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente'), (41, 'Reprovado'), (42, 'Aguardando Retorno da IN100'), (43, 'Aguardando Consulta IN100 (RECALCULO)'), (44, 'IN100 Consultada no Recalculo'), (45, 'Revisão - Mesa de Formalização'), (46, 'Reprovada Revisão - Mesa de Formalização')], default=1, null=True, verbose_name='Status do Contrato'),
        ),
        migrations.AlterField(
            model_name='portabilidade',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente'), (41, 'Reprovado'), (42, 'Aguardando Retorno da IN100'), (43, 'Aguardando Consulta IN100 (RECALCULO)'), (44, 'IN100 Consultada no Recalculo'), (45, 'Revisão - Mesa de Formalização'), (46, 'Reprovada Revisão - Mesa de Formalização')], default=1, null=True, verbose_name='Status do Contrato'),
        ),
        migrations.AlterField(
            model_name='saquecomplementar',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente'), (41, 'Reprovado'), (42, 'Aguardando Retorno da IN100'), (43, 'Aguardando Consulta IN100 (RECALCULO)'), (44, 'IN100 Consultada no Recalculo'), (45, 'Revisão - Mesa de Formalização'), (46, 'Reprovada Revisão - Mesa de Formalização')], default=1, null=True, verbose_name='Status do contrato'),
        ),
        migrations.AlterField(
            model_name='statuscontrato',
            name='nome',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente'), (41, 'Reprovado'), (42, 'Aguardando Retorno da IN100'), (43, 'Aguardando Consulta IN100 (RECALCULO)'), (44, 'IN100 Consultada no Recalculo'), (45, 'Revisão - Mesa de Formalização'), (46, 'Reprovada Revisão - Mesa de Formalização')], default=1, null=True, verbose_name='Nome do status'),
        ),
        migrations.CreateModel(
            name='ReservaDeMargem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='contrato', verbose_name='Anexo')),
                ('nome_anexo', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nome do anexo')),
                ('anexo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do documento')),
                ('protocolo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Protocolo da Averbadora')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Reserva de Margem',
                'verbose_name_plural': 'Reserva de Margens',
            },
        ),
    ]
