# Generated by Django 4.2.3 on 2023-09-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contract', '0107_alter_cartaobeneficio_status_alter_inss_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaobeneficio',
            name='senha_servidor',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='Senha Servidor'
            ),
        ),
    ]
