# Generated by Django 4.2.3 on 2023-09-14 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0108_cartaobeneficio_senha_servidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MargemLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente'), (41, 'Reprovado'), (42, 'Aguardando Retorno da IN100'), (43, 'Aguardando Consulta IN100 (RECALCULO)'), (44, 'IN100 Consultada no Recalculo'), (45, 'Revisão - Mesa de Formalização'), (46, 'Reprovada Revisão - Mesa de Formalização'), (47, 'Averbação - Mesa de Formalização')], default=1, null=True, verbose_name='Status do Contrato')),
                ('vr_contrato', models.DecimalField(blank=True, decimal_places=2, help_text='Indica o valor do contrato', max_digits=20, null=True, verbose_name='Valor Contrato')),
                ('qtd_parcelas', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Parcelas')),
                ('vr_parcelas', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor das Parcelas')),
                ('vr_liberado_cliente', models.DecimalField(blank=True, decimal_places=2, help_text='Indica o valor liberado para o cliente', max_digits=20, null=True, verbose_name='Valor a Pagar')),
                ('taxa_contrato_recalculada', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Taxa Contrato Recalculada')),
                ('valor_parcela_recalculada', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor da Parcela Recalculada')),
                ('ccb_gerada', models.BooleanField(default=False, help_text='Indica se a CCB foi gerada', verbose_name='CCB Gerada pela QITECH?')),
                ('sucesso_insercao_proposta', models.BooleanField(blank=True, default=None, help_text='Indica se a proposta foi inserida com sucesso', null=True, verbose_name='Sucesso na inserção proposta(QITECH)')),
                ('insercao_sem_sucesso', models.CharField(blank=True, help_text='Caso a insercao não foi bem sucedida aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo de erro na insercao QITECH')),
                ('sucesso_envio_assinatura', models.BooleanField(blank=True, default=None, help_text='Indica se o envio da assinatura foi realizado com sucesso', null=True, verbose_name='Sucesso Assinatura(QITECH)')),
                ('motivo_envio_assinatura', models.CharField(blank=True, help_text='Caso o envio de assinatura não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo Assinatura QITECH')),
                ('sucesso_envio_documento_frente_cnh', models.BooleanField(blank=True, default=None, help_text='Indica se o envio do documento(FRENTE/CNH) foi realizado com sucesso', null=True, verbose_name='Sucesso FRENTE/CNH(QITECH)')),
                ('motivo_envio_documento_frente_cnh', models.CharField(blank=True, help_text='Caso o envio de documento (FRENTE/CNH) não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo FRENTE/CNH(QITECH)')),
                ('sucesso_envio_documento_verso', models.BooleanField(blank=True, default=None, help_text='Indica se o envio do documento(VERSO) foi realizado com sucesso', null=True, verbose_name='Sucesso VERSO(QITECH)')),
                ('motivo_envio_documento_verso', models.CharField(blank=True, help_text='Caso o envio de documento (VERSO) não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo VERSO(QITECH)')),
                ('sucesso_envio_documento_selfie', models.BooleanField(blank=True, default=None, help_text='Indica se o envio do documento (SELFIE) foi realizado com sucesso', null=True, verbose_name='Sucesso SELFIE(QITECH)')),
                ('motivo_envio_documento_selfie', models.CharField(blank=True, help_text='Caso o envio de documento (SELFIE) não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo SELFIE(QITECH)')),
                ('sucesso_documentos_linkados', models.BooleanField(blank=True, default=None, help_text='Indica se a conexão dos documentos com a proposta foi realizada com sucesso', null=True, verbose_name='Sucesso CONEXÃO DOCUMENTOS(QITECH)')),
                ('motivo_documentos_linkados', models.CharField(blank=True, help_text='Caso a conexão dos documentos com a proposta não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo CONEXÃO DOCUMENTOS(QITECH)')),
                ('sucesso_submissao_proposta', models.BooleanField(blank=True, default=None, help_text='Indica se a submissão da proposta foi realizada com sucesso', null=True, verbose_name='Sucesso SUBMISSÃO PROPOSTA(QITECH)')),
                ('motivo_submissao_proposta', models.CharField(blank=True, help_text='Caso a submissão da proposta nao foi bem sucedida aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo SUBMISSÃO PROPOSTA(QITECH)')),
                ('sucesso_aceite_proposta', models.BooleanField(blank=True, default=None, help_text='Indica se o aceite da proposta foi realizada com sucesso', null=True, verbose_name='Sucesso ACEITE PROPOSTA(QITECH)')),
                ('motivo_aceite_proposta', models.CharField(blank=True, help_text='Caso o ACEITE da proposta nao foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo ACEITE PROPOSTA(QITECH)')),
                ('sucesso_recusa_proposta', models.BooleanField(blank=True, default=None, help_text='Indica se a recusa da proposta foi realizada com sucesso', null=True, verbose_name='Sucesso RECUSA PROPOSTA(QITECH)')),
                ('motivo_recusa_proposta', models.CharField(blank=True, help_text='Caso a RECUSA da proposta nao foi bem sucedida aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo RECUSA PROPOSTA(QITECH)')),
                ('cd_retorno_averbacao', models.BooleanField(blank=True, null=True, verbose_name='Retorno averbação ')),
                ('codigo_dataprev', models.CharField(blank=True, max_length=150, null=True, verbose_name='Código Dataprev')),
                ('descricao_dataprev', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição Dataprev')),
                ('dt_retorno_dataprev', models.DateField(blank=True, null=True, verbose_name='Data de retorno do Dataprev')),
            ],
            options={
                'verbose_name': 'Margem Livre',
                'verbose_name_plural': 'Margem Livre',
            },
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_produto',
            field=models.SmallIntegerField(choices=[(1, 'FGTS'), (2, 'INSS - Representante Legal'), (3, 'Cartão Benefício - Representante Legal'), (4, 'PAB'), (5, 'INSS CORBAN'), (6, 'INSS'), (7, 'Cartão Benefício'), (8, 'Siape'), (9, 'Exercito'), (10, 'Marinha'), (11, 'Aeronautica'), (12, 'Portabilidade'), (13, 'Consignado'), (14, 'Saque Complementar'), (15, 'Cartão Consignado'), (16, 'Margem Livre')], default=1, verbose_name='Tipo de Produto'),
        ),
        migrations.DeleteModel(
            name='Inss',
        ),
        migrations.AddField(
            model_name='margemlivre',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_margem_livre', to='contract.contrato', verbose_name='Contrato'),
        ),
    ]
