# Generated by Django 4.2.3 on 2023-09-21 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contract', '0110_margemlivre_collateral_key_and_more'),
        ('contract', '0110_portabilidade_dt_recusa_retido'),
    ]

    operations = []
