# Generated by Django 4.2.3 on 2023-10-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0113_contrato_plano_margemlivre_chave_proposta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='margemlivre',
            name='CPF_dados_divergentes',
            field=models.BooleanField(default=False, help_text='Indica se o CPF está Irregular na Receita Federal', verbose_name='CPF irregular na receita?'),
        ),
    ]
