# Generated by Django 4.2.3 on 2023-10-13 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0067_cliente_id_confia'),
        ('contract', '0115_contrato_campos_pendentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='margemlivre',
            name='dt_averbacao',
            field=models.DateField(
                blank=True,
                help_text='Data de Averbação da Operação',
                null=True,
                verbose_name='Data de Averbação',
            ),
        ),
        migrations.AddField(
            model_name='margemlivre',
            name='dt_desembolso',
            field=models.DateField(
                blank=True,
                help_text='Data de Desembolso da Operação',
                null=True,
                verbose_name='Data de Desembolso',
            ),
        ),
        migrations.CreateModel(
            name='PaymentRefusedIncomingData',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'transaction_key',
                    models.CharField(
                        blank=True,
                        help_text='Chave recebida da qi tech quando pagamento TED foi recusado.',
                        max_length=100,
                        null=True,
                        verbose_name='Chave da transação',
                    ),
                ),
                (
                    'is_pix',
                    models.BooleanField(
                        default=False,
                        help_text='Os dados são referentes à um erro no pix?',
                        max_length=100,
                        verbose_name='É pix?',
                    ),
                ),
                (
                    'is_ted',
                    models.BooleanField(
                        default=False,
                        help_text='Os dados são referentes à um erro no ted?',
                        max_length=100,
                        verbose_name='É ted?',
                    ),
                ),
                (
                    'reason_id',
                    models.CharField(
                        help_text='Chave recebida da qi tech quando pagamento foi recusado.',
                        max_length=100,
                        verbose_name='Id da razão do cancelamento do pagamento',
                    ),
                ),
                (
                    'reason_description',
                    models.CharField(
                        help_text='Chave recebida da qi tech quando pagamento foi recusado.',
                        max_length=300,
                        verbose_name='Id da razão do cancelamento do pagamento',
                    ),
                ),
                (
                    'bank_data',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='core.dadosbancarios',
                        verbose_name='bank_data',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='margemlivre',
            name='payment_refused_incoming_data',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='margem_livre_dados_pagamento_recusado',
                to='contract.paymentrefusedincomingdata',
                verbose_name='Dados do cancelamento do pagamento',
            ),
        ),
    ]
