# Generated by Django 4.2.3 on 2023-11-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0118_contractdisbursementaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaobeneficio',
            name='tipo_cartao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Cartão'),
        ),
    ]
