# Generated by Django 4.2.3 on 2023-11-03 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0119_cartaobeneficio_tipo_cartao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envelopecontratos',
            name='id_processo_confia',
        ),
        migrations.AddField(
            model_name='cartaobeneficio',
            name='tipo_margem',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Margem Compra'), (2, 'Margem Saque'), (3, 'Margem Unificada')], null=True, verbose_name='Tipo Margem Contratada'),
        ),
        migrations.AddField(
            model_name='envelopecontratos',
            name='mensagem_confia',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem de retorno da confia'),
        ),
        migrations.AddField(
            model_name='envelopecontratos',
            name='status_unico',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Status Unico'),
        ),
        migrations.AlterField(
            model_name='cartaobeneficio',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente'), (41, 'Reprovado'), (42, 'Aguardando Retorno da IN100'), (43, 'Aguardando Consulta IN100 (RECALCULO)'), (44, 'IN100 Consultada no Recalculo'), (45, 'Revisão - Mesa de Formalização'), (46, 'Reprovada Revisão - Mesa de Formalização'), (47, 'Averbação - Mesa de Formalização'), (48, 'Saque Cancelado - Limite disponível Insuficiente'), (49, 'Saque Recusado - Problema no Pagamento'), (50, 'Andamento - Reapresentação do pagamento de saque'), (51, 'Pendenciado'), (52, 'Proposta enviada para QiTech, aguardando retorno.'), (52, 'Em Andamento – Consulta Dataprev'), (53, 'Erro – Consulta Dataprev'), (54, 'Reprovado – Consulta Dataprev')], default=1, null=True, verbose_name='Status do Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='campos_pendentes',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Campos pendentes?'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_produto',
            field=models.SmallIntegerField(choices=[(1, 'FGTS'), (2, 'INSS - Representante Legal'), (3, 'Cartão Benefício - Representante Legal'), (4, 'PAB'), (5, 'INSS CORBAN'), (6, 'INSS'), (7, 'Cartão Benefício'), (8, 'Siape'), (9, 'Exercito'), (10, 'Marinha'), (11, 'Aeronautica'), (12, 'Portabilidade'), (13, 'Consignado'), (14, 'Saque Complementar'), (15, 'Cartão Consignado'), (16, 'Margem Livre'), (17, 'Portabilidade + Refinanciamento')], default=1, verbose_name='Tipo de Produto'),
        ),
        migrations.AlterField(
            model_name='margemlivre',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente'), (41, 'Reprovado'), (42, 'Aguardando Retorno da IN100'), (43, 'Aguardando Consulta IN100 (RECALCULO)'), (44, 'IN100 Consultada no Recalculo'), (45, 'Revisão - Mesa de Formalização'), (46, 'Reprovada Revisão - Mesa de Formalização'), (47, 'Averbação - Mesa de Formalização'), (48, 'Saque Cancelado - Limite disponível Insuficiente'), (49, 'Saque Recusado - Problema no Pagamento'), (50, 'Andamento - Reapresentação do pagamento de saque'), (51, 'Pendenciado'), (52, 'Proposta enviada para QiTech, aguardando retorno.'), (52, 'Em Andamento – Consulta Dataprev'), (53, 'Erro – Consulta Dataprev'), (54, 'Reprovado – Consulta Dataprev')], default=1, null=True, verbose_name='Status do Contrato'),
        ),
        migrations.AlterField(
            model_name='portabilidade',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente'), (41, 'Reprovado'), (42, 'Aguardando Retorno da IN100'), (43, 'Aguardando Consulta IN100 (RECALCULO)'), (44, 'IN100 Consultada no Recalculo'), (45, 'Revisão - Mesa de Formalização'), (46, 'Reprovada Revisão - Mesa de Formalização'), (47, 'Averbação - Mesa de Formalização'), (48, 'Saque Cancelado - Limite disponível Insuficiente'), (49, 'Saque Recusado - Problema no Pagamento'), (50, 'Andamento - Reapresentação do pagamento de saque'), (51, 'Pendenciado'), (52, 'Proposta enviada para QiTech, aguardando retorno.'), (52, 'Em Andamento – Consulta Dataprev'), (53, 'Erro – Consulta Dataprev'), (54, 'Reprovado – Consulta Dataprev')], default=1, null=True, verbose_name='Status do Contrato'),
        ),
        migrations.AlterField(
            model_name='saquecomplementar',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente'), (41, 'Reprovado'), (42, 'Aguardando Retorno da IN100'), (43, 'Aguardando Consulta IN100 (RECALCULO)'), (44, 'IN100 Consultada no Recalculo'), (45, 'Revisão - Mesa de Formalização'), (46, 'Reprovada Revisão - Mesa de Formalização'), (47, 'Averbação - Mesa de Formalização'), (48, 'Saque Cancelado - Limite disponível Insuficiente'), (49, 'Saque Recusado - Problema no Pagamento'), (50, 'Andamento - Reapresentação do pagamento de saque'), (51, 'Pendenciado'), (52, 'Proposta enviada para QiTech, aguardando retorno.'), (52, 'Em Andamento – Consulta Dataprev'), (53, 'Erro – Consulta Dataprev'), (54, 'Reprovado – Consulta Dataprev')], default=1, null=True, verbose_name='Status do contrato'),
        ),
        migrations.AlterField(
            model_name='statuscontrato',
            name='nome',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente'), (41, 'Reprovado'), (42, 'Aguardando Retorno da IN100'), (43, 'Aguardando Consulta IN100 (RECALCULO)'), (44, 'IN100 Consultada no Recalculo'), (45, 'Revisão - Mesa de Formalização'), (46, 'Reprovada Revisão - Mesa de Formalização'), (47, 'Averbação - Mesa de Formalização'), (48, 'Saque Cancelado - Limite disponível Insuficiente'), (49, 'Saque Recusado - Problema no Pagamento'), (50, 'Andamento - Reapresentação do pagamento de saque'), (51, 'Pendenciado'), (52, 'Proposta enviada para QiTech, aguardando retorno.'), (52, 'Em Andamento – Consulta Dataprev'), (53, 'Erro – Consulta Dataprev'), (54, 'Reprovado – Consulta Dataprev')], default=1, null=True, verbose_name='Nome do status'),
        ),
        migrations.CreateModel(
            name='Refinanciamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente'), (41, 'Reprovado'), (42, 'Aguardando Retorno da IN100'), (43, 'Aguardando Consulta IN100 (RECALCULO)'), (44, 'IN100 Consultada no Recalculo'), (45, 'Revisão - Mesa de Formalização'), (46, 'Reprovada Revisão - Mesa de Formalização'), (47, 'Averbação - Mesa de Formalização'), (48, 'Saque Cancelado - Limite disponível Insuficiente'), (49, 'Saque Recusado - Problema no Pagamento'), (50, 'Andamento - Reapresentação do pagamento de saque'), (51, 'Pendenciado'), (52, 'Proposta enviada para QiTech, aguardando retorno.'), (52, 'Em Andamento – Consulta Dataprev'), (53, 'Erro – Consulta Dataprev'), (54, 'Reprovado – Consulta Dataprev')], default=1, null=True, verbose_name='Status do Contrato')),
                ('banco', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('numero_beneficio', models.CharField(blank=True, max_length=100, verbose_name='Benefício')),
                ('especie', models.CharField(blank=True, max_length=100, verbose_name='Especie')),
                ('numero_contrato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Contrato')),
                ('saldo_devedor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='Saldo Devedor')),
                ('prazo', models.IntegerField(blank=True, verbose_name='Prazo')),
                ('taxa', models.DecimalField(blank=True, decimal_places=7, default=None, max_digits=12, null=True, verbose_name='Taxa')),
                ('parcela_digitada', models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='Parcela Digitada')),
                ('nova_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='Nova Parcela')),
                ('chave_proposta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chave proposta')),
                ('status_ccb', models.SmallIntegerField(blank=True, choices=[(0, 'pending_subimission'), (1, 'pending_response'), (2, 'pending_acceptance'), (3, 'accepted'), (4, 'canceled'), (5, 'retained'), (6, 'settlement_sent'), (7, 'pending_settlement_confirmation'), (8, 'paid'), (9, ' rejected'), (10, ' signature_received')], null=True, verbose_name='Status')),
                ('CPF_dados_divergentes', models.BooleanField(default=False, help_text='Indica se o CPF está Irregular na Receita Federal', verbose_name='CPF irregular na receita?')),
                ('numero_refinanciamento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Número refinanciamento - Qitech')),
                ('document_key_QiTech_Frente_ou_CNH', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chave do Documento Pessoal Frente/CNH')),
                ('document_key_QiTech_Verso', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chave do Documento Pessoal Verso')),
                ('document_key_QiTech_CCB', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chave do Documento CCB')),
                ('document_key_QiTech_Selfie', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chave da Selfie')),
                ('related_party_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='Related_Party_Key')),
                ('numero_refinanciamento_CTC_CIP', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numero do Refinanciamento CTC/CIP')),
                ('saldo_devedor_atualizado', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Saldo Devedor Atualizado')),
                ('numero_parcela_atualizada', models.IntegerField(blank=True, null=True, verbose_name='Numero Parcelas Atualizada')),
                ('taxa_contrato_original', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Taxa Contrato Original')),
                ('taxa_contrato_recalculada', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Taxa Contrato Recalculada')),
                ('valor_parcela_original', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor da Parcela Original')),
                ('valor_parcela_recalculada', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor da Parcela Recalculada')),
                ('motivo_recusa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo de Recusa do CTC/CIP')),
                ('ccb_gerada', models.BooleanField(default=False, help_text='Indica se a CCB foi gerada', verbose_name='CCB Gerada pela QITECH?')),
                ('sucesso_insercao_proposta', models.BooleanField(blank=True, default=None, help_text='Indica se a proposta foi inserida com sucesso', null=True, verbose_name='Sucesso na inserção proposta(QITECH)')),
                ('insercao_sem_sucesso', models.CharField(blank=True, help_text='Caso a insercao não foi bem sucedida aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo de erro na insercao QITECH')),
                ('sucesso_envio_assinatura', models.BooleanField(blank=True, default=None, help_text='Indica se o envio da assinatura foi realizado com sucesso', null=True, verbose_name='Sucesso Assinatura(QITECH)')),
                ('motivo_envio_assinatura', models.CharField(blank=True, help_text='Caso o envio de assinatura não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo Assinatura QITECH')),
                ('sucesso_envio_documento_frente_cnh', models.BooleanField(blank=True, default=None, help_text='Indica se o envio do documento(FRENTE/CNH) foi realizado com sucesso', null=True, verbose_name='Sucesso FRENTE/CNH(QITECH)')),
                ('motivo_envio_documento_frente_cnh', models.CharField(blank=True, help_text='Caso o envio de documento (FRENTE/CNH) não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo FRENTE/CNH(QITECH)')),
                ('sucesso_envio_documento_verso', models.BooleanField(blank=True, default=None, help_text='Indica se o envio do documento(VERSO) foi realizado com sucesso', null=True, verbose_name='Sucesso VERSO(QITECH)')),
                ('motivo_envio_documento_verso', models.CharField(blank=True, help_text='Caso o envio de documento (VERSO) não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo VERSO(QITECH)')),
                ('sucesso_envio_documento_selfie', models.BooleanField(blank=True, default=None, help_text='Indica se o envio do documento (SELFIE) foi realizado com sucesso', null=True, verbose_name='Sucesso SELFIE(QITECH)')),
                ('motivo_envio_documento_selfie', models.CharField(blank=True, help_text='Caso o envio de documento (SELFIE) não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo SELFIE(QITECH)')),
                ('sucesso_documentos_linkados', models.BooleanField(blank=True, default=None, help_text='Indica se a conexão dos documentos com a proposta foi realizada com sucesso', null=True, verbose_name='Sucesso CONEXÃO DOCUMENTOS(QITECH)')),
                ('motivo_documentos_linkados', models.CharField(blank=True, help_text='Caso a conexão dos documentos com a proposta não foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo CONEXÃO DOCUMENTOS(QITECH)')),
                ('sucesso_submissao_proposta', models.BooleanField(blank=True, default=None, help_text='Indica se a submissão da proposta foi realizada com sucesso', null=True, verbose_name='Sucesso SUBMISSÃO PROPOSTA(QITECH)')),
                ('motivo_submissao_proposta', models.CharField(blank=True, help_text='Caso a submissão da proposta nao foi bem sucedida aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo SUBMISSÃO PROPOSTA(QITECH)')),
                ('sucesso_aceite_proposta', models.BooleanField(blank=True, default=None, help_text='Indica se o aceite da proposta foi realizada com sucesso', null=True, verbose_name='Sucesso ACEITE PROPOSTA(QITECH)')),
                ('motivo_aceite_proposta', models.CharField(blank=True, help_text='Caso o ACEITE da proposta nao foi bem sucedido aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo ACEITE PROPOSTA(QITECH)')),
                ('sucesso_recusa_proposta', models.BooleanField(blank=True, default=None, help_text='Indica se a recusa da proposta foi realizada com sucesso', null=True, verbose_name='Sucesso RECUSA PROPOSTA(QITECH)')),
                ('motivo_recusa_proposta', models.CharField(blank=True, help_text='Caso a RECUSA da proposta nao foi bem sucedida aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo RECUSA PROPOSTA(QITECH)')),
                ('codigo_dataprev', models.CharField(blank=True, max_length=150, null=True, verbose_name='Código Dataprev')),
                ('descricao_dataprev', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição Dataprev')),
                ('dt_retorno_dataprev', models.DateField(blank=True, null=True, verbose_name='Data de retorno do Dataprev')),
                ('dt_envio_proposta_CIP', models.DateField(blank=True, help_text='Data de envio do aceite da proposta para a CIP', null=True, verbose_name='Data de envio da proposta(CIP)')),
                ('dt_recebimento_saldo_devedor', models.DateField(blank=True, help_text='Data de recebimento do saldo devedor(CIP)', null=True, verbose_name='Data de recebimento do saldo devedor(CIP)')),
                ('banco_atacado', models.CharField(blank=True, help_text='Banco que estamos refinanciando o Contrato', max_length=300, null=True, verbose_name='Banco Atacado')),
                ('dt_recusa_retido', models.DateField(blank=True, help_text='Data de recusa/retido (CIP)', null=True, verbose_name='Data de RECUSA/RETIDO')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_refinanciamento', to='contract.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Refinanciamento',
                'verbose_name_plural': 'Refinanciamentos',
            },
        ),
    ]
