# Generated by Django 4.2.3 on 2023-11-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0121_alter_cartaobeneficio_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaobeneficio',
            name='tipo_margem',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Margem Compra'), (2, 'Margem Saque'), (3, 'Margem Unica')], null=True, verbose_name='Tipo Margem Contratada'),
        ),
    ]
