# Generated by Django 4.2.3 on 2023-11-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0122_portabilidade_is_proposal_being_inserted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300, verbose_name='Assunto do email')),
                ('msg_email', models.CharField(blank=True, max_length=300, null=True, verbose_name='Mensagem Email')),
            ],
            options={
                'verbose_name': '3. Configurações Relatorios',
                'verbose_name_plural': '3. Configurações Relatorios',
            },
        ),
    ]
