# Generated by Django 4.2.3 on 2023-11-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0122_alter_cartaobeneficio_tipo_margem'),
        ('contract', '0123_reportsettings'),
    ]

    operations = [
    ]
