# Generated by Django 4.2.3 on 2023-11-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0126_alter_anexocontrato_tipo_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='refinanciamento',
            name='margem_liberada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Margem Liberaada'),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='troco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Troco'),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor da Refinanciamento'),
        ),
    ]
