# Generated by Django 4.2.3 on 2023-11-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0128_contrato_is_ccb_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='refinanciamento',
            name='sucesso_finalizada_proposta',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se a finalização da proposta foi realizada com sucesso', null=True, verbose_name='Sucesso FINALIZAÇÃO PROPOSTA(QITECH)'),
        ),
    ]
