# Generated by Django 4.2.3 on 2023-11-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0130_alter_margemlivre_insercao_sem_sucesso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaobeneficio',
            name='folha_compra',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Folha compra'),
        ),
        migrations.AddField(
            model_name='cartaobeneficio',
            name='folha_saque',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Folha saque'),
        ),
        migrations.AddField(
            model_name='cartaobeneficio',
            name='verba_compra',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Verba compra'),
        ),
        migrations.AddField(
            model_name='cartaobeneficio',
            name='verba_saque',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Verba saque'),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='credit_operation_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Status da operação de crédito'),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='disbursement_account_digit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Dígito da conta'),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='disbursement_account_number',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Número da conta'),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='disbursement_branch_number',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Número da agência'),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='disbursement_ispb',
            field=models.CharField(blank=True, help_text='ISPB – Identificador do Sistema de Pagamentos Brasileiro', max_length=300, null=True, verbose_name='ISPB do banco'),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='document_url_qitech_ccb',
            field=models.URLField(blank=True, null=True, verbose_name='Link da CCB'),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='fine_configuration',
            field=models.JSONField(blank=True, null=True, verbose_name='Fine configuration'),
        ),
        migrations.AlterField(
            model_name='cartaobeneficio',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente'), (41, 'Reprovado'), (42, 'Aguardando Retorno da IN100'), (43, 'Aguardando Consulta IN100 (RECALCULO)'), (44, 'IN100 Consultada no Recalculo'), (45, 'Revisão - Mesa de Formalização'), (46, 'Reprovada Revisão - Mesa de Formalização'), (47, 'Averbação - Mesa de Formalização'), (48, 'Saque Cancelado - Limite disponível Insuficiente'), (49, 'Saque Recusado - Problema no Pagamento'), (50, 'Andamento - Reapresentação do pagamento de saque'), (51, 'Pendenciado'), (52, 'Em Andamento – Consulta Dataprev'), (53, 'Erro – Consulta Dataprev'), (54, 'Reprovado – Consulta Dataprev'), (55, 'Aguardando Averbação Refinanciamento')], default=1, null=True, verbose_name='Status do Contrato'),
        ),
        migrations.AlterField(
            model_name='cartaobeneficio',
            name='tipo_margem',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Margem Compra'), (2, 'Margem Saque'), (3, 'Margem Unica'), (4, 'Margem Unificada')], null=True, verbose_name='Tipo Margem Contratada'),
        ),
        migrations.AlterField(
            model_name='margemlivre',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente'), (41, 'Reprovado'), (42, 'Aguardando Retorno da IN100'), (43, 'Aguardando Consulta IN100 (RECALCULO)'), (44, 'IN100 Consultada no Recalculo'), (45, 'Revisão - Mesa de Formalização'), (46, 'Reprovada Revisão - Mesa de Formalização'), (47, 'Averbação - Mesa de Formalização'), (48, 'Saque Cancelado - Limite disponível Insuficiente'), (49, 'Saque Recusado - Problema no Pagamento'), (50, 'Andamento - Reapresentação do pagamento de saque'), (51, 'Pendenciado'), (52, 'Em Andamento – Consulta Dataprev'), (53, 'Erro – Consulta Dataprev'), (54, 'Reprovado – Consulta Dataprev'), (55, 'Aguardando Averbação Refinanciamento')], default=1, null=True, verbose_name='Status do Contrato'),
        ),
        migrations.AlterField(
            model_name='portabilidade',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente'), (41, 'Reprovado'), (42, 'Aguardando Retorno da IN100'), (43, 'Aguardando Consulta IN100 (RECALCULO)'), (44, 'IN100 Consultada no Recalculo'), (45, 'Revisão - Mesa de Formalização'), (46, 'Reprovada Revisão - Mesa de Formalização'), (47, 'Averbação - Mesa de Formalização'), (48, 'Saque Cancelado - Limite disponível Insuficiente'), (49, 'Saque Recusado - Problema no Pagamento'), (50, 'Andamento - Reapresentação do pagamento de saque'), (51, 'Pendenciado'), (52, 'Em Andamento – Consulta Dataprev'), (53, 'Erro – Consulta Dataprev'), (54, 'Reprovado – Consulta Dataprev'), (55, 'Aguardando Averbação Refinanciamento')], default=1, null=True, verbose_name='Status do Contrato'),
        ),
        migrations.AlterField(
            model_name='refinanciamento',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente'), (41, 'Reprovado'), (42, 'Aguardando Retorno da IN100'), (43, 'Aguardando Consulta IN100 (RECALCULO)'), (44, 'IN100 Consultada no Recalculo'), (45, 'Revisão - Mesa de Formalização'), (46, 'Reprovada Revisão - Mesa de Formalização'), (47, 'Averbação - Mesa de Formalização'), (48, 'Saque Cancelado - Limite disponível Insuficiente'), (49, 'Saque Recusado - Problema no Pagamento'), (50, 'Andamento - Reapresentação do pagamento de saque'), (51, 'Pendenciado'), (52, 'Em Andamento – Consulta Dataprev'), (53, 'Erro – Consulta Dataprev'), (54, 'Reprovado – Consulta Dataprev'), (55, 'Aguardando Averbação Refinanciamento')], default=1, null=True, verbose_name='Status do Contrato'),
        ),
        migrations.AlterField(
            model_name='saquecomplementar',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente'), (41, 'Reprovado'), (42, 'Aguardando Retorno da IN100'), (43, 'Aguardando Consulta IN100 (RECALCULO)'), (44, 'IN100 Consultada no Recalculo'), (45, 'Revisão - Mesa de Formalização'), (46, 'Reprovada Revisão - Mesa de Formalização'), (47, 'Averbação - Mesa de Formalização'), (48, 'Saque Cancelado - Limite disponível Insuficiente'), (49, 'Saque Recusado - Problema no Pagamento'), (50, 'Andamento - Reapresentação do pagamento de saque'), (51, 'Pendenciado'), (52, 'Em Andamento – Consulta Dataprev'), (53, 'Erro – Consulta Dataprev'), (54, 'Reprovado – Consulta Dataprev'), (55, 'Aguardando Averbação Refinanciamento')], default=1, null=True, verbose_name='Status do contrato'),
        ),
        migrations.AlterField(
            model_name='statuscontrato',
            name='nome',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Simulação'), (5, 'Formalizaçao (cliente)'), (6, 'Aprovada – Finalizada'), (7, 'Reprovada – Finalizada'), (8, 'Checagem – Mesa Formalização'), (9, 'Aprovada – Mesa Formalização'), (10, 'Reprovada – Finalizada'), (11, 'Pendente Documentação'), (12, 'Em averbação'), (13, 'Aprovada - Averbação'), (14, 'Recusada - Averbação'), (15, 'Andamento – Emissão cartão'), (16, 'Finalizada – Emissão cartão'), (17, 'Andamento – Liberação Pagamento Saque'), (18, 'Finalizado – Liberação Pagamento Saque'), (19, 'Pendente - Correção de dados bancários'), (40, 'Erro - Transmissão do Contrato'), (20, 'Aguarda envio link'), (21, 'Formalização (cliente)'), (22, 'Análise de crédito (Bureaus)'), (23, 'Pendente - Dados Divergentes'), (24, 'Reprovada – Política Interna'), (25, 'Checagem - Mesa Corban'), (26, 'Pendente Documentação - Mesa Corban'), (27, 'Reprovada – Mesa Corban'), (28, 'Aprovada - Mesa Corban'), (29, 'Checagem - Mesa de Formalização'), (30, 'Aprovada - Mesa de Formalização'), (31, 'Reprovada – Mesa de Formalização'), (32, 'Aguarda Retorno Saldo'), (33, 'Saldo Retornado'), (34, 'INT - Confirma pagamento'), (35, 'Saldo Reprovado'), (36, 'Reprovada - Pagamento Devolvido'), (37, 'Int - Aguarda Averbação'), (38, 'Int - Finalizado'), (39, 'Int - Averbação Pendente'), (41, 'Reprovado'), (42, 'Aguardando Retorno da IN100'), (43, 'Aguardando Consulta IN100 (RECALCULO)'), (44, 'IN100 Consultada no Recalculo'), (45, 'Revisão - Mesa de Formalização'), (46, 'Reprovada Revisão - Mesa de Formalização'), (47, 'Averbação - Mesa de Formalização'), (48, 'Saque Cancelado - Limite disponível Insuficiente'), (49, 'Saque Recusado - Problema no Pagamento'), (50, 'Andamento - Reapresentação do pagamento de saque'), (51, 'Pendenciado'), (52, 'Em Andamento – Consulta Dataprev'), (53, 'Erro – Consulta Dataprev'), (54, 'Reprovado – Consulta Dataprev'), (55, 'Aguardando Averbação Refinanciamento')], default=1, null=True, verbose_name='Nome do status'),
        ),
    ]
