# Generated by Django 4.2.3 on 2023-12-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contract', '0132_cartaobeneficio_instituidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='refinanciamento',
            name='sucesso_desembolso_refinanciamento',
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text='Indica se houve o desembolso do refinanciamento pela QITECH',
                null=True,
                verbose_name='Sucesso Desembolso Refinanciamento(QITECH)',
            ),
        ),
    ]
