# Generated by Django 4.2.3 on 2023-12-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0133_refinanciamento_sucesso_desembolso_refinanciamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaobeneficio',
            name='classificacao_siape',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Classificação - SIAPE'),
        ),
        migrations.AddField(
            model_name='cartaobeneficio',
            name='convenio_siape',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Covenio - SIAPE'),
        ),
    ]
