# Generated by Django 4.2.3 on 2023-12-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0139_alter_cartaobeneficio_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinanciamento',
            name='valor_total_recalculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor do Refinanciamento Recalculado'),
        ),
    ]
