# Generated by Django 4.2.3 on 2023-12-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0140_alter_refinanciamento_valor_total_recalculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='refinanciamento',
            name='dt_averbacao',
            field=models.DateField(blank=True, help_text='Data de Averbação da Operação', null=True, verbose_name='Data de Averbação'),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='dt_desembolso',
            field=models.DateField(blank=True, help_text='Data de Desembolso da Operação', null=True, verbose_name='Data de Desembolso'),
        ),
    ]
