# Generated by Django 4.2.3 on 2023-12-19 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contract', '0142_alter_cartaobeneficio_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refinanciamento',
            name='payment_refused_incoming_data',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='refinanciamento',
                to='contract.paymentrefusedincomingdata',
                verbose_name='Dados do cancelamento do pagamento',
            ),
        ),
    ]
