# Generated by Django 4.2.3 on 2023-12-19 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contract', '0143_refinanciamento_payment_refused_incoming_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinanciamento',
            name='payment_refused_incoming_data',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='refinanciamento',
                to='contract.paymentrefusedincomingdata',
                verbose_name='Dados do cancelamento do pagamento',
            ),
        ),
    ]
