# Generated by Django 4.2.3 on 2023-12-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contract', '0144_alter_refinanciamento_payment_refused_incoming_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexocontrato',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
