# Generated by Django 4.2.3 on 2023-12-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contract', '0147_refinanciamento_dt_primeiro_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexocontrato',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
