# Generated by Django 4.2.3 on 2024-01-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contract', '0151_alter_cartaobeneficio_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscontrato',
            name='original_proposals_status',
            field=models.JSONField(
                blank=True, null=True, verbose_name='Status originais das propostas'
            ),
        ),
    ]
