# Generated by Django 4.2.3 on 2024-01-19 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0087_parametrosproduto_teto_inss'),
        ('cartao_beneficio', '0058_alter_planos_seguradora'),
        ('contract', '0152_statuscontrato_original_proposals_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaobeneficio',
            name='convenio',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cartao_convenio',
                to='cartao_beneficio.convenios',
                verbose_name='Convenio',
            ),
        ),
        migrations.AlterField(
            model_name='saquecomplementar',
            name='id_cliente_cartao',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cliente_cartao_contrato_saque_complementar',
                to='core.clientecartaobeneficio',
                verbose_name='ID Cliente Cartão',
            ),
        ),
    ]
