# Generated by Django 4.2.3 on 2024-01-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0153_alter_cartaobeneficio_convenio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelopecontratos',
            name='erro_restritivo_unico',
            field=models.BooleanField(default=False, verbose_name='Erro Restritivo Unico?'),
        ),
        migrations.AddField(
            model_name='envelopecontratos',
            name='erro_unico',
            field=models.BooleanField(default=True, verbose_name='Erro Unico?'),
        ),
    ]
