# Generated by Django 4.2.3 on 2024-01-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0155_alter_cartaobeneficio_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuscontrato",
            name="descricao_front",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Descrição Front"
            ),
        ),
    ]
