# Generated by Django 4.2.3 on 2024-01-31 20:43

from django.db import migrations, models


def popula_contrato(apps, schema_editor):
    Contrato = apps.get_model('contract', 'Contrato')
    DadosIn100 = apps.get_model('consignado_inss', 'DadosIn100')

    for contrato in Contrato.objects.all():
        if dados_in100 := DadosIn100.objects.filter(
                cliente=contrato.cliente
        ).first():
            numero_beneficio = dados_in100.numero_beneficio
            contrato.numero_beneficio = numero_beneficio
            contrato.save(update_fields=['numero_beneficio'])


class Migration(migrations.Migration):
    dependencies = [
        ('contract', '0156_statuscontrato_descricao_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='numero_beneficio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero Benefício'),
        ),
        migrations.RunPython(popula_contrato),
    ]
