# Generated by Django 4.2.3 on 2024-02-27 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0162_contrato_contrato_cross_sell'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularizacaocontrato',
            options={'verbose_name': 'Regularização Averbação', 'verbose_name_plural': 'Regularização Averbação'},
        ),
    ]
