# Generated by Django 4.2.3 on 2024-02-29 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0163_alter_regularizacaocontrato_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaTeimosinhaINSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitada_em', models.DateTimeField(verbose_name='Solicitada em')),
                ('respondida_em', models.DateTimeField(blank=True, null=True, verbose_name='Respondida em')),
                ('proxima_tentativa_em', models.DateTimeField(blank=True, null=True, verbose_name='Próxima tentativa em')),
                ('sucesso', models.BooleanField(default=False, verbose_name='Sucesso')),
                ('retorno_dataprev', models.JSONField(blank=True, null=True, verbose_name='Retorno Dataprev')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contrato', verbose_name='Contrato')),
            ],
        ),
    ]
