# Generated by Django 4.2.3 on 2024-03-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0094_cliente_escolaridade_and_more"),
        ("contract", "0164_tentativateimosinhainss"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="rogado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.rogado",
                verbose_name="Rogado",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="url_formalizacao_rogado",
            field=models.CharField(
                default="",
                max_length=300,
                null=True,
                verbose_name="URL de Formalização do Rogado",
            ),
        ),
        migrations.AlterField(
            model_name="anexocontrato",
            name="tipo_anexo",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "CCB"),
                    (2, "Documento do cliente frente"),
                    (3, "Documento do cliente verso"),
                    (12, "Documentos Adicionais"),
                    (4, "Selfie"),
                    (5, "Foto da Prova de Vida"),
                    (6, "Comprovante de endereço"),
                    (7, "Comprovante financeiro"),
                    (11, "Repasse"),
                    (22, "Arquivo retorno reserva"),
                    (8, "Documento - CNH"),
                    (13, "Documento Frente - CNH"),
                    (14, "Documento Verso - CNH"),
                    (15, "Termos e assinaturas"),
                    (16, "Contracheque"),
                    (17, "Documento assinado fisicamente"),
                    (18, "Documento frente rogado"),
                    (19, "Documento verso rogado"),
                ],
                null=True,
                verbose_name="Tipo do anexo",
            ),
        ),
    ]
