# Generated by Django 4.1.3 on 2023-05-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAlteracaoCadastral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.CharField(max_length=20, verbose_name='Tipo de Registro')),
                ('registro_anterior', models.CharField(max_length=300, verbose_name='Registro Anterior')),
                ('novo_registro', models.CharField(max_length=300, verbose_name='Novo Registro')),
                ('usuario', models.CharField(max_length=300, verbose_name='Usuário')),
                ('canal', models.CharField(max_length=300, verbose_name='Canal')),
                ('data_hora', models.CharField(max_length=300, verbose_name='Data e Hora')),
                ('atualiza_dock', models.BooleanField(default=False, verbose_name='Atualiza Dock')),
            ],
        ),
    ]
