# Generated by Django 4.1.3 on 2023-05-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logalteracaocadastral',
            options={'verbose_name': 'Histórico de alteração', 'verbose_name_plural': 'Histórico de alterações'},
        ),
    ]
