# Generated by Django 4.2.2 on 2023-07-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_alter_logalteracaocadastraldock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logalteracaocadastraldadoscliente',
            name='canal',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='logalteracaocadastraldadoscliente',
            name='novo_registro',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Novo Registro'),
        ),
        migrations.AlterField(
            model_name='logalteracaocadastraldadoscliente',
            name='registro_anterior',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Registro Anterior'),
        ),
        migrations.AlterField(
            model_name='logalteracaocadastraldadoscliente',
            name='tipo_registro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Registro'),
        ),
        migrations.AlterField(
            model_name='logalteracaocadastraldadoscliente',
            name='usuario',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='logalteracaocadastraldock',
            name='canal',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='logalteracaocadastraldock',
            name='novo_registro',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Novo Registro'),
        ),
        migrations.AlterField(
            model_name='logalteracaocadastraldock',
            name='registro_anterior',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Registro Anterior'),
        ),
        migrations.AlterField(
            model_name='logalteracaocadastraldock',
            name='usuario',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Usuário'),
        ),
    ]
