# Generated by Django 4.1.3 on 2023-04-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_dt_nascimento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadoCliente',
        ),
    ]
