# Generated by Django 4.1.3 on 2023-04-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cliente_telefone_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosbancarios',
            name='conta_agencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número da agência'),
        ),
        migrations.AlterField(
            model_name='dadosbancarios',
            name='conta_banco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número do banco'),
        ),
        migrations.AlterField(
            model_name='dadosbancarios',
            name='conta_cpf_titular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CPF do Titular'),
        ),
        migrations.AlterField(
            model_name='dadosbancarios',
            name='conta_digito',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dígito da conta'),
        ),
        migrations.AlterField(
            model_name='dadosbancarios',
            name='conta_numero',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número da conta'),
        ),
    ]
