# Generated by Django 4.1.3 on 2023-04-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_dadosbancarios_conta_agencia_and_more'),
    ]

    operations = [
    ]
