# Generated by Django 4.1.3 on 2023-05-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_parametrosproduto_tipoproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosbackoffice',
            name='valor_outros',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=12, null=True, verbose_name='Outros valores'),
        ),
    ]
