# Generated by Django 4.1.3 on 2023-05-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_parametrosbackoffice_tipoproduto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteinss',
            name='nome_beneficio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome do benefício'),
        ),
        migrations.AddField(
            model_name='clienteinss',
            name='nu_beneficio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do benefício'),
        ),
        migrations.AddField(
            model_name='clienteinss',
            name='uf_beneficio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='UF do benefício'),
        ),
    ]
