# Generated by Django 4.1.3 on 2023-05-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_clienteinss_nome_beneficio_clienteinss_nu_beneficio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='IP_Cliente',
            field=models.CharField(blank=True, default=None, help_text='Utilizado na CCB.', max_length=50, null=True, verbose_name='IP Publico do Cliente'),
        ),
    ]
