# Generated by Django 4.1.3 on 2023-05-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cliente_ip_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrosbackoffice',
            name='valor_outros',
        ),
    ]
