# Generated by Django 4.1.3 on 2023-05-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_parametrosbackoffice_valor_outros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cd_cliente_parceiro',
        ),
        migrations.AddField(
            model_name='clienteinss',
            name='cd_cliente_parceiro',
            field=models.CharField(blank=True, default=None, help_text='Código do cliente no parceiro.', max_length=200, null=True, verbose_name='Cód. parceiro'),
        ),
    ]
