# Generated by Django 4.1.3 on 2023-05-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_parametrosproduto_geolocalizacao_exigida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrosproduto',
            name='geolocalizacao_exigida',
        ),
        migrations.AddField(
            model_name='parametrosbackoffice',
            name='geolocalizacao_exigida',
            field=models.BooleanField(default=True, verbose_name='Geolocalização Exigida'),
        ),
    ]
