# Generated by Django 4.1.3 on 2023-06-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_parametrosproduto_geolocalizacao_exigida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosbackoffice',
            name='geolocalizacao_exigida',
            field=models.BooleanField(default=True, verbose_name='Geolocalização Exigida?'),
        ),
    ]
