# Generated by Django 4.1.3 on 2023-06-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_parametrosbackoffice_geolocalizacao_exigida'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='in100_autorizada',
            field=models.BooleanField(default=False, verbose_name='IN100 Autorizada'),
        ),
    ]
