# Generated by Django 4.1.3 on 2023-06-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_parametrosbackoffice_tipoproduto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosbackoffice',
            name='tipoContrato',
            field=models.SmallIntegerField(choices=[(1, 'Operação nova (margem livre)'), (2, 'Refinanciamento'), (3, 'Refin Portabilidade'), (4, 'Portabilidade'), (5, 'Novo Aumento Salarial'), (6, 'Saque Complementar')], default=4, verbose_name='Tipo de Contrato'),
        ),
    ]
