# Generated by Django 4.2.2 on 2023-06-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cliente_in100_autorizada'),
        ('core', '0025_alter_parametrosbackoffice_tipocontrato'),
    ]

    operations = [
    ]
