# Generated by Django 4.2.2 on 2023-06-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_20230612_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='in100_autorizada',
        ),
        migrations.AddField(
            model_name='cliente',
            name='in100_data_autorizacao',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data de autorização da IN100'),
        ),
    ]
