# Generated by Django 4.2.2 on 2023-06-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_cliente_in100_autorizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='in100_autorizada',
            field=models.BooleanField(default=False, verbose_name='IN100 Autorizada'),
        ),
    ]
