# Generated by Django 4.2.2 on 2023-06-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_cliente_in100_autorizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='salario_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salário Liquido'),
        ),
    ]
