# Generated by Django 4.2.2 on 2023-06-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_cliente_salario_liquido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='in100_autorizada',
        ),
    ]
