# Generated by Django 4.2.2 on 2023-06-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_cliente_in100_autorizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='in100_data_autorizacao',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Data de autorização da IN100'),
        ),
    ]
