# Generated by Django 4.2.2 on 2023-06-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_cliente_in100_data_autorizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='in100_data_autorizacao',
        ),
    ]
