# Generated by Django 4.2.2 on 2023-06-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_parametrosbackoffice_tipoproduto_and_more'),
        ('core', '0032_remove_cliente_in100_data_autorizacao'),
    ]

    operations = [
    ]
