# Generated by Django A.B on YYYY-MM-DD HH:MM
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_auto_20230619_1004"),
    ]

    operations = [
        migrations.AlterField(
            model_name="Cliente",
            name="id_unico",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
