# Generated by Django 4.2.2 on 2023-06-20 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0015_convenios_url'),
        ('core', '0040_alter_cliente_id_unico'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecartaobeneficio',
            name='convenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_convenio', to='cartao_beneficio.convenios', verbose_name='Convenio'),
        ),
    ]
