# Generated by Django 4.2.2 on 2023-06-22 20:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_clientecartaobeneficio_convenio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermosDeUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termos_de_uso', ckeditor.fields.RichTextField(blank=True)),
                ('politica_privacidade', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': '5. Termo de Uso',
                'verbose_name_plural': '5. Termos de Uso',
            },
        ),
    ]
