# Generated by Django 4.2.2 on 2023-06-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_termosdeuso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrosbackoffice',
            name='senha_admin',
        ),
        migrations.AddField(
            model_name='parametrosbackoffice',
            name='enviar_comissionamento',
            field=models.BooleanField(default=True, verbose_name='Enviar para Comissionamento?'),
        ),
    ]
