# Generated by Django 4.2.2 on 2023-06-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_parametrosbackoffice_senha_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosproduto',
            name='dia_vencimento_padrao_simulacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dia de Vencimento Padrão Para a Simulação'),
        ),
        migrations.AddField(
            model_name='parametrosproduto',
            name='dias_limite_para_desembolso',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dias Limite Para Desembolso'),
        ),
        migrations.AddField(
            model_name='parametrosproduto',
            name='meses_para_adicionar_quando_dias_uteis_maior_base',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meses Para Adicionar Quando A Quantidade de Dias Úteis for Maior que a Base'),
        ),
        migrations.AddField(
            model_name='parametrosproduto',
            name='meses_para_adicionar_quando_dias_uteis_menor_igual_base',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meses Para Adicionar Quando A Quantidade de Dias Úteis for Menor ou Igual a Base'),
        ),
        migrations.AddField(
            model_name='parametrosproduto',
            name='quantidade_dias_uteis_base_simulacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Dias Úteis Base Para Simulação'),
        ),
        migrations.AddField(
            model_name='parametrosproduto',
            name='valor_liberado_cliente_operacao_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Máximo Operação Liberado Para o Cliente'),
        ),
        migrations.AddField(
            model_name='parametrosproduto',
            name='valor_liberado_cliente_operacao_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Mínimo Operação Liberado Para o Cliente'),
        ),
        migrations.AddField(
            model_name='parametrosproduto',
            name='valor_minimo_parcela_simulacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Mínimo da Parcela'),
        ),
    ]
