# Generated by Django 4.2.2 on 2023-07-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_parametrosproduto_dia_vencimento_padrao_simulacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AceiteIN100',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cliente', models.CharField(max_length=100, null=True, verbose_name='CPF')),
                ('hash_assinatura', models.CharField(max_length=100, null=True, verbose_name='Hash da Assinatura')),
                ('data_aceite', models.CharField(max_length=100, null=True, verbose_name='Data do aceite')),
                ('data_vencimento_aceite', models.CharField(max_length=100, null=True, verbose_name='Data de vencimento do aceite')),
                ('token_in100', models.CharField(max_length=100, null=True, verbose_name='Token IN100')),
                ('data_criacao_token', models.CharField(max_length=100, null=True, verbose_name='Data de criação do Token')),
                ('data_vencimento_token', models.CharField(max_length=100, null=True, verbose_name='Data de vencimento do Token')),
            ],
            options={
                'verbose_name': 'Aceite IN100',
                'verbose_name_plural': '6. Aceite IN100',
            },
        ),
    ]
