# Generated by Django 4.2.2 on 2023-07-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_aceitein100_data_aceite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoaceitein100',
            options={'verbose_name': 'Documento Aceite', 'verbose_name_plural': 'Documento Aceite'},
        ),
    ]
