# Generated by Django 4.2.2 on 2023-07-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_parametrosproduto_data_inicio_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aceitein100',
            name='token_in100',
            field=models.CharField(max_length=500, null=True, verbose_name='Token IN100'),
        ),
    ]
