# Generated by Django 4.2.2 on 2023-08-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_aceitein100_token_in100'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceitein100',
            name='DV_conta_corrente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DVContaCorrente'),
        ),
        migrations.AddField(
            model_name='aceitein100',
            name='UFAPS',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ufPagamento'),
        ),
        migrations.AddField(
            model_name='aceitein100',
            name='agencia_pagadora',
            field=models.IntegerField(blank=True, null=True, verbose_name='agenciaPagadora'),
        ),
        migrations.AddField(
            model_name='aceitein100',
            name='canal',
            field=models.IntegerField(choices=[(1, 'Autoatendimento'), (2, 'Agencia'), (3, 'Digital Via Cliente'), (4, 'Digital Via Correspondente'), (5, 'Mobile')], default=4, verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='aceitein100',
            name='cbc_if_pagadora',
            field=models.IntegerField(blank=True, null=True, verbose_name='cbcIfPagadora'),
        ),
        migrations.AddField(
            model_name='aceitein100',
            name='conta_corrente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='contaCorrente'),
        ),
        migrations.AlterField(
            model_name='clienteinss',
            name='nome_beneficio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do benefício'),
        ),
        migrations.AlterField(
            model_name='clienteinss',
            name='nu_beneficio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número do benefício'),
        ),
    ]
