# Generated by Django 4.2.2 on 2023-08-10 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0097_merge_20230810_1013'),
        ('core', '0050_aceitein100_dv_conta_corrente_aceitein100_ufaps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiosContratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conta_dock', models.CharField(blank=True, max_length=50, null=True, verbose_name='Conta Dock atrelada ao cartão')),
                ('id_cartao_dock', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cartão Dock atrelada ao cartão')),
                ('id_plano', models.CharField(max_length=100, verbose_name='id do plano')),
                ('nome_operadora', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Operador')),
                ('tipo_plano', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo do plano')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('identificacao_segurado', models.CharField(max_length=50, verbose_name='identificação do segurado')),
                ('nome_plano', models.CharField(max_length=150, verbose_name='Nome do Plano')),
                ('valor_plano', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True, verbose_name='Valor do plano')),
                ('premio', models.CharField(max_length=50, verbose_name='premio')),
                ('validade', models.CharField(max_length=50, verbose_name='validade')),
                ('renovacao_automatica', models.BooleanField(default=False, verbose_name='Renovacao automatica')),
                ('carencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Carencia')),
                ('status', models.SmallIntegerField(choices=[(0, ''), (1, 'Criado com sucesso'), (2, 'Recusado Erro - Necessita de Atenção'), (3, 'Recusado pela Operadora')], default=0, verbose_name='Tipo de Produto')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cliente', verbose_name='contrato de empréstimo')),
                ('contrato_emprestimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contract.contrato', verbose_name='contrato de empréstimo')),
            ],
            options={
                'verbose_name': 'Seguro / Benefício',
                'verbose_name_plural': 'Seguro / Benefício',
            },
        ),
        migrations.CreateModel(
            name='ArquivoGenerali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmDocumento', models.CharField(max_length=300, verbose_name='Nome do documento')),
                ('documento', models.FileField(null=True, upload_to='arquivo', verbose_name='Documento')),
                ('sequencial', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Nº Seqüencial')),
                ('dtCriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('criadoPor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': '3. Arquivos',
            },
        ),
    ]
