# Generated by Django 4.2.2 on 2023-08-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_parametrosproduto_idade_especie_87_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceitein100',
            name='produto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Produtos'),
        ),
        migrations.AlterField(
            model_name='beneficioscontratado',
            name='valor_plano',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Valor do plano'),
        ),
    ]
