# Generated by Django 4.2.2 on 2023-08-22 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0100_alter_cartaobeneficio_status_alter_inss_status_and_more'),
        ('core', '0055_alter_parametrosbackoffice_celulares_por_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficioscontratado',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='contrato de empréstimo'),
        ),
        migrations.AlterField(
            model_name='beneficioscontratado',
            name='contrato_emprestimo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contrato', verbose_name='contrato de empréstimo'),
        ),
    ]
