# Generated by Django 4.2.2 on 2023-08-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_beneficioscontratado_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceitein100',
            name='nome_cliente',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome do Cliente'),
        ),
    ]
