# Generated by Django 4.2.3 on 2023-09-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_aceitein100_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosbancarios',
            name='retornado_in100',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Dado bancário retornado da IN100?'),
        ),
    ]
