# Generated by Django 4.2.3 on 2023-10-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0033_planos_codigo_ramo_planos_codigo_sucursal_and_more'),
        ('core', '0062_dadosbancarios_retornado_in100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficioscontratado',
            name='id_plano',
        ),
        migrations.AddField(
            model_name='beneficioscontratado',
            name='plano',
            field=models.ManyToManyField(blank=True, related_name='beneficio_planos', to='cartao_beneficio.planos', verbose_name='Planos'),
        ),
        migrations.AddField(
            model_name='parametrosproduto',
            name='multa_contrato_margem_livre',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Multa em %', max_digits=12, null=True, verbose_name='Multa do contrato de margem livre'),
        ),
        migrations.AddField(
            model_name='parametrosproduto',
            name='taxa_proposta_margem_livre',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taxa em %', max_digits=12, null=True, verbose_name='Taxa da proposta de margem livre'),
        ),
        migrations.AlterField(
            model_name='beneficioscontratado',
            name='status',
            field=models.SmallIntegerField(choices=[(0, ''), (1, 'Criado com sucesso'), (2, 'Recusado Erro - Necessita de Atenção'), (3, 'Recusado pela Operadora')], default=0, verbose_name='Status'),
        ),
    ]
