# Generated by Django 4.2.3 on 2023-10-06 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0033_planos_codigo_ramo_planos_codigo_sucursal_and_more'),
        ('core', '0063_remove_beneficioscontratado_id_plano_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficioscontratado',
            name='plano',
        ),
        migrations.AddField(
            model_name='beneficioscontratado',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficio_planos_contratados', to='cartao_beneficio.planos', verbose_name='Planos'),
        ),
    ]
