# Generated by Django 4.2.3 on 2023-10-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_beneficioscontratado_contrato_emprestimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficioscontratado',
            name='identificacao_segurado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='identificação do segurado'),
        ),
        migrations.AlterField(
            model_name='beneficioscontratado',
            name='nome_plano',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Plano'),
        ),
        migrations.AlterField(
            model_name='beneficioscontratado',
            name='premio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='premio'),
        ),
        migrations.AlterField(
            model_name='beneficioscontratado',
            name='validade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='validade'),
        ),
    ]
