# Generated by Django 4.2.3 on 2023-10-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_beneficioscontratado_identificacao_segurado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_confia',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='ID Confia'),
        ),
    ]
