# Generated by Django 4.2.3 on 2023-10-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_cliente_id_confia'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosbancarios',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
    ]
