# Generated by Django 4.2.3 on 2023-11-03 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0120_remove_envelopecontratos_id_processo_confia_and_more'),
        ('core', '0069_historicoaceitein100_dadosbeneficioin100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientecartaobeneficio',
            options={'verbose_name': 'Cartão', 'verbose_name_plural': 'Cartões'},
        ),
        migrations.AddField(
            model_name='clientecartaobeneficio',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_cartao_contrato', to='contract.contrato', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='clientecartaobeneficio',
            name='nome_impresso_dock',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Impresso'),
        ),
        migrations.AddField(
            model_name='clientecartaobeneficio',
            name='numero_cartao_dock',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Cartão'),
        ),
        migrations.AddField(
            model_name='clientecartaobeneficio',
            name='tipo_margem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Margem'),
        ),
        migrations.AddField(
            model_name='clientecartaobeneficio',
            name='tipo_produto',
            field=models.SmallIntegerField(choices=[(1, 'FGTS'), (2, 'INSS - Representante Legal'), (3, 'Cartão Benefício - Representante Legal'), (4, 'PAB'), (5, 'INSS CORBAN'), (6, 'INSS'), (7, 'Cartão Benefício'), (8, 'Siape'), (9, 'Exercito'), (10, 'Marinha'), (11, 'Aeronautica'), (12, 'Portabilidade'), (13, 'Consignado'), (14, 'Saque Complementar'), (15, 'Cartão Consignado'), (16, 'Margem Livre'), (17, 'Portabilidade + Refinanciamento')], default=7, verbose_name='Tipo de Produto'),
        ),
        migrations.AddField(
            model_name='parametrosproduto',
            name='valor_minimo_margem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor minimo da margem'),
        ),
        migrations.AlterField(
            model_name='aceitein100',
            name='produto',
            field=models.SmallIntegerField(choices=[(1, 'FGTS'), (2, 'INSS - Representante Legal'), (3, 'Cartão Benefício - Representante Legal'), (4, 'PAB'), (5, 'INSS CORBAN'), (6, 'INSS'), (7, 'Cartão Benefício'), (8, 'Siape'), (9, 'Exercito'), (10, 'Marinha'), (11, 'Aeronautica'), (12, 'Portabilidade'), (13, 'Consignado'), (14, 'Saque Complementar'), (15, 'Cartão Consignado'), (16, 'Margem Livre'), (17, 'Portabilidade + Refinanciamento')], default=7, verbose_name='Tipo de Produto'),
        ),
        migrations.AlterField(
            model_name='historicoaceitein100',
            name='produto',
            field=models.SmallIntegerField(choices=[(1, 'FGTS'), (2, 'INSS - Representante Legal'), (3, 'Cartão Benefício - Representante Legal'), (4, 'PAB'), (5, 'INSS CORBAN'), (6, 'INSS'), (7, 'Cartão Benefício'), (8, 'Siape'), (9, 'Exercito'), (10, 'Marinha'), (11, 'Aeronautica'), (12, 'Portabilidade'), (13, 'Consignado'), (14, 'Saque Complementar'), (15, 'Cartão Consignado'), (16, 'Margem Livre'), (17, 'Portabilidade + Refinanciamento')], default=7, verbose_name='Tipo de Produto'),
        ),
        migrations.AlterField(
            model_name='parametrosbackoffice',
            name='tipoProduto',
            field=models.SmallIntegerField(choices=[(1, 'FGTS'), (2, 'INSS - Representante Legal'), (3, 'Cartão Benefício - Representante Legal'), (4, 'PAB'), (5, 'INSS CORBAN'), (6, 'INSS'), (7, 'Cartão Benefício'), (8, 'Siape'), (9, 'Exercito'), (10, 'Marinha'), (11, 'Aeronautica'), (12, 'Portabilidade'), (13, 'Consignado'), (14, 'Saque Complementar'), (15, 'Cartão Consignado'), (16, 'Margem Livre'), (17, 'Portabilidade + Refinanciamento')], default=1, verbose_name='Tipo de Produto'),
        ),
        migrations.AlterField(
            model_name='parametrosproduto',
            name='tipoProduto',
            field=models.SmallIntegerField(choices=[(1, 'FGTS'), (2, 'INSS - Representante Legal'), (3, 'Cartão Benefício - Representante Legal'), (4, 'PAB'), (5, 'INSS CORBAN'), (6, 'INSS'), (7, 'Cartão Benefício'), (8, 'Siape'), (9, 'Exercito'), (10, 'Marinha'), (11, 'Aeronautica'), (12, 'Portabilidade'), (13, 'Consignado'), (14, 'Saque Complementar'), (15, 'Cartão Consignado'), (16, 'Margem Livre'), (17, 'Portabilidade + Refinanciamento')], default=1, verbose_name='Tipo de Produto'),
        ),
    ]
