# Generated by Django 4.2.3 on 2023-11-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_clientecartaobeneficio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecartaobeneficio',
            name='tipo_margem',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Margem Compra'), (2, 'Margem Saque'), (3, 'Margem Unificada')], null=True, verbose_name='Tipo Margem'),
        ),
    ]
