# Generated by Django 4.2.3 on 2023-11-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_clientecartaobeneficio_tipo_margem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecartaobeneficio',
            name='tipo_margem',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Margem Compra'), (2, 'Margem Saque'), (3, 'Margem Unica')], null=True, verbose_name='Tipo Margem'),
        ),
    ]
