# Generated by Django 4.2.3 on 2023-12-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_clientecartaobeneficio_instituidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecartaobeneficio',
            name='classificacao_siape',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Classificação - SIAPE'),
        ),
        migrations.AddField(
            model_name='clientecartaobeneficio',
            name='convenio_siape',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Covenio - SIAPE'),
        ),
        migrations.AlterField(
            model_name='clientecartaobeneficio',
            name='folha',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número da Folha'),
        ),
    ]
