# Generated by Django 4.2.3 on 2023-12-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_clientecartaobeneficio_tipo_vinculo_siape'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosproduto',
            name='percentual_maximo_aprovacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Aprovação - Até:'),
        ),
        migrations.AddField(
            model_name='parametrosproduto',
            name='percentual_maximo_pendencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pendência Corban - Até:'),
        ),
        migrations.AddField(
            model_name='parametrosproduto',
            name='valor_troco_minimo',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Valor do Troco Mínimo'),
        ),
    ]
