# Generated by Django 4.2.3 on 2023-12-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_parametrosproduto_percentual_maximo_aprovacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficioscontratado',
            name='premio',
        ),
        migrations.AddField(
            model_name='beneficioscontratado',
            name='premio_bruto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Prêmio Bruto'),
        ),
        migrations.AddField(
            model_name='beneficioscontratado',
            name='premio_liquido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Prêmio Líquido'),
        ),
    ]
