# Generated by Django 4.2.3 on 2023-12-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_remove_beneficioscontratado_premio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosproduto',
            name='prazo_maximo',
            field=models.IntegerField(blank=True, help_text='Valor em meses', null=True, verbose_name='Prazo maximo da proposta'),
        ),
        migrations.AlterField(
            model_name='parametrosproduto',
            name='prazo_minimo',
            field=models.IntegerField(blank=True, help_text='Valor em meses', null=True, verbose_name='Prazo minimo da proposta'),
        ),
    ]
