# Generated by Django 4.2.3 on 2024-01-03 12:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0079_alter_parametrosproduto_prazo_maximo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackofficeConfigs',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Criado em'),
                ),
                (
                    'session_expiration_time',
                    models.PositiveIntegerField(
                        blank=True,
                        default=1440,
                        help_text='Tempo em minutos',
                        null=True,
                        verbose_name='Tempo de expiração da sessão no backoffice',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Configuração do backoffice',
                'verbose_name_plural': 'Configurações do backoffice',
            },
        ),
    ]
