# Generated by Django 4.2.3 on 2024-01-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_backofficeconfigs'),
        ('core', '0080_parametrosproduto_taxa_minima_recalculo'),
    ]

    operations = [
    ]
