# Generated by Django 4.2.3 on 2024-01-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_merge_20240104_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backofficeconfigs',
            options={'verbose_name': '7. Configuração do backoffice', 'verbose_name_plural': '7. Configurações do backoffice'},
        ),
        migrations.AlterField(
            model_name='backofficeconfigs',
            name='session_expiration_time',
            field=models.PositiveIntegerField(blank=True, default=1440, help_text='Tempo em minutos', null=True, unique=True, verbose_name='Tempo de expiração da sessão no backoffice'),
        ),
    ]
