# Generated by Django 4.2.3 on 2024-01-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_alter_backofficeconfigs_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backofficeconfigs',
            name='first_password_expiration_days',
            field=models.PositiveIntegerField(default=5, help_text='Prazo em dias úteis', verbose_name='Prazo de expiração da primeira senha'),
        ),
        migrations.AddField(
            model_name='backofficeconfigs',
            name='subsequent_password_expiration_days',
            field=models.PositiveIntegerField(default=30, help_text='Prazo em dias corridos', verbose_name='Prazo de expiração das senhas subsequentes'),
        ),
    ]
