# Generated by Django 4.2.3 on 2024-01-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_backofficeconfigs_first_password_expiration_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backofficeconfigs',
            name='first_password_expiration_days',
        ),
        migrations.AddField(
            model_name='backofficeconfigs',
            name='email_password_expiration_days',
            field=models.PositiveIntegerField(default=5, help_text='Prazo em dias úteis', verbose_name='Prazo de expiração do link de redefinição de senha'),
        ),
    ]
