# Generated by Django 4.2.3 on 2024-01-16 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'core',
            '0084_remove_backofficeconfigs_first_password_expiration_days_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosproduto',
            name='percentual_variacao_troco_recalculo',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Valor de 0 a 100 (%)',
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name='Percentual de Variação do Troco para o Recálculo',
            ),
        ),
    ]
