# Generated by Django 4.2.3 on 2024-01-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contract', '0151_alter_cartaobeneficio_status_and_more'),
        ('core', '0085_parametrosproduto_percentual_variacao_troco_recalculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossieINSS',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                (
                    'matricula',
                    models.CharField(max_length=20, verbose_name='Matrícula'),
                ),
                ('data_envio', models.DateTimeField(verbose_name='Data do Envio')),
                (
                    'codigo_retorno',
                    models.CharField(max_length=10, verbose_name='Código de Retorno'),
                ),
                (
                    'hash_operacao',
                    models.CharField(max_length=64, verbose_name='Hash da Operação'),
                ),
                (
                    'detalhe_erro',
                    models.TextField(
                        blank=True, null=True, verbose_name='Detalhe do Erro'
                    ),
                ),
                (
                    'contrato',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contract.contrato',
                        verbose_name='Número do Contrato',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Dossiê INSS',
                'verbose_name_plural': '7. Dossiês INSS',
            },
        ),
    ]
