# Generated by Django 4.2.3 on 2024-01-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0086_dossieinss'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosproduto',
            name='teto_inss',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Utilizado apenas em Port+Refin',
                max_digits=12,
                null=True,
                verbose_name='Taxa teto INSS',
            ),
        ),
    ]
