# Generated by Django 4.2.3 on 2024-01-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_alter_beneficioscontratado_contrato_emprestimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosbancarios',
            name='conta_tipo',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Conta Corrente Pessoa Física'), (2, 'Conta Corrente Pessoa Jurídica'), (3, 'Conta Poupança Pessoa Física'), (4, 'Cartão magnético'), (5, 'Conta Pagamento Pessoa Física')], null=True, verbose_name='Tipo de conta'),
        ),
    ]
