# Generated by Django 4.2.3 on 2024-01-31 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0156_statuscontrato_descricao_front'),
        ('core', '0089_alter_dadosbancarios_conta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficioscontratado',
            name='qtd_arrecadacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quantidade de arrecadação'),
        ),
        migrations.AlterField(
            model_name='beneficioscontratado',
            name='status',
            field=models.SmallIntegerField(choices=[(0, ''), (1, 'Criado com sucesso'), (2, 'Recusado Erro - Necessita de Atenção'), (3, 'Recusado pela Operadora'), (4, 'Cancelado')], default=0, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='InformativoCancelamentoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_canelamento', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('motivo', models.SmallIntegerField(choices=[(1, 'Cancelamento a pedido'), (2, 'Cancelamento por inadimplência'), (3, 'Cancelamento por sinistro'), (4, 'Por troca de plano')], default=1, verbose_name='Motivo do cancelamento')),
                ('valor_estorno', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Valor do estorno')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelamento', to='core.cliente', verbose_name='Cliente')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_cancelamento', to='contract.contrato', verbose_name='Contrato')),
            ],
        ),
    ]
