# Generated by Django 4.2.3 on 2024-02-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_beneficioscontratado_qtd_arrecadacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosproduto',
            name='permite_oferta_cartao_inss',
            field=models.BooleanField(default=False, verbose_name='Permite oferta de Cartão INSS'),
        ),
    ]
