# Generated by Django 4.2.3 on 2024-02-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_parametrosproduto_permite_oferta_cartao_inss'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossieinss',
            options={'verbose_name': 'Dossiê INSS', 'verbose_name_plural': '8. Dossiês INSS'},
        ),
    ]
