# Generated by Django 4.2.3 on 2024-03-01 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0042_auto_20240122_1208'),
        ('core', '0092_alter_dossieinss_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraTeimosinhaINSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Informe o código de letras que terá o reprocessamento da reserva de margem.', max_length=10)),
                ('descricao', models.TextField(blank=True, help_text='Informe a descrição do código de letras que terá o reprocessamento da reserva de margem.', verbose_name='Descrição')),
                ('intervalo_reprocessamento', models.IntegerField(help_text='Informe o tempo de intervalo em minutos para reprocessar o contrato que tiver de receber o código de retorno da Dataprev dessa regra na Reserva de margem. Caso a Dataprev retorne BD, não haverá nova tentativa.', verbose_name='Intervalo de reprocessamento')),
                ('quantidade_tentativas', models.PositiveIntegerField(help_text='Informe quantas tentativas o sistema deverá realizar, respeitando o intervalo escolhido. Caso a Dataprev retorne BD antes do prazo escolhido, não haverá nova tentativa.', verbose_name='Quantidade de tentativas')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('produto', models.ForeignKey(help_text='Selecione o produto que será atendido por essa regra.', on_delete=django.db.models.deletion.CASCADE, to='custom_auth.produtos')),
            ],
            options={
                'verbose_name': 'Teimosinha INSS',
                'verbose_name_plural': '9. Teimosinha INSS',
            },
        ),
    ]
