# Generated by Django 4.2.3 on 2024-03-01 15:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0164_tentativateimosinhainss"),
        ("core", "0093_regrateimosinhainss"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="escolaridade",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Ensino Fundamental"),
                    (2, "Ensino Médio"),
                    (3, "Ensino Superior"),
                    (4, "Pós Graduado"),
                    (5, "Analfabeto"),
                ],
                null=True,
                verbose_name="Escolaridade",
            ),
        ),
        migrations.AlterField(
            model_name="backofficeconfigs",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.CreateModel(
            name="Testemunha",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "cpf",
                    models.CharField(
                        max_length=11,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
                ("data_nascimento", models.DateField()),
                (
                    "telefone",
                    models.CharField(
                        max_length=11,
                        validators=[utils.validators.CellphoneValidator()],
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="testemunhas",
                        to="core.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "contratos",
                    models.ManyToManyField(
                        related_name="testemunhas",
                        to="contract.contrato",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testemunha",
                "verbose_name_plural": "Testemunhas",
                "db_table": "testemunha",
            },
        ),
        migrations.CreateModel(
            name="Rogado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "cpf",
                    models.CharField(
                        max_length=11,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
                ("data_nascimento", models.DateField()),
                (
                    "grau_parentesco",
                    models.IntegerField(
                        choices=[
                            (1, "Pai"),
                            (2, "Mãe"),
                            (3, "Filho"),
                            (4, "Cônjuge"),
                            (5, "Irmão"),
                        ]
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        max_length=11,
                        validators=[utils.validators.CellphoneValidator()],
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "cliente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rogado",
                        to="core.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rogado",
                "verbose_name_plural": "Rogados",
                "db_table": "rogado",
            },
        ),
    ]
