# Generated by Django 4.1.3 on 2023-04-21 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, null=True, verbose_name='Nome do convênio')),
                ('codigo_folha', models.IntegerField(default=0, verbose_name='Código folha')),
                ('produto', models.SmallIntegerField(blank=True, choices=[(1, 'FGTS'), (2, 'INSS - Representante Legal'), (3, 'Cartão Benefício - Representante Legal'), (4, 'PAB'), (5, 'INSS CORBAN'), (6, 'INSS'), (7, 'Cartão Benefício')], null=True, verbose_name='Produtos para a oferta')),
                ('idade_minima', models.IntegerField(default=0, verbose_name='Idade mínima')),
                ('idade_maxima', models.IntegerField(default=100, verbose_name='Idade máxima')),
                ('margem_minima', models.DecimalField(decimal_places=7, default=0, max_digits=12, verbose_name='Margem mínima')),
                ('margem_maxima', models.DecimalField(decimal_places=7, default=0, max_digits=12, verbose_name='Margem máxima')),
                ('permite_saque', models.BooleanField(default=True, null=True, verbose_name='Permite Saque?')),
                ('percentual_saque', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Percentual destinado para saque')),
                ('vr_minimo_saque', models.DecimalField(decimal_places=7, default=0, max_digits=12, verbose_name='Valor mínimo de saque')),
                ('limite_minimo_credito', models.DecimalField(decimal_places=7, default=0, max_digits=12, verbose_name='Limite mínimo de crédito')),
                ('taxa_produto', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Valor da Taxa do produto')),
                ('cet_am', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Taxa CET a.m')),
                ('cet_aa', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Taxa CET a.a')),
                ('data_vencimento_fatura', models.IntegerField(blank=True, null=True, verbose_name='Dia de vencimento da fatura')),
                ('fator', models.DecimalField(decimal_places=7, default=0, max_digits=12, verbose_name='Fator de multiplicação')),
                ('seguro_obrigatorio', models.BooleanField(default=False, verbose_name='Seguro obrigatório?')),
                ('porcentagem_seguro', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Porcentagem de desconto do seguro sobre o limite do cartão')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Parâmetro - Convênio',
                'verbose_name_plural': '2. Parâmetros - Convênios',
            },
        ),
        migrations.CreateModel(
            name='LimiteDeCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade_minima', models.IntegerField(default=0, verbose_name='Idade mínima')),
                ('idade_maxima', models.IntegerField(default=100, verbose_name='Idade máxima')),
                ('limite_maximo_credito', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='Limite máximo de crédito')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo?')),
                ('convenio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cartao_beneficio.convenios', verbose_name='Convênio')),
            ],
            options={
                'verbose_name': 'Limite de crédito - Idade',
                'verbose_name_plural': '5. Limite de crédito - Idade',
            },
        ),
        migrations.CreateModel(
            name='FontePagadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=300, verbose_name='Razão Social')),
                ('CNPJ', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('convenios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cartao_beneficio.convenios', verbose_name='Convenios')),
            ],
            options={
                'verbose_name': 'Convênio - Fonte Pagadora',
                'verbose_name_plural': 'Convênio - Fontes Pagadoras',
            },
        ),
    ]
