# Generated by Django 4.1.3 on 2023-04-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='senha_convenio',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Senha do Convênio'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='usuario_convenio',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Usuário do Convênio'),
        ),
    ]
