# Generated by Django 4.1.3 on 2023-04-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0002_convenios_senha_convenio_convenios_usuario_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='averbadora',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Facil'), (2, 'Zetrasoft'), (3, 'Quantum')], null=True, verbose_name='Averbadora'),
        ),
    ]
