# Generated by Django 4.1.3 on 2023-04-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0003_convenios_averbadora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fontepagadora',
            options={'verbose_name': 'Fonte Pagadora', 'verbose_name_plural': 'Fontes Pagadoras'},
        ),
        migrations.AlterModelOptions(
            name='limitedecredito',
            options={'verbose_name': 'Limite de crédito - Idade', 'verbose_name_plural': 'Limite de crédito - Idade'},
        ),
    ]
