# Generated by Django 4.1.3 on 2023-04-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0004_alter_fontepagadora_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, null=True, verbose_name='Nome do plano')),
                ('valor_plano', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do plano')),
                ('descricao_plano', models.TextField(blank=True, null=True, verbose_name='Descrição do plano')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': '6. Parâmetros - Plano',
                'verbose_name_plural': '6. Parâmetros - Planos',
            },
        ),
    ]
