# Generated by Django 4.1.3 on 2023-04-27 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0005_planos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convenios',
            options={'verbose_name': 'Parâmetro - Convênio', 'verbose_name_plural': '1. Parâmetros - Convênios'},
        ),
        migrations.AlterModelOptions(
            name='planos',
            options={'verbose_name': '2. Parâmetros - Plano', 'verbose_name_plural': '2. Parâmetros - Planos'},
        ),
    ]
