# Generated by Django 4.1.3 on 2023-05-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0006_alter_convenios_options_alter_planos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenios',
            name='produto',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'FGTS'), (2, 'INSS - Representante Legal'), (3, 'Cartão Benefício - Representante Legal'), (4, 'PAB'), (5, 'INSS CORBAN'), (6, 'INSS'), (7, 'Cartão Benefício'), (8, 'Consignado'), (9, 'Portabilidade')], null=True, verbose_name='Produtos para a oferta'),
        ),
    ]
