# Generated by Django 4.1.3 on 2023-05-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0007_alter_convenios_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='verba',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número da Verba'),
        ),
    ]
