# Generated by Django 4.1.3 on 2023-05-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0007_alter_convenios_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='id_produto_logo_dock',
            field=models.IntegerField(blank=True, null=True, verbose_name='id_produto/Logo Dock'),
        ),
    ]
