# Generated by Django 4.1.3 on 2023-05-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0008_convenios_id_produto_logo_dock'),
        ('cartao_beneficio', '0009_alter_convenios_verba'),
    ]

    operations = [
    ]
