# Generated by Django 4.2.2 on 2023-06-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0014_alter_convenios_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='URL'),
        ),
    ]
