# Generated by Django 4.2.2 on 2023-06-29 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0015_convenios_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='permite_saque_parcelado',
            field=models.BooleanField(default=True, null=True, verbose_name='Permite contratação de Saque Parcelado'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='saque_parc_cod_dock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Dock de Lançamento do Saque Parcelado'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='saque_parc_qnt_min_parcelas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade mínima de parcelas'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='saque_parc_val_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor mínimo em reais da parcela'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='saque_parc_val_total',
            field=models.IntegerField(blank=True, help_text='Este campo será preenchido ao final do cadastro.', null=True, verbose_name='Valor total da contratação mínimo em reais (Sem o cálculo CET)'),
        ),
        migrations.AlterField(
            model_name='convenios',
            name='percentual_saque',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Percentual do limite para o Saque Rotativo e/ou Parcelado'),
        ),
        migrations.AlterField(
            model_name='convenios',
            name='permite_saque',
            field=models.BooleanField(default=True, null=True, verbose_name='Permite contratação de Saque Rotativo'),
        ),
        migrations.AlterField(
            model_name='convenios',
            name='vr_minimo_saque',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=12, null=True, verbose_name='Valor mínimo para solicitação do Saque Rotativo'),
        ),
        migrations.CreateModel(
            name='OpcoesParcelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt_parcelamento', models.IntegerField(blank=True, null=True, verbose_name='Grupo de Parcelas')),
                ('convenio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cartao_beneficio.convenios', verbose_name='Convênio')),
            ],
            options={
                'verbose_name': 'Opção Parcelamento',
                'verbose_name_plural': 'Opções Parcelamento Saque',
            },
        ),
    ]
