# Generated by Django 4.2.2 on 2023-07-04 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0016_convenios_permite_saque_parcelado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenios',
            name='codigo_folha',
        ),
        migrations.CreateModel(
            name='SubOrgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_orgao', models.CharField(max_length=255, verbose_name='Nome do Órgão')),
                ('codigo_folha', models.CharField(max_length=255, verbose_name='Código Folha')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('convenio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cartao_beneficio.convenios', verbose_name='Convênio')),
            ],
            options={
                'verbose_name': 'Sub-órgão',
                'verbose_name_plural': 'Sub-órgãos',
            },
        ),
        migrations.AddField(
            model_name='limitedecredito',
            name='suborgao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cartao_beneficio.suborgao', verbose_name='Sub-órgão'),
        ),
    ]
