# Generated by Django 4.2.2 on 2023-07-06 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0017_remove_convenios_codigo_folha_suborgao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suborgao',
            options={'verbose_name': 'Sub-Orgão / Benefício INSS', 'verbose_name_plural': 'Sub-Orgãos / Benefício INSS'},
        ),
        migrations.AlterField(
            model_name='limitedecredito',
            name='suborgao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cartao_beneficio.suborgao', verbose_name='Sub-Orgão / Benefício INSS'),
        ),
        migrations.AlterField(
            model_name='suborgao',
            name='codigo_folha',
            field=models.CharField(max_length=255, verbose_name='Código Folha / Benefício INSS'),
        ),
    ]
