# Generated by Django 4.2.2 on 2023-07-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0018_alter_suborgao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborgao',
            name='convenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suborgao_convenio', to='cartao_beneficio.convenios', verbose_name='Convênio'),
        ),
    ]
