# Generated by Django 4.2.2 on 2023-07-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0019_alter_suborgao_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='convenio_inss',
            field=models.BooleanField(default=False, verbose_name='Convênio INSS?'),
        ),
        migrations.AlterField(
            model_name='convenios',
            name='verba',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número da Verba'),
        ),
        migrations.CreateModel(
            name='SituacaoBeneficioINSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0, verbose_name='Idade mínima')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('permite_contratacao', models.BooleanField(default=False, verbose_name='Permite contratação?')),
                ('convenio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cartao_beneficio.convenios', verbose_name='Convênio')),
            ],
            options={
                'verbose_name': 'Situação Benefício/INSS',
                'verbose_name_plural': 'Situação Benefício/INSS',
            },
        ),
        migrations.CreateModel(
            name='PensaoAlimenticiaINSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0, verbose_name='Idade mínima')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('permite_contratacao', models.BooleanField(default=False, verbose_name='Permite contratação?')),
                ('convenio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cartao_beneficio.convenios', verbose_name='Convênio')),
            ],
            options={
                'verbose_name': 'Pensão Alimentícia INSS',
                'verbose_name_plural': 'Pensão Alimentícia INSS',
            },
        ),
        migrations.CreateModel(
            name='EspecieBeneficioINSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0, verbose_name='Idade mínima')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('permite_contratacao', models.BooleanField(default=False, verbose_name='Permite contratação?')),
                ('convenio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cartao_beneficio.convenios', verbose_name='Convênio')),
            ],
            options={
                'verbose_name': 'Espécie de Benefício INSS',
                'verbose_name_plural': 'Espécie de Benefício INSS',
            },
        ),
    ]
