# Generated by Django 4.2.2 on 2023-07-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0020_convenios_convenio_inss_alter_convenios_verba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especiebeneficioinss',
            name='codigo',
            field=models.IntegerField(default=0, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='pensaoalimenticiainss',
            name='codigo',
            field=models.IntegerField(default=0, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='situacaobeneficioinss',
            name='codigo',
            field=models.IntegerField(default=0, verbose_name='Código'),
        ),
    ]
