# Generated by Django 4.2.2 on 2023-08-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0021_alter_especiebeneficioinss_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenios',
            name='averbadora',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Facil'), (2, 'Zetrasoft'), (3, 'Quantum'), (4, 'Dataprev - BRB')], null=True, verbose_name='Averbadora'),
        ),
    ]
