# Generated by Django 4.2.2 on 2023-08-01 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0022_alter_convenios_averbadora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suborgao',
            options={'verbose_name': 'Sub-Orgão', 'verbose_name_plural': 'Sub-Orgãos'},
        ),
        migrations.AlterField(
            model_name='limitedecredito',
            name='suborgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cartao_beneficio.suborgao', verbose_name='Sub-Orgão'),
        ),
        migrations.AlterField(
            model_name='suborgao',
            name='codigo_folha',
            field=models.IntegerField(null=True, verbose_name='Código Folha'),
        ),
    ]
