# Generated by Django 4.2.2 on 2023-08-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0024_convenios_limite_maximo_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='digitacao_manual',
            field=models.BooleanField(default=False, verbose_name='Permite digitação manual de contrato?'),
        ),
    ]
