# Generated by Django 4.2.2 on 2023-08-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0026_alter_convenios_averbadora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenios',
            name='averbadora',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Facil'), (2, 'Zetrasoft'), (3, 'Quantum'), (4, 'Dataprev - BRB'), (5, 'Dataprev - PINE')], null=True, verbose_name='Averbadora'),
        ),
    ]
