# Generated by Django 4.2.3 on 2023-09-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0028_alter_convenios_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='corte',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dia de corte da fatura'),
        ),
    ]
