# Generated by Django 4.2.3 on 2023-09-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cartao_beneficio', '0029_convenios_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='senha_servidor',
            field=models.BooleanField(
                default=False, verbose_name='Solicita Senha Servidor?'
            ),
        ),
    ]
