# Generated by Django 4.2.3 on 2023-09-22 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0021_facematchingconfig_alter_produtos_tipo_produto'),
        ('cartao_beneficio', '0031_alter_convenios_averbadora_alter_convenios_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguradoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, null=True, verbose_name='Nome')),
                ('tipo_comunicacao', models.SmallIntegerField(choices=[(1, 'Arquivo'), (2, 'API')], null=True, verbose_name='Tipo de Comunicação')),
                ('url_arquvio', models.CharField(max_length=300, null=True, verbose_name='URL Arquivo')),
                ('url_api', models.CharField(max_length=300, null=True, verbose_name='URL API')),
                ('usuario_seguro', models.CharField(max_length=300, null=True, verbose_name='Usuário')),
                ('senha_seguro', models.CharField(max_length=300, null=True, verbose_name='Senha')),
            ],
            options={
                'verbose_name': 'Parametro Seguradora',
                'verbose_name_plural': '3. Parametros Seguradoras',
            },
        ),
        migrations.RemoveField(
            model_name='planos',
            name='valor_plano',
        ),
        migrations.AddField(
            model_name='planos',
            name='apolice',
            field=models.CharField(max_length=300, null=True, verbose_name='Apólice'),
        ),
        migrations.AddField(
            model_name='planos',
            name='carencia',
            field=models.IntegerField(null=True, verbose_name='Carência (dias)'),
        ),
        migrations.AddField(
            model_name='planos',
            name='codigo_operacao',
            field=models.CharField(max_length=300, null=True, verbose_name='Código de Operação'),
        ),
        migrations.AddField(
            model_name='planos',
            name='codigo_plano',
            field=models.CharField(max_length=300, null=True, verbose_name='Código do Plano'),
        ),
        migrations.AddField(
            model_name='planos',
            name='codigo_produto',
            field=models.CharField(max_length=300, null=True, verbose_name='Código do Produto'),
        ),
        migrations.AddField(
            model_name='planos',
            name='iof',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='IOF (%)'),
        ),
        migrations.AddField(
            model_name='planos',
            name='obrigatorio',
            field=models.IntegerField(choices=[(1, 'SIM'), (0, 'NÃO')], default=None, verbose_name='Plano obrigatório?'),
        ),
        migrations.AddField(
            model_name='planos',
            name='porcentagem_premio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Porcentagem do prémio com base no limite do cartão'),
        ),
        migrations.AddField(
            model_name='planos',
            name='possui_termo_contratacao',
            field=models.IntegerField(choices=[(1, 'SIM'), (0, 'NÃO')], default=None, verbose_name='Possui termo de contratação?'),
        ),
        migrations.AddField(
            model_name='planos',
            name='quantidade_parcelas',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de Parcelas'),
        ),
        migrations.AddField(
            model_name='planos',
            name='renovacao_automatica',
            field=models.IntegerField(choices=[(1, 'SIM'), (0, 'NÃO')], default=None, verbose_name='Renovação Automática?'),
        ),
        migrations.AddField(
            model_name='planos',
            name='tipo_plano',
            field=models.SmallIntegerField(choices=[(1, 'Prata'), (2, 'Ouro'), (3, 'Diamante')], null=True, verbose_name='Tipo de Plano'),
        ),
        migrations.AddField(
            model_name='planos',
            name='valor_pago_cliente',
            field=models.CharField(blank=True, default=0, max_length=12, null=True, verbose_name='Valor Pago pelo Cliente (R$)'),
        ),
        migrations.AddField(
            model_name='planos',
            name='valor_segurado',
            field=models.CharField(blank=True, default=0, max_length=12, null=True, verbose_name='Valor Segurado (R$)'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='descricao_plano',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes'),
        ),
        migrations.CreateModel(
            name='Seguros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convenio_seguro', to='cartao_beneficio.convenios', verbose_name='Convênio')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_seguro', to='cartao_beneficio.planos', verbose_name='Plano')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_seguro', to='custom_auth.produtos', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Parâmetro – Plano',
                'verbose_name_plural': 'Parâmetros – Planos',
            },
        ),
        migrations.AddField(
            model_name='planos',
            name='seguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cartao_beneficio.seguradoras', verbose_name='Seguradora'),
        ),
    ]
