# Generated by Django 4.2.3 on 2023-10-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0032_seguradoras_remove_planos_valor_plano_planos_apolice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planos',
            name='codigo_ramo',
            field=models.CharField(max_length=300, null=True, verbose_name='Código Ramo'),
        ),
        migrations.AddField(
            model_name='planos',
            name='codigo_sucursal',
            field=models.CharField(max_length=300, null=True, verbose_name='Código Sucursal'),
        ),
        migrations.AlterField(
            model_name='seguradoras',
            name='nome',
            field=models.SmallIntegerField(choices=[(1, 'Tem Saúde'), (2, 'Generali')], null=True, verbose_name='Nome'),
        ),
    ]
