# Generated by Django 4.2.3 on 2023-10-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0032_seguradoras_remove_planos_valor_plano_planos_apolice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenios',
            name='percentual_saque',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Percentual do limite para o Saque Rotativo e/ou Parcelado'),
        ),
    ]
