# Generated by Django 4.2.3 on 2023-10-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0033_alter_convenios_percentual_saque'),
        ('cartao_beneficio', '0033_planos_codigo_ramo_planos_codigo_sucursal_and_more'),
    ]

    operations = [
    ]
