# Generated by Django 4.2.3 on 2023-10-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0034_merge_20231009_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planos',
            name='apolice',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Apólice'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='carencia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Carência (dias)'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='codigo_operacao',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Código de Operação'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='codigo_plano',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Código do Plano'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='codigo_produto',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Código do Produto'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='codigo_ramo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Código Ramo'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='codigo_sucursal',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Código Sucursal'),
        ),
        migrations.AlterField(
            model_name='seguradoras',
            name='nome',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Tem Saúde'), (2, 'Generali')], null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='seguradoras',
            name='senha_seguro',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='seguradoras',
            name='tipo_comunicacao',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Arquivo'), (2, 'API')], null=True, verbose_name='Tipo de Comunicação'),
        ),
        migrations.AlterField(
            model_name='seguradoras',
            name='url_api',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='URL API'),
        ),
        migrations.AlterField(
            model_name='seguradoras',
            name='url_arquvio',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='URL Arquivo'),
        ),
        migrations.AlterField(
            model_name='seguradoras',
            name='usuario_seguro',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Usuário'),
        ),
    ]
