# Generated by Django 4.2.3 on 2023-10-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0036_alter_seguros_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='aviso_reducao_margem',
            field=models.BooleanField(default=False, verbose_name='Aviso de redução de margem ativo?'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='horario_func_ativo',
            field=models.BooleanField(default=False, verbose_name='Horário de funcionamento ativo?'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='horario_func_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de fim de funcionamento'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='horario_func_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de início de funcionamento'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='porcentagem_reducao_margem',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Porcentagem aceita para redução da margem'),
        ),
    ]
