# Generated by Django 4.2.3 on 2023-10-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0038_alter_especiebeneficioinss_convenio_tipovinculosiape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='id_imagem_dock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id Imagem'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='id_plastico_dock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id Plastico'),
        ),
    ]
