# Generated by Django 4.2.3 on 2023-10-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0039_convenios_id_imagem_dock_convenios_id_plastico_dock'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='idade_minima_assinatura',
            field=models.IntegerField(blank=True, null=True, verbose_name='Idade mínima para a obrigatoriedade da assinatura'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='necessita_assinatura_fisica',
            field=models.BooleanField(default=False, verbose_name='Necessita assinatura física dos termos de contratação?'),
        ),
    ]
