# Generated by Django 4.2.3 on 2023-11-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0041_remove_convenios_cet_aa_remove_convenios_cet_am_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoconvenio',
            name='margem_compra',
        ),
        migrations.RemoveField(
            model_name='produtoconvenio',
            name='margem_saque',
        ),
        migrations.RemoveField(
            model_name='produtoconvenio',
            name='margem_unificada',
        ),
        migrations.AddField(
            model_name='produtoconvenio',
            name='tipo_margem',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Margem Compra'), (2, 'Margem Saque'), (3, 'Margem Unica')], null=True, verbose_name='Tipo Margem'),
        ),
    ]
