# Generated by Django 4.2.3 on 2023-11-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0042_remove_produtoconvenio_margem_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='cod_convenio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Convênio (Neoconsig)'),
        ),
        migrations.AlterField(
            model_name='convenios',
            name='averbadora',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Facil'), (2, 'Zetrasoft'), (3, 'Quantum'), (4, 'Dataprev - BRB'), (5, 'Dataprev - PINE'), (6, 'Serpro'), (7, 'Neoconsig')], null=True, verbose_name='Averbadora'),
        ),
    ]
