# Generated by Django 4.2.3 on 2023-11-30 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0131_cartaobeneficio_folha_compra_and_more'),
        ('cartao_beneficio', '0043_convenios_cod_convenio_alter_convenios_averbadora'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAverbacaoINSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField()),
            ],
            options={
                'verbose_name': '4. Averbação INSS',
                'verbose_name_plural': '4. Averbação INSS',
            },
        ),
        migrations.RemoveField(
            model_name='planos',
            name='valor_pago_cliente',
        ),
        migrations.AddField(
            model_name='convenios',
            name='permite_unificar_margem',
            field=models.BooleanField(default=False, verbose_name='Permite unificação de margem?'),
        ),
        migrations.AlterField(
            model_name='classificacaosiape',
            name='convenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convenio_classificacao_siape', to='cartao_beneficio.convenios', verbose_name='Convênio'),
        ),
        migrations.AlterField(
            model_name='conveniosiape',
            name='convenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convenio_convenio_siape', to='cartao_beneficio.convenios', verbose_name='Convênio'),
        ),
        migrations.AlterField(
            model_name='produtoconvenio',
            name='tipo_margem',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Margem Compra'), (2, 'Margem Saque'), (3, 'Margem Unica'), (4, 'Margem Unificada')], null=True, verbose_name='Tipo Margem'),
        ),
        migrations.CreateModel(
            name='PlanosContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_plano', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor pago cliente (R$)')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_planos_contratados', to='contract.contrato', verbose_name='Contrato')),
                ('plano', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='plano_contrato_contratado', to='cartao_beneficio.planos', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
    ]
