# Generated by Django 4.2.3 on 2023-11-30 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0044_logaverbacaoinss_remove_planos_valor_pago_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegrasIdade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade_minima', models.IntegerField(default=0, verbose_name='Idade mínima')),
                ('idade_maxima', models.IntegerField(default=100, verbose_name='Idade máxima')),
                ('limite_maximo_credito', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='Limite máximo de crédito')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('tipo_vinculo_siape', models.SmallIntegerField(blank=True, choices=[(1, 'Servidor'), (2, 'Pencionista')], null=True, verbose_name='Tipo de Vinculo - SIAPE')),
                ('convenio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cartao_beneficio.convenios', verbose_name='Convênio')),
            ],
            options={
                'verbose_name': 'Regra de Idade',
                'verbose_name_plural': 'Regras de Idade',
            },
        ),
        migrations.DeleteModel(
            name='LimiteDeCredito',
        ),
    ]
