# Generated by Django 4.2.3 on 2023-12-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0045_regrasidade_delete_limitedecredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='planos',
            name='porcentagem_premio_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Porcentagem do prémio LIQUIDO com base no limite do cartão'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='porcentagem_premio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Porcentagem do prémio BRUTO com base no limite do cartão'),
        ),
    ]
