# Generated by Django 4.2.3 on 2023-12-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0045_regrasidade_delete_limitedecredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='cod_convenio_zetra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Convenio (Apenas Zetra)'),
        ),
        migrations.AddField(
            model_name='produtoconvenio',
            name='verba',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Verba'),
        ),
    ]
