# Generated by Django 4.2.3 on 2023-12-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0046_convenios_cod_convenio_zetra_produtoconvenio_verba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoconvenio',
            name='verba',
        ),
        migrations.AddField(
            model_name='convenios',
            name='cliente_zetra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Convenio (Apenas Zetra)'),
        ),
        migrations.AddField(
            model_name='produtoconvenio',
            name='cod_servico_zetra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serviço (Apenas Zetra)'),
        ),
    ]
