# Generated by Django 4.2.3 on 2023-12-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0046_planos_porcentagem_premio_liquido_and_more'),
        ('cartao_beneficio', '0047_remove_produtoconvenio_verba_convenios_cliente_zetra_and_more'),
    ]

    operations = [
    ]
