# Generated by Django 4.2.3 on 2023-12-06 14:04

import contract.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0048_merge_20231206_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='planos',
            name='tipo_termo',
            field=models.SmallIntegerField(choices=[(contract.constants.EnumArquivosSeguros['VIDA_SIAPE'], 'Termo Vida - Siape'), (contract.constants.EnumArquivosSeguros['VIDA_INSS'], 'Termo Vida - INSS'), (contract.constants.EnumArquivosSeguros['OURO_INSS'], 'Termo Ouro - INSS'), (contract.constants.EnumArquivosSeguros['DIAMANTE_INSS'], 'Termo Diamanete - INSS'), (contract.constants.EnumArquivosSeguros['OURO_DEMAIS_CONVENIOS'], 'Termo Ouro - Demais Convênios'), (contract.constants.EnumArquivosSeguros['DIAMANTE_DEMAIS_CONVENIOS'], 'Termo Diamante - Demais Convênios')], null=True, verbose_name='Tipo de Termo'),
        ),
    ]
