# Generated by Django 4.2.3 on 2023-12-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0049_planos_tipo_termo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planos',
            name='gratuito',
            field=models.IntegerField(choices=[(1, 'SIM'), (0, 'NÃO')], default=None, verbose_name='Plano gratuito?'),
        ),
    ]
