# Generated by Django 4.2.3 on 2023-12-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0050_planos_gratuito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planos',
            name='tipo_termo',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Termo Vida - Siape'), (2, 'Termo Vida - INSS'), (3, 'Termo Ouro - INSS'), (4, 'Termo Diamanete - INSS'), (5, 'Termo Ouro - Demais Convênios'), (6, 'Termo Diamante - Demais Convênios')], null=True, verbose_name='Tipo de Termo'),
        ),
    ]
