# Generated by Django 4.2.3 on 2023-12-14 19:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0051_alter_planos_tipo_termo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planos',
            name='descricao_plano',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Detalhes'),
        ),
    ]
