# Generated by Django 4.2.3 on 2023-12-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0052_alter_planos_descricao_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='especiebeneficioinss',
            name='idade_maxima',
            field=models.IntegerField(default=100, verbose_name='Idade máxima'),
        ),
        migrations.AddField(
            model_name='especiebeneficioinss',
            name='idade_minima',
            field=models.IntegerField(default=0, verbose_name='Idade mínima'),
        ),
    ]
