# Generated by Django 4.2.3 on 2023-12-28 20:36

import contract.products.cartao_beneficio.validators.validate_characters
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0053_especiebeneficioinss_idade_maxima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='derivacao_mesa_averbacao',
            field=models.BooleanField(default=False, verbose_name='Derivação Mesa de Averbação'),
        ),
        migrations.AddField(
            model_name='regrasidade',
            name='fator',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Fator de multiplicação'),
        ),
        migrations.AddField(
            model_name='regrasidade',
            name='grupo_parcelas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='Grupo de Parcelas'),
        ),
        migrations.AddField(
            model_name='regrasidade',
            name='grupo_parcelas_2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='Grupo de Parcelas'),
        ),
        migrations.AddField(
            model_name='regrasidade',
            name='grupo_parcelas_3',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='Grupo de Parcelas'),
        ),
        migrations.AddField(
            model_name='regrasidade',
            name='grupo_parcelas_4',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='Grupo de Parcelas'),
        ),
        migrations.AddField(
            model_name='regrasidade',
            name='limite_minimo_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Limite mínimo de crédito'),
        ),
        migrations.AddField(
            model_name='regrasidade',
            name='produto',
            field=models.SmallIntegerField(blank=True, choices=[(7, 'Cartão Benefício'), (15, 'Cartão Consignado')], null=True, validators=[contract.products.cartao_beneficio.validators.validate_characters.validate_tipo_produto], verbose_name='Tipo de Produto'),
        ),
        migrations.AlterField(
            model_name='regrasidade',
            name='idade_maxima',
            field=models.IntegerField(default=100, validators=[contract.products.cartao_beneficio.validators.validate_characters.validate_max_length], verbose_name='Idade máxima'),
        ),
        migrations.AlterField(
            model_name='regrasidade',
            name='idade_minima',
            field=models.IntegerField(default=0, validators=[contract.products.cartao_beneficio.validators.validate_characters.validate_max_length], verbose_name='Idade mínima'),
        ),
        migrations.AlterField(
            model_name='regrasidade',
            name='limite_maximo_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Limite máximo de crédito'),
        ),
    ]
