# Generated by Django 4.2.3 on 2024-01-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0056_alter_seguradoras_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoscontrato',
            name='numero_sorte',
            field=models.CharField(blank=True, default=0, max_length=12, null=True, verbose_name='Numero de sorteio seguro'),
        ),
    ]
