# Generated by Django 4.2.3 on 2024-01-19 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('cartao_beneficio', '0057_planoscontrato_numero_sorte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planos',
            name='seguradora',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='cartao_beneficio.seguradoras',
                verbose_name='Seguradora',
            ),
        ),
    ]
