# Generated by Django 4.2.3 on 2024-01-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0058_alter_planos_seguradora'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='permite_saque_complementar',
            field=models.BooleanField(default=False, verbose_name='Permite Saque Complementar?'),
        ),
    ]
