# Generated by Django 4.2.3 on 2024-02-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0059_convenios_permite_saque_complementar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborgao',
            name='codigo_folha',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código Folha'),
        ),
    ]
