# Generated by Django 4.2.3 on 2024-02-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_beneficio', '0060_alter_suborgao_codigo_folha'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='fixar_valor_maximo',
            field=models.BooleanField(default=False, verbose_name='Fixar valor máximo de saque ?'),
        ),
        migrations.AlterField(
            model_name='convenios',
            name='digitacao_manual',
            field=models.BooleanField(default=False, verbose_name='Permite digitação manual de contrato ?'),
        ),
        migrations.AlterField(
            model_name='convenios',
            name='permite_saque_complementar',
            field=models.BooleanField(default=False, verbose_name='Permite Saque Complementar ?'),
        ),
        migrations.AlterField(
            model_name='convenios',
            name='permite_unificar_margem',
            field=models.BooleanField(default=False, verbose_name='Permite unificação de margem ?'),
        ),
        migrations.AlterField(
            model_name='convenios',
            name='senha_servidor',
            field=models.BooleanField(default=False, verbose_name='Solicita Senha Servidor ?'),
        ),
    ]
