# Generated by Django 4.2.2 on 2023-06-30 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroLojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cadastro de Loja',
                'verbose_name_plural': '4. Cadastro de Lojas',
            },
        ),
        migrations.CreateModel(
            name='RepresentanteComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('nu_cpf_cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Número de CPF/CNPJ')),
                ('dt_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='DDD + número com 9 dígitos')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='E-mail Corporativo')),
                ('cargo', models.SmallIntegerField(blank=True, choices=[(1, 'Agente'), (2, 'Gerente'), (3, 'Superintendente')], null=True, verbose_name='Cargo')),
                ('tipo_atuacao', models.SmallIntegerField(blank=True, choices=[(1, 'Regional'), (2, 'Distrital')], null=True, verbose_name='Tipo de Atuação')),
            ],
            options={
                'verbose_name': 'Cadastro de Representante Comercial',
                'verbose_name_plural': '3. Cadastro de Representantes Comerciais',
            },
        ),
        migrations.CreateModel(
            name='VinculoProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Vínculo de Produto',
                'verbose_name_plural': '5. Vínculo de Produtos',
            },
        ),
        migrations.CreateModel(
            name='Superintendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_direto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Supervisor Direto')),
                ('representante_comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_comercial.representantecomercial', verbose_name='Representante Comercial')),
            ],
            options={
                'verbose_name': 'Responsável Direto',
                'verbose_name_plural': 'Responsável Direto',
            },
        ),
        migrations.CreateModel(
            name='LocalAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.SmallIntegerField(blank=True, choices=[(1, 'Norte'), (2, 'Nordeste'), (3, 'Centro-Oeste'), (4, 'Sul'), (5, 'Sudeste')], null=True, verbose_name='Região')),
                ('estado', models.SmallIntegerField(blank=True, choices=[(1, 'AC'), (2, 'AL'), (3, 'AP'), (4, 'AM'), (5, 'BA'), (6, 'CE'), (7, 'DF'), (8, 'ES'), (9, 'GO'), (10, 'MA'), (11, 'MT'), (12, 'MS'), (13, 'MG'), (14, 'PA'), (15, 'PB'), (16, 'PR'), (17, 'PE'), (18, 'PI'), (19, 'RJ'), (20, 'RN'), (21, 'RS'), (22, 'RO'), (23, 'RR'), (24, 'SC'), (25, 'SP'), (26, 'SE'), (27, 'TO')], null=True, verbose_name='Estado')),
                ('municipio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Município')),
                ('representante_comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_comercial.representantecomercial', verbose_name='Representante Comercial')),
            ],
            options={
                'verbose_name': 'Locais de Atuação',
                'verbose_name_plural': 'Locais de Atuação',
            },
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representante_comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_comercial.representantecomercial', verbose_name='Representante Comercial')),
                ('supervisor_direto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_comercial.superintendente', verbose_name='Supervisor Direto')),
            ],
            options={
                'verbose_name': 'Responsável Direto',
                'verbose_name_plural': 'Responsável Direto',
            },
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representante_comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_comercial.representantecomercial', verbose_name='Representante Comercial')),
                ('supervisor_direto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_comercial.gerente', verbose_name='Supervisor Direto')),
            ],
            options={
                'verbose_name': 'Responsável Direto',
                'verbose_name_plural': 'Responsável Direto',
            },
        ),
    ]
