# Generated by Django 4.2.2 on 2023-07-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastrolojas',
            options={'verbose_name': 'Cadastro de Loja', 'verbose_name_plural': '2. Cadastro de Lojas'},
        ),
        migrations.AlterModelOptions(
            name='representantecomercial',
            options={'verbose_name': 'Cadastro de Representante Comercial', 'verbose_name_plural': '1. Cadastro de Representantes Comerciais'},
        ),
        migrations.AlterModelOptions(
            name='vinculoprodutos',
            options={'verbose_name': 'Vínculo de Produto', 'verbose_name_plural': '3. Vínculo de Produtos'},
        ),
    ]
