# Generated by Django 4.2.2 on 2023-07-03 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_comercial', '0002_alter_cadastrolojas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastrolojas',
            options={'verbose_name': 'Cadastro de Corban/Loja', 'verbose_name_plural': '2. Cadastro de Corban/Lojas'},
        ),
        migrations.AddField(
            model_name='cadastrolojas',
            name='agencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número da agência'),
        ),
        migrations.AddField(
            model_name='cadastrolojas',
            name='banco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número do banco'),
        ),
        migrations.AddField(
            model_name='cadastrolojas',
            name='conta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número da conta'),
        ),
        migrations.AddField(
            model_name='cadastrolojas',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='cadastrolojas',
            name='endereco',
            field=models.CharField(max_length=200, null=True, verbose_name='Endereço Completo'),
        ),
        migrations.AddField(
            model_name='cadastrolojas',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='cadastrolojas',
            name='loja_matriz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número da Loja Matriz'),
        ),
        migrations.AddField(
            model_name='cadastrolojas',
            name='mesa_corban',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Mesa Corban'),
        ),
        migrations.AddField(
            model_name='cadastrolojas',
            name='nu_cpf_cnpj',
            field=models.CharField(blank=True, max_length=14, unique=True, verbose_name='Número de CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='cadastrolojas',
            name='representante_comercial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_comercial.representantecomercial', verbose_name='Representante Comercial'),
        ),
        migrations.AddField(
            model_name='cadastrolojas',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='DDD + número com 9 dígitos'),
        ),
        migrations.AddField(
            model_name='cadastrolojas',
            name='tipo_cadastro',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Matriz'), (2, 'Subsidiária'), (3, 'Subestabelecimento')], null=True, verbose_name='Tipo de Cadastro'),
        ),
        migrations.AddField(
            model_name='cadastrolojas',
            name='tipo_estabelecimento',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Virtual'), (2, 'Físico')], null=True, verbose_name='Tipo de Estabelecimento'),
        ),
        migrations.AddField(
            model_name='cadastrolojas',
            name='tipo_relacionamento',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Proprietário'), (2, 'Representante Legal'), (3, 'Representante Autorizado')], null=True, verbose_name='Tipo de Relacionamento'),
        ),
        migrations.AddField(
            model_name='cadastrolojas',
            name='tipo_venda',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'B2C - Direto ao Cliente'), (2, 'B2B2C - Comercial')], null=True, verbose_name='Tipo de Venda'),
        ),
        migrations.AlterField(
            model_name='cadastrolojas',
            name='nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome Completo'),
        ),
    ]
