# Generated by Django 4.2.2 on 2023-07-06 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_comercial', '0004_alter_representantecomercial_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representantecomercial',
            name='dt_nascimento',
        ),
        migrations.AlterField(
            model_name='agente',
            name='representante_comercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_comercial.representantecomercial', verbose_name='Representante Comercial'),
        ),
        migrations.AlterField(
            model_name='gerente',
            name='representante_comercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_comercial.representantecomercial', verbose_name='Representante Comercial'),
        ),
        migrations.AlterField(
            model_name='localatuacao',
            name='regiao',
            field=models.SmallIntegerField(choices=[(1, 'Norte'), (2, 'Nordeste'), (3, 'Centro-Oeste'), (4, 'Sul'), (5, 'Sudeste')], verbose_name='Região'),
        ),
        migrations.AlterField(
            model_name='superintendente',
            name='representante_comercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_comercial.representantecomercial', verbose_name='Representante Comercial'),
        ),
    ]
