# Generated by Django 4.2.2 on 2023-07-18 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_comercial', '0005_remove_representantecomercial_dt_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localatuacao',
            name='estado',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'AC'), (2, 'AL'), (3, 'AP'), (4, 'AM'), (5, 'BA'), (6, 'CE'), (7, 'DF'), (8, 'ES'), (9, 'GO'), (10, 'MA'), (11, 'MT'), (12, 'MS'), (13, 'MG'), (14, 'PA'), (15, 'PB'), (16, 'PR'), (17, 'PE'), (18, 'PI'), (19, 'RJ'), (20, 'RN'), (21, 'RS'), (22, 'RO'), (23, 'RR'), (24, 'SC'), (25, 'SP'), (26, 'SE'), (27, 'TO')], null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='localatuacao',
            name='municipio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='localatuacao',
            name='regiao',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Norte'), (2, 'Nordeste'), (3, 'Centro-Oeste'), (4, 'Sul'), (5, 'Sudeste'), (0, '-------')], null=True, verbose_name='Região'),
        ),
        migrations.AlterField(
            model_name='localatuacao',
            name='representante_comercial',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_comercial.representantecomercial', verbose_name='Representante Comercial'),
        ),
        migrations.AlterField(
            model_name='representantecomercial',
            name='tipo_atuacao',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Regional'), (2, 'Distrital')], null=True, verbose_name='Tipo de Atuação'),
        ),
    ]
