# Generated by Django 4.2.2 on 2023-07-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_comercial', '0006_alter_localatuacao_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrolojas',
            name='representante_comercial',
        ),
        migrations.DeleteModel(
            name='VinculoProdutos',
        ),
        migrations.DeleteModel(
            name='CadastroLojas',
        ),
    ]
