from enum import Enum


class EnumContaTipo(Enum):
    CONTACORRENTEPESSOALFISICA = 1
    CONTACORRENTEPESSOALJURIDICA = 2
    CONTAPOUPANCAPESSOALFISICA = 3
    CARTAOMAGNETICO = 4
    CONTAPAGAMENTOPESSOALFISICA = 5


class EnumParametroSistema(Enum):
    DIAS_LIMITE_PARA_DESEMBOLSO = 1
    DIAS_LIMITE_PARA_DESEMBOLSO_AUMENTO_SALARIAL = 2
    VALOR_MINIMO_PARCELA = 3
    QUANTIDADE_DIAS_UTEIS_BASE_SIMULACAO = 4
    MESES_PARA_ADICIONAR_QUANDO_DIAS_UTEIS_MENOR_IGUAL_BASE = 5
    MESES_PARA_ADICIONAR_QUANDO_DIAS_UTEIS_MAIOR_BASE = 5
    DIA_VENCIMENTO_PADRAO_SIMULACAO = 6
    VALOR_LIBERADO_CLIENTE_OPERACAO_MIN = 7
    VALOR_LIBERADO_CLIENTE_OPERACAO_MAX = 8
