from enum import Enum


class StatusAccountDock(Enum):
    NORMAL = 0
    BLOQUEADO = 1
    CANCELADO = 2
    BLOQUEADO_POR_FALTA_PAGAMENTO = 3
    BLOQUEADO_POR_EXCEDER_LIMITE = 4
    BLOQUEADO_POR_REGISTRO_INCORRETO = 5
    CANCELADO_CLIENTE = 6
    CANCELADO_MANUAL = 7
    CRELIQ = 8
    PERDA = 9
    LANCADO = 10
    CANCELADO_CPF_ALTERADO = 11
    CANCELADO_OBITO_TITULAR = 14
    ACORDO_CRELIQ = 15
    BLOQUEADO_CHEQUE_SEM_FUNDO = 20
    ACORDO_ESCRITORIO_COBRANCA = 21
    ACORDO_PERDA = 26
    REMOCAO = 27
    DEMISSAO = 28
    PERDA_MARGEM = 29
    ACAO_LEGAL = 30
    LICENCA_MATERNIDADE = 31
    BLOQUEADO_PREVENCAO = 33
    CANCELADO_DEFINITIVAMENTE_FRAUDE = 34
    PARCEIRO_BLOQUEADO = 35
    SALDO_RECUPERAVEL_PRE_PAGO = 109
    CONTA_NAO_ATIVADA = 200
    CANCELAMENTO_DEFINITIVO_AML = 201


class StatusCardDock(Enum):
    NORMAL_DESBLOQUEADO = 1
    BLOQUEADO_PODE_SER_REVERTIDO = 2
    CANCELADO_NAO_PODE_SER_REVERTIDO = 3
    CANCELADO_EXTRAVIADO = 8
    CANCELADO_DANIFICADO = 9
    CANCELADO_TARJA = 10
    CANCELADO_EMBOSSING = 11
    CANCELADO_NAO_PODE_SER_REVERTIDO_2 = 17
    MIGRADO = 18
    MIGRADO_2 = 19
    CANCELADO_DEFINITIVO = 20
    CANCELADO_DEFINITIVO_2 = 24
    MIGRADO_BLOQUEADO = 25
    MIGRADO_BLOQUEADO_2 = 26
    REEMITIDO = 27
    CANCELADO_DEFINITIVO_REEMITIDO = 28
    BLOQUEADO_SENHA_INCORRETA = 29
    CANCELADO_NAO_GEROU_CVV_CVV2 = 30
    SUSPEITA_FRAUDE = 32
    BLOQUEADO_PREVENTIVO = 27
    PREVENCAO_LAVAGEM_DINHEIRO = 171
