# Generated by Django 4.1.3 on 2023-04-22 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_cliente_dt_nascimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Log - Consulta Cliente Log',
                'verbose_name_plural': 'Log - Consulta Clientes Logs',
            },
        ),
        migrations.CreateModel(
            name='TemSaudeAdesao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Cliente')),
                ('tipo_servico', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Servico')),
                ('payload', models.TextField(blank=True, null=True, verbose_name='Payload de Resposta')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('log_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_log.logcliente', verbose_name='Log_Cliente')),
            ],
            options={
                'verbose_name': 'Log - Tem Saude',
                'verbose_name_plural': 'Logs - Tem Saude',
            },
        ),
        migrations.CreateModel(
            name='RetornosDock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.CharField(blank=True, max_length=15, null=True, verbose_name='Id cliente - Dock')),
                ('nome_chamada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da chamada')),
                ('payload', models.TextField(blank=True, null=True, verbose_name='Payload de retorno')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('codigo_retorno', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código de retorno')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('log_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_log.logcliente', verbose_name='Log_Cliente')),
            ],
            options={
                'verbose_name': 'Log - Resposta - Dock',
                'verbose_name_plural': 'Log - Respostas - Dock',
            },
        ),
        migrations.CreateModel(
            name='RetornoCallbackUnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, null=True, verbose_name='nome do retorno')),
                ('payload', models.TextField(blank=True, null=True, verbose_name='Payload de retorno')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('log_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_log.logcliente', verbose_name='Log_Cliente')),
            ],
            options={
                'verbose_name': 'Log - Callback Unico',
                'verbose_name_plural': 'Logs - Callback - Unico',
            },
        ),
        migrations.CreateModel(
            name='RealizaSimulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=15, null=True, verbose_name='Matrícula')),
                ('convenio', models.IntegerField(blank=True, null=True, verbose_name='Código do convênio')),
                ('taxa', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Taxa')),
                ('cet_am', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Taxa CET a.m')),
                ('cet_aa', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Taxa CET a.a')),
                ('valor_iof', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Valor IOF')),
                ('valor_disponivel_saque', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Valor disponível para saque')),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Valor da parcela')),
                ('valor_saque', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True, verbose_name='Valor do saque')),
                ('valor_financiado', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Valor Financiado')),
                ('limite_pre_aprovado', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True, verbose_name='Valor do limite pré-aprovado')),
                ('saque', models.BooleanField(default=True, verbose_name='Possui saque?')),
                ('seguro', models.BooleanField(default=True, verbose_name='Possui seguro?')),
                ('taxa_seguro', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Taxa do seguro prestamista')),
                ('reservado', models.BooleanField(default=False, verbose_name='Reservado?')),
                ('averbado', models.BooleanField(default=False, verbose_name='Averbado?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('log_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_log.logcliente', verbose_name='Log_Cliente')),
            ],
            options={
                'verbose_name': 'Log - Realizar simulaçao',
                'verbose_name_plural': 'Log - Realiza simulações',
            },
        ),
        migrations.CreateModel(
            name='RealizaReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=15, null=True, verbose_name='Matrícula')),
                ('folha', models.CharField(blank=True, max_length=10, null=True, verbose_name='Folha')),
                ('verba', models.CharField(blank=True, max_length=15, null=True, verbose_name='Verba')),
                ('valor', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Valor')),
                ('reserva', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número da Reserva')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('codigo_retorno', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código de retorno')),
                ('descricao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('log_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_log.logcliente', verbose_name='Log_Cliente')),
            ],
            options={
                'verbose_name': 'Log - Realizar reserva',
                'verbose_name_plural': 'Log - Realiza reservas ',
            },
        ),
        migrations.CreateModel(
            name='ConsultaMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=45, null=True, verbose_name='Matrícula')),
                ('folha', models.CharField(blank=True, max_length=10, null=True, verbose_name='Folha')),
                ('verba', models.CharField(blank=True, max_length=15, null=True, verbose_name='Verba')),
                ('tipo_margem', models.CharField(blank=True, max_length=40, null=True, verbose_name='Tipo Margem')),
                ('margem_atual', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Margem atual')),
                ('cargo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cargo')),
                ('estavel', models.BooleanField(default=False, verbose_name='Estável')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('log_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_log.logcliente', verbose_name='Log_Cliente')),
            ],
            options={
                'verbose_name': 'Log - Consulta Matrícula',
                'verbose_name_plural': 'Log - Consulta Matrícula',
            },
        ),
        migrations.CreateModel(
            name='ConsultaMargem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=15, null=True, verbose_name='Matrícula')),
                ('folha', models.CharField(blank=True, max_length=10, null=True, verbose_name='Folha')),
                ('verba', models.CharField(blank=True, max_length=15, null=True, verbose_name='Verba')),
                ('margem_atual', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Margem atual')),
                ('cargo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cargo')),
                ('estavel', models.BooleanField(default=False, verbose_name='Estável')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('codigo_retorno', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código de retorno')),
                ('descricao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('log_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_log.logcliente', verbose_name='Log_Cliente')),
            ],
            options={
                'verbose_name': 'Log - Consulta Margem',
                'verbose_name_plural': 'Log - Consulta Margens',
            },
        ),
        migrations.CreateModel(
            name='ConsultaConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_folha', models.CharField(blank=True, max_length=25, null=True, verbose_name='Código folha')),
                ('descricao_folha', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descricao folha')),
                ('periodo_atual', models.IntegerField(blank=True, null=True, verbose_name='Período atual')),
                ('verba', models.IntegerField(blank=True, null=True, verbose_name='Verba')),
                ('autorizacao', models.BooleanField(default=False, verbose_name='Requer autorização?')),
                ('cet_maximo', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='CET máximo')),
                ('descricao_margem', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição da margem')),
                ('descricao_modalidade', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição da modalidade')),
                ('validade_reserva', models.IntegerField(blank=True, null=True, verbose_name='Validade da reserva')),
                ('codigo_retorno', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código de retorno')),
                ('descricao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('log_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_log.logcliente', verbose_name='Log_Cliente')),
            ],
            options={
                'verbose_name': 'Log - Consulta Convênio',
                'verbose_name_plural': 'Log - Consulta Convênios',
            },
        ),
        migrations.CreateModel(
            name='ConsultaConsignacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_operacao', models.CharField(blank=True, max_length=25, null=True, verbose_name='Código da operação')),
                ('prazo', models.IntegerField(blank=True, null=True, verbose_name='Prazo')),
                ('valor', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Valor')),
                ('valor_liberado', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Valor liberado')),
                ('codigo_operacao_instituicao', models.CharField(blank=True, max_length=25, null=True, verbose_name='Código da operação na instituição')),
                ('verba', models.CharField(blank=True, max_length=15, null=True, verbose_name='Verba')),
                ('prazo_restante', models.CharField(blank=True, max_length=15, null=True, verbose_name='Verba')),
                ('data_consignacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Consignação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('codigo_retorno', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código de retorno')),
                ('descricao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('log_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_log.logcliente', verbose_name='Log_Cliente')),
            ],
            options={
                'verbose_name': 'Log - Consulta Consignação',
                'verbose_name_plural': 'Log - Consulta Consignações',
            },
        ),
        migrations.CreateModel(
            name='ConsultaBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField(blank=True, null=True, verbose_name='Payload de retorno')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('codigo_retorno', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código de retorno')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('log_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_log.logcliente', verbose_name='Log_Cliente')),
            ],
            options={
                'verbose_name': 'Log - Consulta Bureau - DXON',
                'verbose_name_plural': 'Log - Consulta Bureau - DXON',
            },
        ),
        migrations.CreateModel(
            name='CancelaReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=15, null=True, verbose_name='Matrícula')),
                ('cancelada', models.BooleanField(default=False, verbose_name='Reserva cancelada?')),
                ('reserva', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número da Reserva')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('codigo_retorno', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código de retorno')),
                ('descricao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('log_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_log.logcliente', verbose_name='Log_Cliente')),
            ],
            options={
                'verbose_name': 'Log - Cancelar reserva',
                'verbose_name_plural': 'Log - Cancelar reservas ',
            },
        ),
        migrations.CreateModel(
            name='Averbacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=15, null=True, verbose_name='Matrícula')),
                ('folha', models.CharField(blank=True, max_length=10, null=True, verbose_name='Folha')),
                ('verba', models.CharField(blank=True, max_length=15, null=True, verbose_name='Verba')),
                ('cancelada', models.BooleanField(default=False, verbose_name='Reserva cancelada?')),
                ('valor', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Valor')),
                ('contrato', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número do Contrato')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('codigo_retorno', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código de retorno')),
                ('descricao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('log_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_log.logcliente', verbose_name='Log_Cliente')),
            ],
            options={
                'verbose_name': 'Log - Averbação',
                'verbose_name_plural': 'Log - Averbação',
            },
        ),
    ]
