# Generated by Django 4.1.3 on 2023-04-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averbacao',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='cancelareserva',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='consultabureau',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='consultaconsignacoes',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='consultaconvenio',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='consultamargem',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='consultamatricula',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='realizareserva',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='realizasimulacao',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='retornocallbackunico',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='retornosdock',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='temsaudeadesao',
            name='cliente',
        ),
    ]
