# Generated by Django 4.1.3 on 2023-04-25 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_log', '0003_alter_logcliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='averbacao',
            options={'verbose_name': 'Averbação', 'verbose_name_plural': 'Averbação'},
        ),
        migrations.AlterModelOptions(
            name='cancelareserva',
            options={'verbose_name': 'Cancelar reserva', 'verbose_name_plural': 'Cancelar reservas '},
        ),
        migrations.AlterModelOptions(
            name='consultabureau',
            options={'verbose_name': 'Consulta Bureau - DXON', 'verbose_name_plural': 'Consulta Bureau - DXON'},
        ),
        migrations.AlterModelOptions(
            name='consultaconsignacoes',
            options={'verbose_name': 'Consulta Consignação', 'verbose_name_plural': 'Consulta Consignações'},
        ),
        migrations.AlterModelOptions(
            name='consultaconvenio',
            options={'verbose_name': 'Consulta Convênio', 'verbose_name_plural': 'Consulta Convênios'},
        ),
        migrations.AlterModelOptions(
            name='consultamargem',
            options={'verbose_name': 'Consulta Margem', 'verbose_name_plural': 'Consulta Margens'},
        ),
        migrations.AlterModelOptions(
            name='consultamatricula',
            options={'verbose_name': 'Consulta Matrícula', 'verbose_name_plural': 'Consulta Matrícula'},
        ),
        migrations.AlterModelOptions(
            name='realizareserva',
            options={'verbose_name': 'Realizar reserva', 'verbose_name_plural': 'Realiza reservas '},
        ),
        migrations.AlterModelOptions(
            name='realizasimulacao',
            options={'verbose_name': 'Realizar simulaçao', 'verbose_name_plural': 'Realiza simulações'},
        ),
        migrations.AlterModelOptions(
            name='retornocallbackunico',
            options={'verbose_name': 'Callback Unico', 'verbose_name_plural': 'Callback - Unico'},
        ),
        migrations.AlterModelOptions(
            name='retornosdock',
            options={'verbose_name': 'Resposta - Dock', 'verbose_name_plural': 'Respostas - Dock'},
        ),
        migrations.AlterModelOptions(
            name='temsaudeadesao',
            options={'verbose_name': 'Tem Saude', 'verbose_name_plural': 'Tem Saude'},
        ),
    ]
