# Generated by Django 4.1.3 on 2023-04-26 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_parametrosbackoffice_tipoproduto'),
        ('api_log', '0004_alter_averbacao_options_alter_cancelareserva_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='averbacao',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='cancelareserva',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='consultabureau',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='consultaconsignacoes',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='consultaconvenio',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='consultamargem',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='consultamatricula',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='realizareserva',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='realizasimulacao',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='retornocallbackunico',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='retornosdock',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='temsaudeadesao',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente'),
        ),
    ]
