# Generated by Django 4.1.3 on 2023-05-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_log', '0005_averbacao_cliente_cancelareserva_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banksoft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Cliente')),
                ('contrato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contrato')),
                ('payload_enviado', models.TextField(blank=True, default=None, null=True, verbose_name='Payload enviado')),
                ('payload', models.TextField(blank=True, null=True, verbose_name='Payload de resposta')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Log - Banksoft',
                'verbose_name_plural': 'Logs - Banksoft',
            },
        ),
    ]
