# Generated by Django 4.1.3 on 2023-05-02 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_parametrosproduto_tipoproduto'),
        ('api_log', '0006_banksoft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banksoft',
            name='nome',
        ),
        migrations.AddField(
            model_name='banksoft',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='banksoft',
            name='log_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_log.logcliente', verbose_name='Log_Cliente'),
        ),
    ]
