# Generated by Django 4.1.3 on 2023-05-08 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_clienteinss_nome_beneficio_clienteinss_nu_beneficio_and_more"),
        ("api_log", "0007_remove_banksoft_nome_banksoft_cliente_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QitechRetornos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "retorno",
                    models.JSONField(blank=True, null=True, verbose_name="Retorno"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "log_api",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_log.logcliente",
                        verbose_name="Log_Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log - Retorno qitech",
                "verbose_name_plural": "Logs - Retornos qitech",
            },
        ),
    ]
