# Generated by Django 4.1.3 on 2023-05-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_log", "0008_qitechretornos"),
    ]

    operations = [
        migrations.AddField(
            model_name="qitechretornos",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Criado em"
            ),
        ),
    ]
