# Generated by Django 4.2.2 on 2023-06-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_log', '0010_qitechretornos_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='retornosdock',
            name='payload_envio',
            field=models.TextField(blank=True, null=True, verbose_name='Payload de envio'),
        ),
    ]
