# Generated by Django 4.2.2 on 2023-07-03 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_comercial', '0003_alter_cadastrolojas_options_cadastrolojas_agencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_log', '0014_logcomercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja', models.CharField(max_length=200, verbose_name='Nome do Corban/Loja')),
                ('cpf_cnpj', models.CharField(max_length=200, verbose_name='CPF/CNPJ do Corban/Loja')),
                ('tipo_cadastro', models.SmallIntegerField(blank=True, choices=[(1, 'Matriz'), (2, 'Subsidiária'), (3, 'Subestabelecimento')], null=True, verbose_name='Tipo de Cadastro')),
                ('operacao', models.CharField(max_length=20, verbose_name='Operação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('representante_comercial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_comercial.representantecomercial', verbose_name='Representante Comercial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log - Corban/Loja',
                'verbose_name_plural': 'Logs - Corban/Loja',
            },
        ),
    ]
