# Generated by Django 4.2.2 on 2023-07-26 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_aceitein100_token_in100'),
        ('api_log', '0015_logloja'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogIn100',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_envio', models.TextField(blank=True, null=True, verbose_name='Payload de envio')),
                ('payload', models.TextField(blank=True, null=True, verbose_name='Payload de retorno')),
                ('tipo_chamada', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo Chamada')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('log_api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_log.logcliente', verbose_name='Log_Cliente')),
            ],
            options={
                'verbose_name': 'Log - In100',
                'verbose_name_plural': 'Log - In100',
            },
        ),
    ]
