# Generated by Django 4.2.2 on 2023-08-01 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_aceitein100_dv_conta_corrente_aceitein100_ufaps_and_more'),
        ('api_log', '0016_login100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizareserva',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realiza_reserva_cliente', to='core.cliente', verbose_name='Cliente'),
        ),
    ]
