# Generated by Django 4.2.2 on 2023-08-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_log', '0018_alter_realizasimulacao_limite_pre_aprovado_and_more'),
        ('api_log', '0018_logenviodossie_logatualizacaocadastral'),
    ]

    operations = [
    ]
