# Generated by Django 4.2.2 on 2023-08-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_log', '0019_merge_20230808_1618'),
        ('api_log', '0019_merge_20230809_0819'),
        ('api_log', '0020_logtransferenciasaque'),
    ]

    operations = [
    ]
