# Generated by Django 4.2.3 on 2023-09-11 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_parametrosproduto_aprovar_automatico_and_more'),
        ('api_log', '0021_merge_20230810_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaAverbadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_chamada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo chamada')),
                ('payload_envio', models.TextField(blank=True, null=True, verbose_name='Payload de envio')),
                ('payload', models.TextField(blank=True, null=True, verbose_name='Payload de retorno')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('log_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_log.logcliente', verbose_name='Log_Cliente')),
            ],
            options={
                'verbose_name': 'Consulta Averbadora',
                'verbose_name_plural': 'Consulta Averbadora',
            },
        ),
    ]
