# Generated by Django 4.2.3 on 2024-01-03 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0080_backofficeconfigs'),
        ('api_log', '0022_consultaaverbadora'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCobrancaDock',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'status_cobranca',
                    models.CharField(
                        blank=True,
                        max_length=25,
                        null=True,
                        verbose_name='Status Cobrança',
                    ),
                ),
                (
                    'cliente',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='core.cliente',
                        verbose_name='Cliente',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Status Cobrança',
                'verbose_name_plural': 'Status Cobrança',
            },
        ),
    ]
