from .life_insurance_moneylender_diamond import (
    SabemiLifeInsuranceMoneyLenderDiamondTerm,
)
from .life_insurance_moneylender_gold import SabemiLifeInsuranceMoneyLenderGoldTerm
from .life_insurance_silver import SabemiLifeInsuranceSilverTerm
