from .arquivos_generali import ArquivoGenerali
from .backoffice_configs import BackofficeConfigs
from .bancos_brasileiros import BancosBrasileiros
from .beneficios_contratado import BeneficiosContratado
from .cliente import Cliente
from .dossie_inss import DossieINSS
from .parametros_backoffice import ParametrosBackoffice
from .parcela import Parcela
from .informativo_cancelamento import InformativoCancelamentoPlano
from .rogado import Rogado
from .testemunha import Testemunha
from .regra_teimosinha_inss import RegraTeimosinhaINSS
