# Generated by Django 4.2.3 on 2023-09-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET')], max_length=10)),
                ('url', models.URLField(max_length=500)),
                ('headers', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_content', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('can_access_apicaller', 'Can Access API Caller')],
            },
        ),
    ]
