# Generated by Django 4.2.3 on 2024-02-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_caller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicalllog',
            name='method',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PATCH', 'PATCH')], max_length=10),
        ),
    ]
