# Generated by Django 4.1.3 on 2023-04-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corban',
            name='corban_CNPJ',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='corban',
            name='corban_email',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='corban',
            name='corban_endereco',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='corban',
            name='corban_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='corban',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ativo?'),
        ),
    ]
