# Generated by Django 4.1.3 on 2023-04-27 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_corban_corban_cnpj_corban_corban_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corban',
            options={'verbose_name': '1. Corban', 'verbose_name_plural': '1. Corban'},
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={'verbose_name': '2. Produto', 'verbose_name_plural': '2. Produtos'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('name',), 'verbose_name': '3. Usuário', 'verbose_name_plural': '3. Usuários'},
        ),
    ]
