# Generated by Django 4.1.3 on 2023-05-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_corban_options_alter_produtos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='comprovante_residencia',
            field=models.BooleanField(default=True, help_text='É necessário enviar esse documento para esse produto?', verbose_name='Envio comprovante residência?'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='documento_pessoal',
            field=models.BooleanField(default=True, help_text='É necessário enviar esse documento para esse produto?', verbose_name='Envio documento pessoal?'),
        ),
    ]
