# Generated by Django 4.1.3 on 2023-05-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_produtos_comprovante_residencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corban',
            name='mesa_corban',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Mesa Corban'),
        ),
    ]
