# Generated by Django 4.1.3 on 2023-05-22 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_corban_mesa_corban'),
    ]

    operations = [
        migrations.AddField(
            model_name='corban',
            name='corban_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_auth.corban', verbose_name='Corban pai'),
        ),
    ]
