# Generated by Django 4.2.2 on 2023-06-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_produtos_tipo_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corban',
            options={'ordering': ('corban_name',), 'verbose_name': 'Corban', 'verbose_name_plural': '3. Corbans'},
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={'verbose_name': 'Produto', 'verbose_name_plural': '2. Produtos'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('name',), 'verbose_name': 'Usuário', 'verbose_name_plural': '1. Usuários'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='info',
            field=models.TextField(blank=True, help_text='Informações relevantes', null=True, verbose_name='Informações adicionais'),
        ),
        migrations.AlterField(
            model_name='corban',
            name='corban_name',
            field=models.CharField(max_length=250, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='identifier',
            field=models.CharField(help_text='Login do usuário', max_length=80, unique=True, verbose_name='Identificador'),
        ),
    ]
