# Generated by Django 4.1.3 on 2023-06-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0008_alter_corban_options_alter_produtos_options_and_more'),
        ('custom_auth', '0008_alter_produtos_tipo_produto'),
    ]

    operations = [
    ]
