# Generated by Django 4.2.2 on 2023-07-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0010_alter_produtos_tipo_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='media_segundos_digitacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Média segundos digitação'),
        ),
    ]
