# Generated by Django 4.2.2 on 2023-07-21 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_comercial', '0007_remove_cadastrolojas_representante_comercial_and_more'),
        ('custom_auth', '0012_remove_corban_corban_pai_corban_agencia_corban_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='departamento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dt_emissao_certificado',
            field=models.DateField(blank=True, help_text='Data de emissão do certificado Febraban', null=True, verbose_name='Data de emissão'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dt_validade_certificado',
            field=models.DateField(blank=True, help_text='Data de validade do certificado Febraban', null=True, verbose_name='Data de validade'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='funcionario_byx',
            field=models.BooleanField(default=False, verbose_name='Funcionário grupo BYX?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='municipio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Município de atuação'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='numero_febraban',
            field=models.IntegerField(blank=True, help_text='Número do certificado Febraban', null=True, verbose_name='Certificado Febraban'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='representante_comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_comercial.representantecomercial', verbose_name='Representante comercial'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='responsavel_direto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsável direto'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uf_atuacao',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'AC'), (2, 'AL'), (3, 'AP'), (4, 'AM'), (5, 'BA'), (6, 'CE'), (7, 'DF'), (8, 'ES'), (9, 'GO'), (10, 'MA'), (11, 'MT'), (12, 'MS'), (13, 'MG'), (14, 'PA'), (15, 'PB'), (16, 'PR'), (17, 'PE'), (18, 'PI'), (19, 'RJ'), (20, 'RN'), (21, 'RS'), (22, 'RO'), (23, 'RR'), (24, 'SC'), (25, 'SP'), (26, 'SE'), (27, 'TO')], null=True, verbose_name='UF de atuação'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='corban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_auth.corban', verbose_name='Corban/Loja'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='identifier',
            field=models.CharField(help_text='Login do usuário', max_length=80, unique=True, verbose_name='CPF do usuário'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Usuário Ativo?'),
        ),
    ]
