# Generated by Django 4.2.2 on 2023-07-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0013_userprofile_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica quem tem acesso ao Backoffice', verbose_name='Staff'),
        ),
    ]
