# Generated by Django 4.2.2 on 2023-08-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0015_userprofile_is_checked_userprofile_last_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='identifier',
            field=models.CharField(help_text='Login do usuário', max_length=80, verbose_name='CPF do usuário'),
        ),
    ]
