# Generated by Django 4.2.2 on 2023-08-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0016_alter_userprofile_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexousuario',
            name='selfie_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da selfie'),
        ),
    ]
