# Generated by Django 4.2.2 on 2023-08-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0017_anexousuario_selfie_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='identifier',
            field=models.CharField(help_text='Login do usuário', max_length=80, unique=True, verbose_name='CPF do usuário'),
        ),
    ]
