# Generated by Django 4.2.3 on 2023-09-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0019_alter_produtos_tipo_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexousuario',
            name='anexo_extensao',
        ),
        migrations.RemoveField(
            model_name='anexousuario',
            name='nome_anexo',
        ),
        migrations.AddField(
            model_name='produtos',
            name='contracheque',
            field=models.BooleanField(default=False, help_text='É necessário enviar esse documento para esse produto?', verbose_name='Envio contracheque?'),
        ),
        migrations.AlterField(
            model_name='anexousuario',
            name='tipo_anexo',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'CCB'), (2, 'Documento do cliente frente'), (3, 'Documento do cliente verso'), (12, 'Documentos Adicionais'), (4, 'Selfie'), (5, 'Foto da Prova de Vida'), (6, 'Comprovante de endereço'), (7, 'Comprovante financeiro'), (11, 'Repasse'), (22, 'Arquivo retorno reserva'), (8, 'Documento - CNH'), (13, 'Documento Frente - CNH'), (14, 'Documento Verso - CNH'), (15, 'Termos e assinaturas'), (16, 'Contracheque')], null=True, verbose_name='Tipo do anexo'),
        ),
    ]
