# Generated by Django 4.2.3 on 2023-09-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0021_facematchingconfig_alter_produtos_tipo_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='confia',
            field=models.BooleanField(default=False, verbose_name='Confia?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='confia_id',
            field=models.TextField(blank=True, help_text='Idenficador processo de validacao confia', null=True, verbose_name='Idenficador processo de validacao confia'),
        ),
    ]
