# Generated by Django 4.2.3 on 2023-10-11 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0022_produtos_confia_userprofile_confia_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='confia_id',
        ),
    ]
