# Generated by Django 4.2.3 on 2023-11-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0026_alter_anexousuario_tipo_anexo'),
        ('custom_auth', '0026_featuretoggle_delete_facematchingconfig'),
    ]

    operations = [
    ]
