# Generated by Django 4.2.3 on 2023-12-28 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_comercial', '0007_remove_cadastrolojas_representante_comercial_and_more'),
        ('custom_auth', '0028_corban_corban_type_corban_parent_corban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corban',
            name='representante_comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_comercial.representantecomercial', verbose_name='Representante Comercial'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='representante_comercial',
            field=models.BooleanField(default=False, verbose_name='Representante Comercial?'),
        ),
    ]
