# Generated by Django 4.2.3 on 2023-12-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0029_alter_corban_representante_comercial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='representante_comercial',
        ),
    ]
