# Generated by Django 4.2.3 on 2023-12-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0030_remove_userprofile_representante_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='representante_comercial',
            field=models.BooleanField(default=False, verbose_name='Representante Comercial?'),
        ),
    ]
