# Generated by Django 4.2.3 on 2024-01-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_auth', '0032_usersession_tokensession'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokensession',
            name='access',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
