# Generated by Django 4.2.3 on 2024-01-09 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('custom_auth', '0033_tokensession_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bairro_endereco',
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name='Bairro'
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cep_endereco',
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name='CEP'
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cidade_endereco',
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name='Cidade'
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='complemento_endereco',
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name='Bairro'
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='users_created',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Criado por',
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='endereco',
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name='Endereço'
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='numero_endereco',
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name='Número'
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uf_estado_endereco',
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, 'AC'),
                    (2, 'AL'),
                    (3, 'AP'),
                    (4, 'AM'),
                    (5, 'BA'),
                    (6, 'CE'),
                    (7, 'DF'),
                    (8, 'ES'),
                    (9, 'GO'),
                    (10, 'MA'),
                    (11, 'MT'),
                    (12, 'MS'),
                    (13, 'MG'),
                    (14, 'PA'),
                    (15, 'PB'),
                    (16, 'PR'),
                    (17, 'PE'),
                    (18, 'PI'),
                    (19, 'RJ'),
                    (20, 'RN'),
                    (21, 'RS'),
                    (22, 'RO'),
                    (23, 'RR'),
                    (24, 'SC'),
                    (25, 'SP'),
                    (26, 'SE'),
                    (27, 'TO'),
                ],
                null=True,
                verbose_name='UF',
            ),
        ),
    ]
