# Generated by Django 4.2.3 on 2024-01-09 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0034_userprofile_bairro_endereco_userprofile_cep_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Senha atualizada em'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Senha criada em'),
            preserve_default=False,
        ),
    ]
