# Generated by Django 4.2.3 on 2024-01-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0035_userprofile_password_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uf_estado_endereco',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF de residência do cliente'),
        ),
    ]
