# Generated by Django 4.2.3 on 2024-01-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0036_alter_userprofile_uf_estado_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_initial_password',
            field=models.BooleanField(default=True),
        ),
    ]
