# Generated by Django 4.2.3 on 2024-01-15 15:34

from django.db import migrations

from custom_auth.models import UserProfile


def create_permission(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Substitua 'UserProfile' pelo nome correto do seu modelo, se diferente
    content_type = ContentType.objects.get_for_model(UserProfile)
    Permission.objects.create(
        codename='happy_can_create_user',
        name='[HAPPY] Can Create User',
        content_type=content_type,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0037_userprofile_is_initial_password'),
    ]

    operations = [
        migrations.RunPython(create_permission),
    ]
