# Generated by Django 4.2.3 on 2024-01-19 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            'gestao_comercial',
            '0007_remove_cadastrolojas_representante_comercial_and_more',
        ),
        ('custom_auth', '0038_auto_20240115_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corban',
            name='parent_corban',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sub_corbans',
                to='custom_auth.corban',
                verbose_name='Corban Superior',
            ),
        ),
        migrations.AlterField(
            model_name='corban',
            name='representante_comercial',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='gestao_comercial.representantecomercial',
                verbose_name='Representante Comercial',
            ),
        ),
    ]
