# Generated by Django 4.2.3 on 2024-01-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0039_alter_corban_parent_corban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='numero_febraban',
            field=models.CharField(blank=True, help_text='Número do certificado Febraban', max_length=50, null=True, verbose_name='Certificado Febraban'),
        ),
    ]
