# Generated by Django 4.2.3 on 2024-01-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0041_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, null=True, max_length=255, unique=True),
        ),
    ]

