# Generated by Django 4.2.3 on 2024-03-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0042_auto_20240122_1208"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anexousuario",
            name="tipo_anexo",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "CCB"),
                    (2, "Documento do cliente frente"),
                    (3, "Documento do cliente verso"),
                    (12, "Documentos Adicionais"),
                    (4, "Selfie"),
                    (5, "Foto da Prova de Vida"),
                    (6, "Comprovante de endereço"),
                    (7, "Comprovante financeiro"),
                    (11, "Repasse"),
                    (22, "Arquivo retorno reserva"),
                    (8, "Documento - CNH"),
                    (13, "Documento Frente - CNH"),
                    (14, "Documento Verso - CNH"),
                    (15, "Termos e assinaturas"),
                    (16, "Contracheque"),
                    (17, "Documento assinado fisicamente"),
                    (18, "Documento frente rogado"),
                    (19, "Documento verso rogado"),
                ],
                null=True,
                verbose_name="Tipo do anexo",
            ),
        ),
    ]
