# Generated by Django 4.2.2 on 2023-06-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComissaoTaxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_contrato_tipo', models.SmallIntegerField(choices=[(1, 'Operação nova (margem livre)'), (2, 'Refinanciamento'), (3, 'Refin Portabilidade'), (4, 'Portabilidade'), (5, 'Novo Aumento Salarial'), (6, 'Saque Complementar')], db_index=True, verbose_name='Contrato Tipo')),
                ('cd_convenio', models.IntegerField(null=True, verbose_name='Código Convenio')),
                ('prazo', models.IntegerField(null=True, verbose_name='Prazo')),
                ('tx_efetiva_contrato_min', models.FloatField(null=True, verbose_name='Taxa Efetiva Contrato Min')),
                ('tx_efetiva_contrato_max', models.FloatField(null=True, verbose_name='Taxa Efetiva Contrato Max')),
                ('tx_comissao_total', models.FloatField(null=True, verbose_name='Taxa Comissao Total')),
                ('tx_comissao_flat', models.FloatField(null=True, verbose_name='Taxa Comissao Flat')),
                ('tx_comissao_pmt', models.FloatField(null=True, verbose_name='Taxa Comissao Pmt')),
                ('tx_parcelada_vf', models.FloatField(null=True, verbose_name='Taxa Parcelada VF')),
                ('tx_parcelada_vp', models.FloatField(null=True, verbose_name='Taxa Parcelada VP')),
                ('tx_total_vp', models.FloatField(null=True, verbose_name='Taxa Total VP')),
                ('tx_antecipacao', models.FloatField(null=True, verbose_name='Taxa Antecipacao')),
                ('dt_vigencia_inicio', models.DateTimeField(null=True, verbose_name='Data Vigencia Inicio')),
                ('dt_vigencia_fim', models.DateTimeField(null=True, verbose_name='Data Vigencia Fim')),
                ('dt_cadastro', models.DateTimeField(null=True, verbose_name='Data Cadastro')),
                ('fl_ativa', models.BooleanField(null=True, verbose_name='Flag Ativa')),
            ],
            options={
                'verbose_name': 'Comissao Taxa',
            },
        ),
        migrations.CreateModel(
            name='ContratoTipoTaxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_contrato_tipo', models.SmallIntegerField(choices=[(1, 'Operação nova (margem livre)'), (2, 'Refinanciamento'), (3, 'Refin Portabilidade'), (4, 'Portabilidade'), (5, 'Novo Aumento Salarial'), (6, 'Saque Complementar')], db_index=True, verbose_name='Contrato Tipo')),
                ('dt_inicio_vigencia', models.DateTimeField(null=True, verbose_name='Data Início Vigência')),
                ('dt_fim_vigencia', models.DateTimeField(null=True, verbose_name='Data Fim Vigência')),
                ('vr_taxa_efetiva_mes_min', models.FloatField(null=True, verbose_name='Valor Taxa Efetiva Mês Min')),
                ('vr_taxa_efetiva_mes_max', models.FloatField(null=True, verbose_name='Valor Taxa Efetiva Mês Max')),
            ],
            options={
                'verbose_name': 'Tipo Taxa',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_data', models.DateField()),
                ('base', models.IntegerField()),
                ('ds_mes', models.CharField(max_length=50, null=True)),
                ('ds_dia_da_semana', models.CharField(max_length=50, null=True)),
                ('ds_feriado', models.CharField(max_length=50, null=True)),
                ('fl_final_de_semana', models.BooleanField()),
                ('fl_feriado', models.BooleanField()),
                ('fl_ponto_facultativo', models.BooleanField()),
                ('fl_dia_util', models.BooleanField()),
                ('dt_data_util', models.DateField()),
            ],
            options={
                'verbose_name': 'Data',
            },
        ),
        migrations.CreateModel(
            name='FaixaIdade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nu_idade_minima', models.FloatField(null=True, verbose_name='Idade Mínima')),
                ('nu_idade_maxima', models.FloatField(null=True, verbose_name='Idade Máxima')),
                ('vr_minimo', models.FloatField(null=True, verbose_name='Valor Mínimo')),
                ('vr_maximo', models.FloatField(null=True, verbose_name='Valor Máximo')),
                ('nu_prazo_minimo', models.IntegerField(null=True, verbose_name='Prazo Mínimo')),
                ('nu_prazo_maximo', models.IntegerField(null=True, verbose_name='Prazo Máximo')),
                ('fl_possui_representante_legal', models.BooleanField(null=True, verbose_name='Possui Representante Legal')),
            ],
            options={
                'verbose_name': 'Faixa de Idade',
            },
        ),
    ]
