# Generated by Django 4.1.3 on 2023-04-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosIn100',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NmCliente', models.CharField(max_length=400, null=True, verbose_name='Nome do Cliente')),
                ('FlSituacaoBeneficio', models.BooleanField(null=True, verbose_name='Situação do Benefício')),
                ('CdInnsBeneficioTipo', models.IntegerField(null=True, verbose_name='Código do Tipo de Benefício')),
                ('UfBeneficio', models.CharField(max_length=2, null=True, verbose_name='UF do Benefício')),
                ('CdTipoConta', models.IntegerField(choices=[(1, 'Conta Corrente Pessoa Física'), (2, 'Conta Corrente Pessoa Jurídica'), (3, 'Conta Poupança Pessoa Física'), (4, 'Cartão magnético')], null=True, verbose_name='Código do Tipo de Conta')),
                ('CdBanco', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do banco')),
                ('NuAgencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da Agência')),
                ('NuConta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da Conta')),
                ('NrDigito', models.CharField(blank=True, max_length=2, null=True, verbose_name='Número do Dígito')),
                ('CdPensaoSituacao', models.CharField(choices=[(1, 'Não Pagador(a)'), (2, 'Pagador(a)'), (3, 'Beneficio')], max_length=2, null=True, verbose_name='Código da Situação da Pensão')),
                ('VrMargem', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor da Margem')),
                ('QtTotalEmprestimos', models.IntegerField(null=True, verbose_name='Quantidade Total de Empréstimos')),
                ('FlConcessaoJudicial', models.BooleanField(null=True, verbose_name='Concessão Judicial')),
                ('FlPossuiRepresentanteLegal', models.BooleanField(null=True, verbose_name='Possui Representante Legal')),
                ('FlPossuiProcurador', models.BooleanField(null=True, verbose_name='Possui Procurador')),
                ('FlPossuiEntidadeRepresentante', models.BooleanField(null=True, verbose_name='Possui Entidade Representante')),
                ('FlPossuiImpedimentoEmprestimo', models.BooleanField(null=True, verbose_name='Possui Impedimento para Empréstimo')),
                ('FlElegivelEmprestimo', models.BooleanField(null=True, verbose_name='Elegível para Empréstimo')),
                ('DsRecusa', models.TextField(blank=True, null=True, verbose_name='Descrição da Recusa')),
                ('DtUltimoExameMedico', models.DateField(blank=True, null=True, verbose_name='Data do Último Exame Médico')),
                ('DtExpedicaoBeneficio', models.DateField(blank=True, null=True, verbose_name='Data de Expedição do Benefício')),
            ],
            options={
                'verbose_name': 'Dados de retorno da IN100',
                'verbose_name_plural': 'Dados de retorno da IN100',
            },
        ),
        migrations.CreateModel(
            name='INSSBeneficioTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdInssBeneficioTipo', models.IntegerField(null=True, verbose_name='Código do tipo do benefício no INSS')),
                ('dsINSSBeneficioTipo', models.CharField(max_length=300, null=True, verbose_name='Descrição do tipo do beneficio')),
                ('inssBeneficioTipo', models.TextField(max_length=300, null=True, verbose_name='Descrição do tipo do beneficio do INSS')),
                ('dsINSSBeneficioTipoIngles', models.CharField(max_length=200, null=True, verbose_name='Nome do tipo do beneficio em ingles, utilizado pela financeira qi tech')),
                ('flConsignavel', models.BooleanField(null=True, verbose_name='Indica se o beneficio é consignável')),
                ('flAtivo', models.BooleanField(null=True, verbose_name='Indica se o benefício está ativo')),
            ],
            options={
                'verbose_name': '3. INSS Beneficio',
                'verbose_name_plural': '3. INSS Beneficios',
            },
        ),
        migrations.CreateModel(
            name='LogWebHookQiTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcao_webhook', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nome da Função do Webhook')),
                ('json_entrada', models.TextField(blank=True, null=True, verbose_name='Json Entrada')),
                ('json_saida', models.TextField(blank=True, null=True, verbose_name='Json Saída')),
                ('dt_entrada', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Entrada do Webhook')),
                ('dt_saida', models.DateTimeField(null=True, verbose_name='Data de Saída do Webhook')),
                ('chave_retorno_financeira', models.CharField(blank=True, max_length=300, null=True, verbose_name='Chave de Retorno da Financeira')),
            ],
            options={
                'verbose_name': 'Log WebHook Qi Tech',
                'verbose_name_plural': 'Logs WebHook Qi Tech',
            },
        ),
    ]
