# Generated by Django 4.1.3 on 2023-05-19 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0053_alter_statuscontrato_descricao_mesa'),
        ('consignado_inss', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosin100',
            name='contrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contract.contrato', verbose_name='Contrato'),
            preserve_default=False,
        ),
    ]
