# Generated by Django 4.1.3 on 2023-06-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignado_inss', '0003_dadosin100_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosin100',
            name='anexo_in100',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='', verbose_name='Termo IN100'),
        ),
    ]
