# Generated by Django 4.2.2 on 2023-06-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignado_inss', '0004_dadosin100_anexo_in100'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosin100',
            name='in100_data_autorizacao',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Data de autorização da IN100'),
        ),
    ]
