# Generated by Django 4.2.2 on 2023-06-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignado_inss', '0005_dadosin100_in100_data_autorizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosin100',
            name='CdPensaoSituacao',
            field=models.SmallIntegerField(choices=[(1, 'Não Pagador(a)'), (2, 'Pagador(a)'), (3, 'Beneficio')], max_length=2, null=True, verbose_name='Código da Situação da Pensão'),
        ),
    ]
