# Generated by Django 4.2.2 on 2023-06-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignado_inss', '0007_alter_dadosin100_cdpensaosituacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosin100',
            name='NmBeneficio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do benefício'),
        ),
    ]
