# Generated by Django 4.2.2 on 2023-06-13 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_cliente_in100_data_autorizacao'),
        ('consignado_inss', '0008_dadosin100_nmbeneficio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosin100',
            old_name='CdBanco',
            new_name='codigo_banco',
        ),
        migrations.RenameField(
            model_name='dadosin100',
            old_name='DsRecusa',
            new_name='descricao_recusa',
        ),
        migrations.RenameField(
            model_name='dadosin100',
            old_name='DtExpedicaoBeneficio',
            new_name='dt_expedicao_beneficio',
        ),
        migrations.RenameField(
            model_name='dadosin100',
            old_name='NuAgencia',
            new_name='numero_agencia',
        ),
        migrations.RenameField(
            model_name='dadosin100',
            old_name='NmBeneficio',
            new_name='numero_beneficio',
        ),
        migrations.RenameField(
            model_name='dadosin100',
            old_name='NuConta',
            new_name='numero_conta',
        ),
        migrations.RenameField(
            model_name='dadosin100',
            old_name='NrDigito',
            new_name='numero_digito',
        ),
        migrations.RenameField(
            model_name='dadosin100',
            old_name='DtUltimoExameMedico',
            new_name='utlimo_exame_medico',
        ),
        migrations.RemoveField(
            model_name='dadosin100',
            name='CdInnsBeneficioTipo',
        ),
        migrations.RemoveField(
            model_name='dadosin100',
            name='CdPensaoSituacao',
        ),
        migrations.RemoveField(
            model_name='dadosin100',
            name='CdTipoConta',
        ),
        migrations.RemoveField(
            model_name='dadosin100',
            name='FlElegivelEmprestimo',
        ),
        migrations.RemoveField(
            model_name='dadosin100',
            name='FlPossuiEntidadeRepresentante',
        ),
        migrations.RemoveField(
            model_name='dadosin100',
            name='FlPossuiProcurador',
        ),
        migrations.RemoveField(
            model_name='dadosin100',
            name='FlPossuiRepresentanteLegal',
        ),
        migrations.RemoveField(
            model_name='dadosin100',
            name='FlSituacaoBeneficio',
        ),
        migrations.RemoveField(
            model_name='dadosin100',
            name='NmCliente',
        ),
        migrations.RemoveField(
            model_name='dadosin100',
            name='QtTotalEmprestimos',
        ),
        migrations.RemoveField(
            model_name='dadosin100',
            name='UfBeneficio',
        ),
        migrations.RemoveField(
            model_name='dadosin100',
            name='VrMargem',
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='cd_beneficio_tipo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código do Tipo de Benefício'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='cd_pensao_situracao',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Não Pagador(a)'), (2, 'Pagador(a)'), (3, 'Beneficio')], null=True, verbose_name='Código da Situação da Pensão'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='cd_tipo_conta',
            field=models.IntegerField(blank=True, choices=[(1, 'Conta Corrente Pessoa Física'), (2, 'Conta Corrente Pessoa Jurídica'), (3, 'Conta Poupança Pessoa Física'), (4, 'Cartão magnético')], null=True, verbose_name='Código do Tipo de Conta'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='elegivel_emprestimo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Elegível para Empréstimo'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Nome do Cliente'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='possui_entidade_representante',
            field=models.BooleanField(blank=True, null=True, verbose_name='Possui Entidade Representante'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='possui_procurador',
            field=models.BooleanField(blank=True, null=True, verbose_name='Possui Procurador'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='possui_representante_legal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Possui Representante Legal'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='qt_total_emprestimos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade Total de Empréstimos'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='situacao_beneficio',
            field=models.BooleanField(blank=True, null=True, verbose_name='Situação do Benefício'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='uf_beneficio',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF do Benefício'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='valor_margem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor da Margem'),
        ),
        migrations.AlterField(
            model_name='dadosin100',
            name='FlConcessaoJudicial',
            field=models.BooleanField(blank=True, null=True, verbose_name='Concessão Judicial'),
        ),
        migrations.AlterField(
            model_name='dadosin100',
            name='FlPossuiImpedimentoEmprestimo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Possui Impedimento para Empréstimo'),
        ),
        migrations.AlterField(
            model_name='dadosin100',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_in100', to='core.cliente', verbose_name='Cliente'),
        ),
    ]
