# Generated by Django 4.2.2 on 2023-06-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignado_inss', '0009_rename_cdbanco_dadosin100_codigo_banco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosin100',
            old_name='FlConcessaoJudicial',
            new_name='concessao_judicial',
        ),
        migrations.RenameField(
            model_name='dadosin100',
            old_name='FlPossuiImpedimentoEmprestimo',
            new_name='possui_impedimento_emprestimo',
        ),
        migrations.RemoveField(
            model_name='dadosin100',
            name='anexo_in100',
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='valor_beneficio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor do Benefício'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='valor_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Líquido do Benefício'),
        ),
    ]
