# Generated by Django 4.2.2 on 2023-06-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignado_inss', '0010_rename_flconcessaojudicial_dadosin100_concessao_judicial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosin100',
            name='nome_cliente',
        ),
        migrations.AlterField(
            model_name='dadosin100',
            name='situacao_beneficio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Situação do Benefício'),
        ),
    ]
