# Generated by Django 4.2.2 on 2023-06-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consignado_inss', '0011_remove_dadosin100_nome_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosin100',
            name='contrato',
        ),
    ]
