# Generated by Django 4.2.2 on 2023-06-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignado_inss', '0013_remove_dadosin100_cd_tipo_conta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosin100',
            name='retornou_IN100',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Retornou Dados IN100'),
        ),
    ]
