# Generated by Django 4.2.2 on 2023-06-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignado_inss', '0014_dadosin100_retornou_in100'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosin100',
            name='balance_request_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Key do cliente IN100'),
        ),
    ]
