# Generated by Django 4.2.2 on 2023-07-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignado_inss', '0015_dadosin100_balance_request_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosin100',
            name='tipo_retorno',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo de Retorno da IN100'),
        ),
    ]
