# Generated by Django 4.2.2 on 2023-07-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignado_inss', '0017_especiein100_remove_dadosin100_utlimo_exame_medico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosin100',
            name='chamada_sem_sucesso',
            field=models.CharField(blank=True, help_text='Caso a chamada não foi bem sucedida aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo de erro QITECH'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='envio_termo_sem_sucesso',
            field=models.CharField(blank=True, help_text='Caso o envio do termo IN100 não foi bem sucedida aqui aparece o motivo do erro', max_length=300, null=True, verbose_name='Motivo envio do termo IN100'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='sucesso_chamada_in100',
            field=models.BooleanField(blank=True, default=None, help_text='Mostra se houve sucesso na chamada da in100', null=True, verbose_name='Sucesso chamada IN100'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='sucesso_envio_termo_in100',
            field=models.BooleanField(blank=True, default=None, help_text='Mostra se houve sucesso no envio do termo IN100', null=True, verbose_name='Envio do termo IN100'),
        ),
    ]
