# Generated by Django 4.2.2 on 2023-08-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignado_inss', '0018_dadosin100_chamada_sem_sucesso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosin100',
            name='cd_pensao_situracao',
        ),
        migrations.RemoveField(
            model_name='dadosin100',
            name='elegivel_emprestimo',
        ),
        migrations.RemoveField(
            model_name='dadosin100',
            name='possui_impedimento_emprestimo',
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='situacao_pensao',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Situação da Pensão Alimetícia'),
        ),
        migrations.AlterField(
            model_name='dadosin100',
            name='possui_procurador',
            field=models.BooleanField(blank=True, null=True, verbose_name='Possui Procuração'),
        ),
    ]
