# Generated by Django 4.2.2 on 2023-08-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignado_inss', '0019_remove_dadosin100_cd_pensao_situracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosin100',
            name='validacao_in100_recalculo',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se a in100 ja retornou na fase do recalculo', null=True, verbose_name='IN100 Recalculo'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='validacao_in100_saldo_retornado',
            field=models.BooleanField(blank=True, default=None, help_text='Indica se a proxima in100 que vai voltar é a do recalculo', null=True, verbose_name='IN100 saldo retornado'),
        ),
    ]
