# Generated by Django 4.2.2 on 2023-08-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignado_inss', '0020_dadosin100_validacao_in100_recalculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especiein100',
            name='tipo_produto',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'FGTS'), (2, 'INSS - Representante Legal'), (3, 'Cartão Benefício - Representante Legal'), (4, 'PAB'), (5, 'INSS CORBAN'), (6, 'INSS'), (7, 'Cartão Benefício'), (8, 'Siape'), (9, 'Exercito'), (10, 'Marinha'), (11, 'Aeronautica'), (12, 'Portabilidade'), (13, 'Consignado'), (14, 'Saque Complementar'), (15, 'Cartão Consignado')], null=True, verbose_name='Tipo Produto'),
        ),
    ]
