# Generated by Django 4.2.3 on 2023-11-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignado_inss', '0022_alter_especiein100_tipo_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosin100',
            name='vr_disponivel_emprestimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor total disponível para empréstimo'),
        ),
        migrations.AlterField(
            model_name='especiein100',
            name='tipo_produto',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'FGTS'), (2, 'INSS - Representante Legal'), (3, 'Cartão Benefício - Representante Legal'), (4, 'PAB'), (5, 'INSS CORBAN'), (6, 'INSS'), (7, 'Cartão Benefício'), (8, 'Siape'), (9, 'Exercito'), (10, 'Marinha'), (11, 'Aeronautica'), (12, 'Portabilidade'), (13, 'Consignado'), (14, 'Saque Complementar'), (15, 'Cartão Consignado'), (16, 'Margem Livre'), (17, 'Portabilidade + Refinanciamento')], null=True, verbose_name='Tipo Produto'),
        ),
    ]
