# Generated by Django 4.2.3 on 2023-12-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignado_inss', '0023_dadosin100_vr_disponivel_emprestimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosin100',
            name='beneficio_ativo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Situação do benefício'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='data_expiracao_beneficio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Data de expiração do benefício'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='data_final_beneficio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Data final do benefício'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='data_retorno_in100',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Data de retorno da in100'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='limite_cartao_beneficio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Limite do cartão benefício'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='limite_cartao_consignado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Limite do cartão consignado'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='margem_livre_cartao_beneficio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Margem livre do cartão benefício'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='margem_livre_cartao_consignado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Margem livre do cartão_consignado'),
        ),
        migrations.AddField(
            model_name='dadosin100',
            name='margem_total_beneficio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Margem total do benefício'),
        ),
        migrations.AlterField(
            model_name='dadosin100',
            name='situacao_beneficio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status do Benefício'),
        ),
        migrations.AlterField(
            model_name='dadosin100',
            name='tipo_retorno',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo de recebimento do beneficio'),
        ),
        migrations.AlterField(
            model_name='dadosin100',
            name='valor_beneficio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor Calculado', max_digits=15, null=True, verbose_name='Valor do benefício'),
        ),
        migrations.AlterField(
            model_name='dadosin100',
            name='valor_margem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Margem livre do credito consignado'),
        ),
    ]
