# Generated by Django 4.2.3 on 2023-12-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignado_inss', '0024_dadosin100_beneficio_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosin100',
            name='data_expiracao_beneficio',
            field=models.DateField(blank=True, max_length=150, null=True, verbose_name='Data de expiração do benefício'),
        ),
    ]
