# Generated by Django 4.2.3 on 2023-12-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignado_inss', '0025_alter_dadosin100_data_expiracao_beneficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosin100',
            name='qt_total_emprestimos_suspensos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade Total de Empréstimos Suspensos'),
        ),
        migrations.AlterField(
            model_name='dadosin100',
            name='qt_total_emprestimos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade Total de Empréstimos Reservados'),
        ),
    ]
