from enum import Enum


class SeguroStatus(Enum):
    CRIADO_SUCESSO = 1
    RECUSADO_ERRO_NECESSITA_ATENCAO = 2
    RECUSADO_OPERADORA = 3


class ContractStatus(Enum):
    # CARTAO_BENEFICIO
    ANDAMENTO_SIMULACAO = 1
    ANDAMENTO_FORMALIZACAO = 5
    APROVADA_FINALIZADA = 6
    REPROVADA_FINALIZADA = 7
    CHECAGEM_MESA_FORMALIZACAO = 8
    APROVADA_MESA_FORMALIZACAO = 9
    REPROVADA_MESA_FORMALIZACAO = 10
    PENDENTE_DOCUMENTACAO = 11
    EM_AVERBACAO = 12
    APROVADA_AVERBACAO = 13
    RECUSADA_AVERBACAO = 14
    ANDAMENTO_EMISSAO_CARTAO = 15
    FINALIZADA_EMISSAO_CARTAO = 16
    ANDAMENTO_LIBERACAO_SAQUE = 17
    FINALIZADA_LIBERACAO_SAQUE = 18
    PENDENTE_CORRECAO_DADOS_BANCARIOS = 19

    # PORTABILIDADE
    AGUARDA_ENVIO_LINK = 20
    FORMALIZACAO_CLIENTE = 21
    ANALISE_DE_CREDITO = 22
    PENDENTE_DADOS_DIVERGENTES = 23
    REPROVADA_POLITICA_INTERNA = 24
    CHECAGEM_MESA_CORBAN = 25
    PENDENTE_DOCUMENTACAO_MESA_CORBAN = 26
    REPROVADA_MESA_CORBAN = 27
    APROVADA_MESA_CORBAN = 28
    CHECAGEM_MESA_DE_FORMALIZACAO = 29
    APROVADA_MESA_DE_FORMALIZACAO = 30
    REPROVADA_MESA_DE_FORMALIZACAO = 31
    AGUARDA_RETORNO_SALDO = 32
    SALDO_RETORNADO = 33
    INT_CONFIRMA_PAGAMENTO = 34
    SALDO_REPROVADO = 35
    REPROVADA_PAGAMENTO_DEVOLVIDO = 36
    INT_AGUARDA_AVERBACAO = 37
    INT_FINALIZADO = 38
    INT_AVERBACAO_PENDENTE = 39

    # CARTAO NOVOS
    ERRO_SOLICITACAO_SAQUE = 40

    # PORTABILIDADE IN100
    REPROVADO = 41
    AGUARDANDO_RETORNO_IN100 = 42

    # NOVO STATUS
    AGUARDANDO_IN100_RECALCULO = 43
    RETORNO_IN100_RECALCULO_RECEBIDO = 44

    REVISAO_MESA_DE_FORMALIZACAO = 45
    REPROVADA_REVISAO_MESA_DE_FORMALIZACAO = 46
    AVERBACAO_MESA_DE_FORMALIZACAO = 47

    SAQUE_CANCELADO_LIMITE_DISPONIVEL_INSUFICIENTE = 48
    SAQUE_RECUSADO_PROBLEMA_PAGAMENTO = 49

    ANDAMENTO_REAPRESENTACAO_DO_PAGAMENTO_DE_SAQUE = 50
    PENDENCIADO = 51

    ANDAMENTO_CHECAGEM_DATAPREV = 52
    ERRO_CONSULTA_DATAPREV = 53
    REPROVADO_CONSULTA_DATAPREV = 54

    # PORT + REFIN
    AGUARDANDO_AVERBACAO_REFIN = 55
    AGUARDANDO_DESEMBOLSO_REFIN = 56
    AGUARDANDO_FINALIZAR_PORT = 57
    INT_FINALIZADO_DO_REFIN = 58

    ERRO_CRIACAO_CARTAO = 59
    PENDENTE_APROVACAO_RECALCULO_CORBAN = 60

    CHECAGEM_MESA_DE_AVERBECAO = 61

    AGUARDA_FINALIZACAO_PROPOSTA_PRINCIPAL = 62
    REPROVADA_MESA_DE_AVERBECAO = 63
    INT_AJUSTE_AVERBACAO = 64

    VALIDACOES_AUTOMATICAS = 65
    AGUARDANDO_DESEMBOLSO = 66
    INT_AGUARDANDO_PAGO_QITECH = 67

    PENDENCIAS_AVERBACAO_CORBAN = 68
    REGULARIZADA_MESA_AVERBACAO = 69
    FINALIZADA_FORMALIZACAO_CLIENTE = 70
    FINALIZADA_FORMALIZACAO_ROGADO = 71
