from django.urls import path

import contract.products.cartao_beneficio.api.views as cartao_beneficio_view

urlpatterns = [
    path('consulta-convenios/', cartao_beneficio_view.ConveniosApiView.as_view()),
    path(
        'consulta-matricula/',
        cartao_beneficio_view.registration_view,
        name='api_consulta_matricula',
    ),
    path(
        'consulta-margem/',
        cartao_beneficio_view.margem_view,
        name='api_consulta_margem',
    ),
    path(
        'realizar-reserva/',
        cartao_beneficio_view.realiza_reserva_view,
        name='api_realizar_reserva',
    ),
    path(
        'cancelar-reserva/',
        cartao_beneficio_view.cancela_reserva_view,
        name='api_cancela_reserva',
    ),
    path(
        'simulacao-limite/',
        cartao_beneficio_view.simulacao_limite_view,
        name='api_simulacao_limite',
    ),
    path(
        'simulacao-saque/',
        cartao_beneficio_view.simulacao_saque_view,
        name='api_simulacao_saque',
    ),
    path(
        'simulacao-saque-complementar/',
        cartao_beneficio_view.SimulacaoSaqueComplementar.as_view(),
        name='api_simulacao_saque_complementar',
    ),
    path(
        'planos/',
        cartao_beneficio_view.PlanosAPIView.as_view(),
        name='planos',
    ),
    path(
        'seguros/',
        cartao_beneficio_view.InsuranceByAgreementView.as_view(),
        name='seguros',
    ),
    path(
        'atualizar-contrato-saque/',
        cartao_beneficio_view.AtualizarContratoSaque.as_view(),
        name='atualizar-contrato-saque',
    ),
    path(
        'verifica-cartao/',
        cartao_beneficio_view.VerificaCartaoCliente.as_view(),
        name='verifica_cartao_cliente',
    ),
    path(
        'consulta-limite-saque/',
        cartao_beneficio_view.ConsultaLimiteSaque.as_view(),
        name='consulta_limite_saque',
    ),
    path(
        'criar-contrato-saque-complementar/',
        cartao_beneficio_view.CriarContratoSaqueComplementar.as_view(),
        name='criar_contrato_saque_complementar',
    ),
    path(
        'aceite-in100/',
        cartao_beneficio_view.Aceite_IN100.as_view(),
        name='aceite-in100',
    ),
    path(
        'consulta-in100/',
        cartao_beneficio_view.ConsultaIN100.as_view(),
        name='consulta_in100',
    ),
    path(
        'autorizacao-consulta-digital/',
        cartao_beneficio_view.AutorizacaoConsultaDigital.as_view(),
        name='autorizacao-consulta-digital',
    ),
    path(
        'consulta-beneficio/',
        cartao_beneficio_view.ConsultaBeneficios.as_view(),
        name='consulta-beneficio',
    ),
    path(
        'consulta-margem-inss/',
        cartao_beneficio_view.ConsultaMargemInss.as_view(),
        name='consulta-margem-inss',
    ),
    path('import-excel/', cartao_beneficio_view.import_excel_view, name='import_excel'),
    path(
        'cancelamento-planos/',
        cartao_beneficio_view.CancelamentoPlano.as_view(),
        name='cancelemento-plano-generali',
    ),
    path(
        'arrecadacao-planos/',
        cartao_beneficio_view.ArrecadacaoPlano.as_view(),
        name='arrecadacao-plano-generali',
    ),
]
