# Generated by Django 4.2.3 on 2024-01-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'product',
                    models.SmallIntegerField(
                        choices=[
                            (1, 'FGTS'),
                            (2, 'INSS - Representante Legal'),
                            (3, 'Cartão Benefício - Representante Legal'),
                            (4, 'PAB'),
                            (5, 'INSS CORBAN'),
                            (6, 'INSS'),
                            (7, 'Cartão Benefício'),
                            (8, 'Siape'),
                            (9, 'Exercito'),
                            (10, 'Marinha'),
                            (11, 'Aeronautica'),
                            (12, 'Portabilidade'),
                            (13, 'Consignado'),
                            (14, 'Saque Complementar'),
                            (15, 'Cartão Consignado'),
                            (16, 'Margem Livre'),
                            (17, 'Portabilidade + Refinanciamento'),
                        ],
                        default=1,
                        unique=True,
                        verbose_name='Tipo de Produto',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='UnicoParameter',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('products', models.ManyToManyField(to='documentscopy.product')),
            ],
        ),
    ]
