# Generated by Django 4.2.3 on 2024-01-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_auth', '0039_alter_corban_parent_corban_and_more'),
        ('documentscopy', '0002_populate_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='unicoparameter',
            name='corbans',
            field=models.ManyToManyField(to='custom_auth.corban'),
        ),
    ]
