# Generated by Django 4.2.3 on 2024-01-19 04:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documentscopy', '0003_unicoparameter_corbans'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnicoParameterFaceMatch',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'score_from',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MaxValueValidator(99.99)],
                        verbose_name='De',
                    ),
                ),
                (
                    'score_to',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.01),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name='Até',
                    ),
                ),
                (
                    'corban_action',
                    models.IntegerField(
                        choices=[(0, 'Aprovar'), (1, 'Pendenciar'), (2, 'Reprovar')],
                        default=0,
                        verbose_name='Ação',
                    ),
                ),
            ],
        ),
    ]
