# Generated by Django 4.2.3 on 2024-01-19 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('documentscopy', '0004_unicoparameterfacematch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unicoparameter',
            options={
                'verbose_name': 'Parametro Unico',
                'verbose_name_plural': 'Parametro Unico',
            },
        ),
        migrations.AlterModelOptions(
            name='unicoparameterfacematch',
            options={
                'verbose_name': 'Biometria Facial',
                'verbose_name_plural': 'Biometria Facial',
            },
        ),
        migrations.AddField(
            model_name='unicoparameterfacematch',
            name='parameter',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='documentscopy.unicoparameter',
                verbose_name='Parametro',
            ),
        ),
    ]
