# Generated by Django 4.2.3 on 2024-01-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0039_alter_corban_parent_corban_and_more"),
        ("documentscopy", "0005_alter_unicoparameter_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiaParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corbans", models.ManyToManyField(to="custom_auth.corban")),
                ("products", models.ManyToManyField(to="documentscopy.product")),
            ],
            options={
                "verbose_name": "Parametro Confia",
                "verbose_name_plural": "Parametro Confia",
            },
        ),
    ]
