# Generated by Django 4.2.3 on 2024-01-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0040_alter_userprofile_numero_febraban"),
        ("cartao_beneficio", "0058_alter_planos_seguradora"),
        ("documentscopy", "0007_alter_unicoparameterfacematch_corban_action_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="confiaparameterfacematch",
            name="parameter",
        ),
        migrations.AddField(
            model_name="bpoconfig",
            name="entities",
            field=models.ManyToManyField(
                to="cartao_beneficio.convenios", verbose_name="Entidades"
            ),
        ),
        migrations.AddField(
            model_name="bpoconfig",
            name="stores",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_stores",
                to="custom_auth.corban",
                verbose_name="Lojas",
            ),
        ),
        migrations.AddField(
            model_name="unicoparameter",
            name="entities",
            field=models.ManyToManyField(
                to="cartao_beneficio.convenios", verbose_name="Entidades"
            ),
        ),
        migrations.AddField(
            model_name="unicoparameter",
            name="stores",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_stores",
                to="custom_auth.corban",
                verbose_name="Lojas",
            ),
        ),
        migrations.AlterField(
            model_name="bpoconfig",
            name="corbans",
            field=models.ManyToManyField(
                limit_choices_to={"corban_type": 1},
                related_name="%(app_label)s_%(class)s_corbans",
                to="custom_auth.corban",
            ),
        ),
        migrations.AlterField(
            model_name="bpoconfig",
            name="products",
            field=models.ManyToManyField(
                to="documentscopy.product", verbose_name="Produtos"
            ),
        ),
        migrations.AlterField(
            model_name="unicoparameter",
            name="corbans",
            field=models.ManyToManyField(
                limit_choices_to={"corban_type": 1},
                related_name="%(app_label)s_%(class)s_corbans",
                to="custom_auth.corban",
            ),
        ),
        migrations.AlterField(
            model_name="unicoparameter",
            name="products",
            field=models.ManyToManyField(
                to="documentscopy.product", verbose_name="Produtos"
            ),
        ),
        migrations.DeleteModel(
            name="ConfiaParameter",
        ),
        migrations.DeleteModel(
            name="ConfiaParameterFaceMatch",
        ),
    ]
