# Generated by Django 4.2.3 on 2024-01-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cartao_beneficio", "0058_alter_planos_seguradora"),
        ("custom_auth", "0040_alter_userprofile_numero_febraban"),
        ("documentscopy", "0008_remove_confiaparameterfacematch_parameter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bpoconfig",
            name="entities",
            field=models.ManyToManyField(
                blank=True, to="cartao_beneficio.convenios", verbose_name="Entidades"
            ),
        ),
        migrations.AlterField(
            model_name="bpoconfig",
            name="stores",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_%(class)s_stores",
                to="custom_auth.corban",
                verbose_name="Lojas",
            ),
        ),
        migrations.AlterField(
            model_name="unicoparameter",
            name="entities",
            field=models.ManyToManyField(
                blank=True, to="cartao_beneficio.convenios", verbose_name="Entidades"
            ),
        ),
        migrations.AlterField(
            model_name="unicoparameter",
            name="stores",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_%(class)s_stores",
                to="custom_auth.corban",
                verbose_name="Lojas",
            ),
        ),
    ]
