# Generated by Django 4.2.3 on 2024-01-22 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documentscopy",
            "0009_alter_bpoconfig_entities_alter_bpoconfig_stores_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="unicoparameterfacematch",
            name="corban_action",
            field=models.IntegerField(
                choices=[(0, "Aprovar"), (1, "Análise Mesa"), (2, "Reprovar")],
                default=0,
                verbose_name="Ação",
            ),
        ),
        migrations.AlterField(
            model_name="unicoparameterfacematch",
            name="score_from",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MaxValueValidator(-100)],
                verbose_name="De",
            ),
        ),
        migrations.AlterField(
            model_name="unicoparameterfacematch",
            name="score_to",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(-99),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Até",
            ),
        ),
    ]
