# Generated by Django 4.2.3 on 2024-01-22 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentscopy", "0010_alter_unicoparameterfacematch_corban_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unicoparameterfacematch",
            name="score_from",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MaxValueValidator(1000)],
                verbose_name="De",
            ),
        ),
    ]
