# Generated by Django 4.2.3 on 2024-01-24 21:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documentscopy", "0012_alter_unicoparameterfacematch_score_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="BPORow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bpo",
                    models.IntegerField(
                        choices=[(0, "Serasa")], default=0, verbose_name="BPO"
                    ),
                ),
                (
                    "amount_from",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="R$ Inicial",
                    ),
                ),
                (
                    "amount_to",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="R$ Final",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentscopy.bpoconfig",
                        verbose_name="Parametro",
                    ),
                ),
            ],
            options={
                "verbose_name": "BPOs",
                "verbose_name_plural": "BPOs",
            },
        ),
    ]
