# Generated by Django 4.2.3 on 2024-01-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentscopy", "0013_bporow"),
    ]

    operations = [
        migrations.CreateModel(
            name="UF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uf",
                    models.SmallIntegerField(
                        choices=[
                            (1, "AC"),
                            (2, "AL"),
                            (3, "AP"),
                            (4, "AM"),
                            (5, "BA"),
                            (6, "CE"),
                            (7, "DF"),
                            (8, "ES"),
                            (9, "GO"),
                            (10, "MA"),
                            (11, "MT"),
                            (12, "MS"),
                            (13, "MG"),
                            (14, "PA"),
                            (15, "PB"),
                            (16, "PR"),
                            (17, "PE"),
                            (18, "PI"),
                            (19, "RJ"),
                            (20, "RN"),
                            (21, "RS"),
                            (22, "RO"),
                            (23, "RR"),
                            (24, "SC"),
                            (25, "SP"),
                            (26, "SE"),
                            (27, "TO"),
                        ],
                        default=1,
                        unique=True,
                        verbose_name="UF",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bpoconfig",
            name="age_from",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Idade - Mínima"
            ),
        ),
        migrations.AddField(
            model_name="bpoconfig",
            name="age_to",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Idade - Máxima"
            ),
        ),
        migrations.AddField(
            model_name="bpoconfig",
            name="score_from",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Score - Mínimo"
            ),
        ),
        migrations.AddField(
            model_name="bpoconfig",
            name="score_to",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Score - Máximo"
            ),
        ),
    ]
