# Generated by Django 4.2.3 on 2024-01-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentscopy", "0015_populate_ufs"),
    ]

    operations = [
        migrations.AddField(
            model_name="bpoconfig",
            name="ufs",
            field=models.ManyToManyField(
                blank=True, to="documentscopy.uf", verbose_name="UFs"
            ),
        ),
    ]
