# Generated by Django 4.2.3 on 2024-01-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentscopy", "0016_bpoconfig_ufs"),
    ]

    operations = [
        migrations.CreateModel(
            name="SerasaProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.CharField(max_length=11, null=True, verbose_name="CPF")),
                (
                    "protocol",
                    models.CharField(
                        max_length=11, null=True, verbose_name="Protocolo BRFlow"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Resultado"
                    ),
                ),
                ("processed", models.BooleanField(default=False)),
            ],
        ),
    ]
