# Generated by Django 4.2.3 on 2024-01-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0042_auto_20240122_1208"),
        ("documentscopy", "0017_serasaprotocol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bpoconfig",
            name="corbans",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"corban_type": 1},
                related_name="%(app_label)s_%(class)s_corbans",
                to="custom_auth.corban",
            ),
        ),
        migrations.AlterField(
            model_name="unicoparameter",
            name="corbans",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"corban_type": 1},
                related_name="%(app_label)s_%(class)s_corbans",
                to="custom_auth.corban",
            ),
        ),
    ]
