# Generated by Django 4.2.3 on 2024-01-30 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0156_statuscontrato_descricao_front"),
        ("documentscopy", "0018_alter_bpoconfig_corbans_alter_unicoparameter_corbans"),
    ]

    operations = [
        migrations.AddField(
            model_name="serasaprotocol",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="serasa_protocol_contract",
                to="contract.contrato",
                verbose_name="Contrato",
            ),
        ),
    ]
