# Generated by Django 4.2.3 on 2024-02-20 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0160_alter_cartaobeneficio_status_and_more"),
        ("documentscopy", "0019_serasaprotocol_contract"),
    ]

    operations = [
        migrations.CreateModel(
            name="MostProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.CharField(max_length=14, null=True, verbose_name="CPF")),
                (
                    "protocol",
                    models.CharField(
                        max_length=11, null=True, verbose_name="Protocolo MOST"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Resultado"
                    ),
                ),
                ("processed", models.BooleanField(default=False)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="most_protocol_contract",
                        to="contract.contrato",
                        verbose_name="Contrato",
                    ),
                ),
            ],
        ),
    ]
