# Generated by Django 4.2.3 on 2024-02-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentscopy", "0020_mostprotocol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mostprotocol",
            name="protocol",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Protocolo MOST"
            ),
        ),
    ]
